### ISSUE TITLE
Tile in homekit.

### ISSUE THREAD

**Issue by oigroigm** [grzegorz914/homebridge-denon-tv#1]
Do not display the tile in homekit, in homebridge it is shown instead
In addition there is also this error
[AV receiver] Can not acces device: 192.168.1.5. Might be due to a wrong settings in config, error ReferenceError: volume is not defined:

**Comment by grzegorz914** [comment]
Please always post yours Config, 
Are U add the Accessory in HomeKit app?

**Comment by oigroigm** [comment]
I added the accessory in Homekit app and it is now shown.
this is my config
"platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "dark-mode",
            "restart": "sudo -n systemctl restart homebridge",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "tempUnits": "c",
            "sudo": false,
            "log": {
                "method": "systemd",
                "service": "homebridge"
            },
            "accessoryControl": {
                "debug": false
            },
            "platform": "config"
        },
        {
            "name": "AV receiver",
            "checkStateInterval": 5,
            "devices": [
                {
                    "host": "192.168.1.5",
                    "port": 80,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "name": "PLEX",
                            "reference": "DB"
                        }
                    ]
                }
            ],
            "platform": "DenonTv"
        }
]

**Comment by grzegorz914** [comment]
How do you add it in HomeKit? If U add it with PIN and the process was successfully done then must be available in the HomeKit app, otherwise post log from homebridge after restart.

**Comment by oigroigm** [comment]
thank you, now everything works.
