### ISSUE TITLE
Receiver not supported?

### ISSUE THREAD

**Issue by th3cube** [grzegorz914/homebridge-denon-tv#10]
My Receiver (Denon AVR-X2300W) isn´t working. 

```
[DenonTv] Device: 10.20.30.100, name: AV Receiver, state: Offline
```
I tried both Ports 80 and 8080. The Receiver dosn´t support HEOS. Does this Plugin only support heos Receivers?

**Comment by grzegorz914** [comment]
Put this in web browser and get the output:

http://ipreceiver:port/goform/formMainZone_MainZoneXmlStatusLite.xml

**Comment by th3cube** [comment]
Output is 

```
ON SAT/CBL Absolute -50.0 off
```

**Comment by grzegorz914** [comment]
OK, will be fixed soon, wait for update.

**Comment by grzegorz914** [comment]
Please check ver 1.2.41

**Comment by th3cube** [comment]
FYI 
Its working flawless now. Many Thanks
