### ISSUE TITLE
Logs are extremely verbose even disable log info is checked

### ISSUE THREAD

**Issue by bwt615** [grzegorz914/homebridge-denon-tv#100]
Makes homebridge unusable for me

**Comment by grzegorz914** [comment]
After disable log info is nothing in the homebridge log, can You provide example of Your log?

**Comment by bwt615** [comment]
[4/19/2021, 1:02:23 PM] [DenonTv] Device: XXX.XXX.X.XXX AV Receiver, requesting Device state.
[4/19/2021, 1:02:23 PM] [DenonTv] Device: XXX.XXX.X.XXX AV Receiver, debug response: <?xml version="1.0" encoding="utf-8" ?>
<item>
<Power><value>OFF</value></Power>
<InputFuncSelect><value>MPLAY</value></InputFuncSelect>
<VolumeDisplay><value>Absolute</value></VolumeDisplay>
<MasterVolume><value>-10.0</value></MasterVolume>
<Mute><value>off</value></Mute>

**Comment by grzegorz914** [comment]
You have enabled debug mode, turn it off.

**Comment by bwt615** [comment]
What does : "disableLogInfo": true do then? very misleading

**Comment by grzegorz914** [comment]
This disable log Info, not a debug mode.  U can disable debug mode in Homebridge config.

**Comment by bwt615** [comment]
But I keep debug mode on for Homebridge UI. Your app is the chattiest by far.

[https://i.imgur.com/zf87pbX.jpg]
Benjamin Wesley Thomas
m +1 (781) 864-3648 | f +1 (781) 787-2609
e ***@***.***
w www.benjaminwesleythomas.com
[https://i.imgur.com/LekBgmL.png]<https://twitter.com/benjaminwthomas> [https://i.imgur.com/lyRQWJR.png] <https://www.linkedin.com/in/benjaminwesleythomas/>
On Apr 19, 2021, 1:35 PM -0400, Grzegorz ***@***.***>, wrote:

This disable log Info, not a debug mode. U can disable debug mode in Homebridge config.

**Comment by grzegorz914** [comment]
Then restrict only for Config UI X, if U just enabled debug mode in Homebridge settings, then is enabled for all plugins.
