### ISSUE TITLE
Question - which input should I use for airplay?

### ISSUE THREAD

**Issue by luigi-lauro** [grzegorz914/homebridge-denon-tv#102]
I cannot find the proper 'input' to put in configuration in order to switch my Denon AVC-X8500H to AirPlay mode. Also useful so that when I'm airplaying, it will show it's on the proper input (right now it just shows the first input). Thank you for the wonderful plugin! :-)

**Comment by luigi-lauro** [comment]
Also a minor thing - many input modes in configuration have typos (e.g. BLUE-RAY, BLUETOTH), or seems duplicated (e.g. SAT/CBL & CBL/SAT)

**Comment by grzegorz914** [comment]
SAT/CBL & CBL/SAT are not duplicated, Code receivers use different inputs in api. 
Typos will be fixed. 
AirPlay input will be added soon.

**Comment by grzegorz914** [comment]
On my receiver AVR-X6300H AirPlay is a NET, if U can please disable “Hiden Log Info” in Plugin settings and restart homebridge, next look in The log, there must be displayed reference for AirPlay. 
Paste Here the log and I add this iniput  to the choice list.

**Comment by luigi-lauro** [comment]
Thank you Grzegorz (polish?), I will try and report back. Very appreciated your feedback!

**Comment by luigi-lauro** [comment]
You were indeed right... it's NET.

[5/3/2021, 7:24:14 PM] [homebridge-denon-tv] Device: 192.168.4.71 Amplificatore Sala Main Zone, get current Input successful: TV Audio NET
[5/3/2021, 7:24:14 PM] [homebridge-denon-tv] Device: 192.168.4.71 Amplificatore Sala, get current Power state successfull, state: ON

**Comment by luigi-lauro** [comment]
I tried to map it with NETWORK and now it works and shows my custom label (AirPlay). So it's just perfect, nothing to do, thank you Grzegorz! Maybe just a small suggestion - add maybe a description next to the input NAME between brackets so to explain what that INPUT is used for, example "NETWORK (incl. AirPlay)" or just NETWORK/AIRPLAY to clarify. Thank you!

**Comment by grzegorz914** [comment]
Yes polish.

Thanks for Your suggestion, will add it in next update.

**Comment by luigi-lauro** [comment]
> Yes polish.
> 
> Thanks for Your suggestion, will add it in next update.

Wonderful, have quite a few polish friends in Krakow. Fantastic city & country :-) and thank you for picking up my suggestion :-)

**Comment by grzegorz914** [comment]
Updated
