### ISSUE TITLE
8K input in configuration panel

### ISSUE THREAD

**Issue by JeedPi** [grzegorz914/homebridge-denon-tv#109]
First of all thanks for the great plugin!
On the AVR-X3700, one of the input is named "8K". 
I got it to work by changing the configuration JSON, but it would be nice to have the "8K" input in the list. 

Thank you

**Comment by grzegorz914** [comment]
Can You post Here the reference of 8KInput. i will Add it.

**Comment by JeedPi** [comment]
Sure. The log entry says "Reference: 8K"

**Comment by grzegorz914** [comment]
Thanks

**Comment by grzegorz914** [comment]
One może thing, can be used for all zones?

**Comment by JeedPi** [comment]
yes - I use it for a headset, and I can use the headset while playing the Playstation that is on this input. 

Thanks again!

**Comment by grzegorz914** [comment]
added in 3.11.1

**Comment by JeedPi** [comment]
Works like a charm, thank you!
