### ISSUE TITLE
Unconfigured input

### ISSUE THREAD

**Issue by Heukers** [grzegorz914/homebridge-denon-tv#112]
i have 4 inputs configured and since the recent updates i have an extra unconfigured input extra in the list at the top....

I cannot find how it gets there and how to get it deleted.... can you help?

the following inputs are in the config....

 "inputs": [
                        {
                            "name": "TV",
                            "reference": "TV",
                            "mode": "SI"
                        },
                        {
                            "name": "Airplay",
                            "reference": "NET",
                            "mode": "SI"
                        },
                        {
                            "name": "FM",
                            "reference": "TUNER",
                            "mode": "SI"
                        },
                        {
                            "name": "Internet radio",
                            "reference": "IRADIO",
                            "mode": "SI"
                        }

The following screenshot is from my homekit app....

![Schermafbeelding 2021-09-06 om 11 51 39](https://user-images.githubusercontent.com/46219592/132198638-d155e761-1edb-4cb5-af1d-fff92d2af2e2.png)

**Comment by grzegorz914** [comment]
It is Created by Default, If You Switch Receiver to Input which not exist In Your Config List Then will displayed the Unconfigured Input. You can always hide it in HomeKit  settings.

**Comment by Heukers** [comment]
Thnx! 

So easy.... i did not expect to find the solution there.... but next time i look further then just homebridge and the plugin settings/config...
