### ISSUE TITLE
Marantz SR6013 - Volume in Homebridge Config UI X but not Homekit

### ISSUE THREAD

**Issue by intrepidsilence** [grzegorz914/homebridge-denon-tv#12]
Hi there. I managerd to get the base working where I can see the Receiver in the Accessories page of Homebridge Config UI X and I also se a volume accessory there that works fine. When I add the accessory to Homekit I only get one buton that turns the receiver on and off and if i long press I can try to change the input but I do not get a way to change the volume.  What am I missing?

Here is my platform config:
```
{
            "platform": "DenonTv",
            "devices": [
                {
                    "name": "AV Receiver",
                    "host": "192.168.15.46",
                    "port": 8080,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "name": "PS4",
                            "reference": "BD"
                        },
                        {
                            "name": "TV Audio",
                            "reference": "TV"
                        },
                        {
                            "name": "AppleTV",
                            "reference": "MPLAY"
                        },
                        {
                            "name": "PS3",
                            "reference": "DVD"
                        },
                        {
                            "name": "Cable",
                            "reference": "SAT/CBL"
                        },
                        {
                            "name": "Phono",
                            "reference": "Phono"
                        },
                        {
                            "name": "HTPC",
                            "reference": "AUX2"
                        }
                    ]
                }
            ]
        }
```

Thanks in advance!

**Comment by intrepidsilence** [comment]
I should have included my platform statement:

{
            "platform": "DenonTv",
            "devices": [
                {
                    "name": "AV Receiver",
                    "host": "192.168.15.46",
                    "port": 8080,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "name": "PS4",
                            "reference": "BD"
                        },
                        {
                            "name": "TV Audio",
                            "reference": "TV"
                        },
                        {
                            "name": "AppleTV",
                            "reference": "MPLAY"
                        },
                        {
                            "name": "PS3",
                            "reference": "DVD"
                        },
                        {
                            "name": "Cable",
                            "reference": "SAT/CBL"
                        },
                        {
                            "name": "Phono",
                            "reference": "Phono"
                        },
                        {
                            "name": "HTPC",
                            "reference": "AUX2"
                        }
                    ]
                }
            ]
        }

**Comment by grzegorz914** [comment]
This is TV acccesory and do not get extra volume control tile, U can change volume using Siri or go to RC control app and use Hardware button on iPhone.

**Comment by intrepidsilence** [comment]
OK, I understand. Could you help me understand how to change the volume with Siri then? I have tried by asking it to change the volume of the AV receiver and the brightness of the AV receiver, including and excluding the location and it tells me it cannot do that every time.

**Comment by TheChallinor** [comment]
@grzegorz914 When you say the RC control app do you mean the Denon app?

I wanted to control my Denon volume off my Apple Watch to my receiver.

**Comment by grzegorz914** [comment]
RC control app on iPhone/iPad

![FDA33F91-BBB6-42BB-956F-4A2C8C7B96C3](https://user-images.githubusercontent.com/28867813/79639143-07875100-818a-11ea-8cfa-57070e7dccf1.jpeg)

**Comment by TheChallinor** [comment]
Ah got you, I can turn the Denon on and off but have no access to volume control. 

P.S. Thanks for the swift reply.

**Comment by grzegorz914** [comment]
I think the issue is resolved.

**Comment by intrepidsilence** [comment]
I don't feel that this issue is closed.  You never answered my question: "Could you help me understand how to change the volume with Siri then? I have tried by asking it to change the volume of the AV receiver and the brightness of the AV receiver, including and excluding the location and it tells me it cannot do that every time."

**Comment by sbernhardt81** [comment]
I have the feeling it is a limitation with Siri. Alexa is doing great.
Siri allways tells me she can’t do it.

**Comment by sbernhardt81** [comment]
For Siri Volume Control I propose this plugin.

https://www.npmjs.com/package/homebridge-marantz-volume

It adds also the apple watch control, which doesn’t work with the TV implementation either.

**Comment by TheChallinor** [comment]
I’m doing the same thing and this plug-in works great
