### ISSUE TITLE
Denon AVCX6500H unable to access in Home Kit

### ISSUE THREAD

**Issue by DarkRogue71** [grzegorz914/homebridge-denon-tv#13]
Hi,
Not sure if I am doing anything wrong here as I can't get the amp to work in HomeKit.  I can add it but it says that it cannot get updates from the device.
Cheers
Drago

**Comment by grzegorz914** [comment]
Log please?

**Comment by DarkRogue71** [comment]
Thanks for having a look - hope this is what you need.

[Homebridge log Denon copy.docx](https://github.com/grzegorz914/homebridge-denon-tv/files/4468135/Homebridge.log.Denon.copy.docx)

**Comment by grzegorz914** [comment]
Looks like all is ok, can U provide Your complete config?
Where U get the info “it says that it cannot get updates from the device” I do not see this in log, please run homebridge in debug mode -D and get this log.

Put this in web browser and get the output:
http://ipreceiver:port/goform/formMainZone_MainZoneXmlStatusLite.xml

**Comment by DarkRogue71** [comment]
When I meant it can't get updates from device, this is what the Home App on my iOS device is saying not the Homebridge - maybe I am not setting things up on in the Home app properly.

ON TV Absolute -31.0 off

[config..docx](https://github.com/grzegorz914/homebridge-denon-tv/files/4468219/config.docx)

**Comment by grzegorz914** [comment]
Your config should be:

```
{
    "bridge": {
        "name": "Homebridge 237C",
        "username": "0E:90:CD:64:23:7C",
        "port": 51537,
        "pin": "906-71-005"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "platform": "DenonTv",
            "devices": [
                {
                    "name": "Denon Living Room Amp",
                    "host": "192.168.100.206",
                    "port": 8080,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "name": "Fetch",
                            "reference": "DVD"
                        },
                        {
                            "name": "Blu-ray",
                            "reference": "BD"
                        },
                        {
                            "name": "TV Audio",
                            "reference": "TV"
                        },
                        {
                            "name": "Tuner",
                            "reference": "TUNER"
                        },
                        {
                            "name": "Media Player",
                            "reference": "MPLAY"
                        }
                    ]
                }
            ]
        }
    ]
}
```

always look here for correct references: 
https://github.com/grzegorz914/homebridge-denon-tv#configuration

**Comment by DarkRogue71** [comment]
Thanks!!

**Comment by grzegorz914** [comment]
I think is working now, if so then I close this issue. If U get other problems please open new issue.
