### ISSUE TITLE
Feature request: input mode presence

### ISSUE THREAD

**Issue by elministerr** [grzegorz914/homebridge-denon-tv#131]
Hi,

thanks for your great plugin. it works like a charm!

But there is one thing i miss there. is it possible to create/build a presence sensor for input modes ? 

e.g create a presence sensor for DVD Input and when DVD Input are selected the presence sensor are turned on and when deselected it turns off. 

This could help me for some automations. 

Regards

**Comment by grzegorz914** [comment]
@elministerr 
can You test 3.16.0-beta and let me know
the reference can be found beta branch:
https://github.com/grzegorz914/homebridge-denon-tv/tree/3.16.0-beta

**Comment by elministerr** [comment]
wow.. that was quick :) it seems to be working. it would be nice to change the type from switch to motion/occupancy sensor. In my case i don't need a switch. I try this now with a few automations and let you know how it works. Thanks!

**Comment by grzegorz914** [comment]
try beta 12, possible to select as type are `Switch`, `Button`, `Motion Sensor`, `Ocupancy Sensor`

**Comment by elministerr** [comment]
Well done! Thanks
