### ISSUE TITLE
Device is not showing up in 3rd party Homekit apps

### ISSUE THREAD

**Issue by hansw1204** [grzegorz914/homebridge-denon-tv#137]
My accessory shows up in the Home app but not in any 3rd party apps. I'v recently tried to add some scenes that contain the accessory to widgets on my iPhone but that fails because the device is not seen by the app. Is there a way to make Denon accessories visible to 3rd party homekit apps?
Many thanks

**Comment by grzegorz914** [comment]
Check ob 3rd party app support television accessory.

**Comment by hansw1204** [comment]
Thank you, will do.

 

From: Grzegorz ***@***.***>
Reply-To: grzegorz914/homebridge-denon-tv ***@***.***>
Date: Tuesday, February 22, 2022 at 12:42
To: grzegorz914/homebridge-denon-tv ***@***.***>
Cc: Hans Winkler ***@***.***>, Author ***@***.***>
Subject: Re: [grzegorz914/homebridge-denon-tv] Device is not showing up in 3rd party Homekit apps (Issue #137)

 

Check ob 3rd party app support television accessory.

**Comment by grzegorz914** [comment]
I coke this as not a plugin problem.
