### ISSUE TITLE
No configuration found for homebridge-denon-tv

### ISSUE THREAD

**Issue by Judge74** [grzegorz914/homebridge-denon-tv#14]
Hi! I’m sure it must be something to do with my Config but I can’t work out why it’s not finding it on initialisation, please help? 

[4/18/2020, 14:32:11] [Denon AVR] No configuration found for homebridge-denon-tv
[4/18/2020, 14:32:11] [Denon AVR] Initializing DenonTv platform...

  "platforms" : [
    {
      "devices" : {
        "host" : "192.168.0.98",
        "name" : "AV Receiver",
        "switchInfoMenu" : "true",
        "port" : "8080"
      },
      "inputs" : [
        {
          "name" : "Xbox One",
          "reference" : "GAME"
        }
      ],
      "name" : "Denon AVR",
      "platform" : "DenonTv"
    },

**Comment by grzegorz914** [comment]
Your config is wrong:

```
  "platforms": [
        {
            "platform": "DenonTv",
            "devices": [
                {
                    "name": "AV Receiver",
                    "host": "192.168.0.98",
                    "port": 8080,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "name": "Xbox One",
                            "reference": "GAME"
                        },
                        {
                            "name": "Telewizor",
                            "reference": "TV"
                        },
                        {
                            "name": "Tuner Sat",
                            "reference": "SAT/CBL"
                        },
                        {
                            "name": "CD",
                            "references": "CD"
                        }
                    ]
                }
            ]
```
