### ISSUE TITLE
Scènes with different inputs do not work.

### ISSUE THREAD

**Issue by Garia666** [grzegorz914/homebridge-denon-tv#141]
Hi ,  when I start my start tv scene it works great. Tv goes on, my hue back lightning strip and the receiver with the source i configured.

however when my son wants to play the Nintendo switch, I have the same scene the only thing different is the source.   But since it’s already activated the source does not change. 

When I start the scene when the receiver is off then it does work.

Anyone with an bright idea?

thanks in advance 

G6

**Comment by grzegorz914** [comment]
Can you try 3.17.21-beta.0 and let me know

**Comment by Garia666** [comment]
> 

Sir you are my hero, work like a charm now and the sound issue has been fixed aswell

**Comment by grzegorz914** [comment]
Nice. thanks for info.

**Comment by Garia666** [comment]
> Nice. thanks for info.

I couldnt find a donate button, but there was a sponsor button so i did a small donation.  thanks again
