### ISSUE TITLE
AVR unresponsive in home app

### ISSUE THREAD

**Issue by rpungello** [grzegorz914/homebridge-denon-tv#143]
I recently updated to the latest version of the plugin. I was running into issues with the Home app on my phone, then I saw the note in the readme about needing to remove and re-add the device in HomeKit.
I also saw steps for removing files from homebridge/persist, which I also did.
I removed the AVR from the Home app on my phone, deleted the persist files, then restarted Homebridge.
I then re-added the AVR in the Home app, which seemed to work fine.
However, the home app cannot actually control the AVR, despite it adding seemingly fine.
I can control it from the Homebridge "Accessories" page on the web app, but no iOS device can control it.
Somehow it seems there's a communication issue between iOS and HomeBridge, but I'm not sure how to troubleshoot from here.

**Comment by grzegorz914** [comment]
still the problem here
