### ISSUE TITLE
"BRANDCODE" error

### ISSUE THREAD

**Issue by DueHack12** [grzegorz914/homebridge-denon-tv#144]
Hello,

I have been trying to get my denon receiver to connect to homebridge for about 3 days now. I saw it was not connecting so I turned on debug and saw "TypeError: Cannot read property 'BrandCode'". Any ideas on how to fix this error?

This is similar to [#76](https://github.com/grzegorz914/homebridge-denon-tv/issues/76) and [#44](https://github.com/grzegorz914/homebridge-denon-tv/issues/44)

**Comment by grzegorz914** [comment]
try 3.7.12-beta.o and let me know, also post the log with debug ON

**Comment by DueHack12** [comment]
Same error. Attached is the log file with just the DenonTv plugin showing.

[homebridge log](https://github.com/grzegorz914/homebridge-denon-tv/files/8550628/homebridge.log.txt)

Hope this helps!

**Comment by grzegorz914** [comment]
try beta 2

**Comment by grzegorz914** [comment]
@DueHack12 
any info?
