### ISSUE TITLE
possible to extend to other similar receivers?

### ISSUE THREAD

**Issue by mrMiimo** [grzegorz914/homebridge-denon-tv#145]
is it possible to extend this plugin to other similar receivers like Pioneer VSX? (e.g. https://github.com/martinalmlof/homebridge-pioneer-vsx527)
I have mqtt integrated with the "pioneer vsx 1021" model receiver but I don't have a hombrige compatible plugin that accepts mqtt.
<img width="1503" alt="Schermata 2022-05-04 alle 10 36 53" src="https://user-images.githubusercontent.com/49750870/166661009-54f3e584-2a43-4333-9101-dd34561e7673.png">

![Schermata 2022-05-04 alle 11 51 50](https://user-images.githubusercontent.com/49750870/166661033-05d4b0fb-12d8-4fd3-ace6-bbcd069eebee.png)

Any help is appreciated 🥺...
Regards ✋🏼

**Comment by grzegorz914** [comment]
Not plan to extends support to other brand in one plugin. Pioneer use other api to communicate, is better to use dedicated plugin.
