### ISSUE TITLE
Socket Hangup

### ISSUE THREAD

**Issue by simplytoast1** [grzegorz914/homebridge-denon-tv#146]
I have a Denon AVR-X2700H and configured the plugin but keep getting the following error:

Device: XXX.XXX.XXX.47 Media Room Denon, Device info error: Error: socket hang up

I confirmed the HTTP port is correct

**Comment by grzegorz914** [comment]
Power cycle Your receiver Please

**Comment by simplytoast1** [comment]
I was doing a soft power with no luck.  A good ol remove the plug and plug it back in fixed the issues.  Thanks!

**Comment by Yashrg** [comment]
I had the same issue. So I decided to try the power cycle trick. didn't work for me unfortunately :( mine is a Denon AVR-S940H
