### ISSUE TITLE
HomeKit does not find the Denon Plugin

### ISSUE THREAD

**Issue by Robnbill** [grzegorz914/homebridge-denon-tv#148]
Using 3.7.13 (also tried 3.7.12).    I took the actions laid out in #125 #124 #104.  I've tried those a couple of times - no luck.  Homebridge finds the Denon and is able to connect to it- see log below.  

I'm switching over to HB from HOOBS.  There is a working Denon Plugin (3.7.12) in HomeKit via HOOBS - works as designed.  I did not delete that.  Should I?

Log attached with JSON below.

Thanks!

[homebridge.log](https://github.com/grzegorz914/homebridge-denon-tv/files/9202827/homebridge.log)

{
    "devices": [
        {
            "name": "GreatRoomAVR",
            "host": "192.168.1.78",
            "port": 80,
            "zoneControl": 0,
            "volumeControl": 0,
            "masterPower": false,
            "masterVolume": true,
            "masterMute": true,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "enableDebugMode": true,
            "inputs": [
                {
                    "name": "Apple",
                    "reference": "DVD",
                    "mode": "SI",
                    "displayType": 0
                },
                {
                    "name": "TiVo",
                    "reference": "SAT/CBL",
                    "mode": "SI"
                }
            ],
            "buttonsMainZone": [
                {
                    "name": "Power On",
                    "reference": "ZMON",
                    "displayType": 1
                },
                {
                    "name": "Power Off",
                    "reference": "ZMOFF",
                    "displayType": 1
                }
            ],
            "enableMqtt": false,
            "mqttAuth": false,
            "mqttDebug": false
        }
    ],
    "platform": "DenonTv"
}

**Comment by grzegorz914** [comment]
Yes, you can not use same plugin two times. Please delete it first from Homebridge and HomeKit app and try add it again.

**Comment by Robnbill** [comment]
Sorry it took so long to get back.  Your recommendation works.  I was able to move from HB to HK.  Your plugin is controlling my Denon and Marantz's AVRs.  Thanks
