### ISSUE TITLE
Getting an ECONNREFUSED error code.

### ISSUE THREAD

**Issue by DMcWetty** [grzegorz914/homebridge-denon-tv#149]
Hi. Thanks so much for developing this plugin.

Plugin looks like exactly what I needed. Got everything setup but I'm getting "[8/23/2022, 10:54:42 AM] [homebridge-denon-tv] Device: 192.168.5.141 Marantz Amp, Device info error: Error: connect ECONNREFUSED [192.168.5.141:9034](https://192.168.5.141:9034/)" in the log.
I had to open up a new port (9034) and forwarded it to 8080 after making an IP reservation.
Wondering if it was the Marantz, I tried it on my S760 and X3400 as well... similar errors:
"[8/23/2022, 10:59:23 AM] [homebridge-denon-tv] Device: 192.168.7.16 Office Denon, Device info error: Error: connect ECONNREFUSED [192.168.7.16:9134](https://192.168.7.16:9134/)" and "[8/23/2022, 11:01:56 AM] [homebridge-denon-tv] Device: 192.168.6.193 Theater Denon, Device info error: Error: connect ECONNREFUSED [192.168.6.193:9234](https://192.168.6.193:9234/) ".
Suggestion?

**Comment by grzegorz914** [comment]
Can you ping the device on this port?

**Comment by DMcWetty** [comment]
Seems to be pinging just fine. Here’s the terminal feedback:

ping 192.168.5.141
PING 192.168.5.141 (192.168.5.141): 56 data bytes
64 bytes from 192.168.5.141: icmp_seq=0 ttl=64 time=12.982 ms
64 bytes from 192.168.5.141: icmp_seq=1 ttl=64 time=11.038 ms
64 bytes from 192.168.5.141: icmp_seq=2 ttl=64 time=7.406 ms
64 bytes from 192.168.5.141: icmp_seq=3 ttl=64 time=16.979 ms
64 bytes from 192.168.5.141: icmp_seq=4 ttl=64 time=9.425 ms
64 bytes from 192.168.5.141: icmp_seq=5 ttl=64 time=8.156 ms
64 bytes from 192.168.5.141: icmp_seq=6 ttl=64 time=6.964 ms
^C
--- 192.168.5.141 ping statistics ---
7 packets transmitted, 7 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 6.964/10.421/16.979/3.319 ms

Do I need to bother adding the :9034 port?

Dave

**Comment by grzegorz914** [comment]
Please Ping with the port 9034

**Comment by DMcWetty** [comment]
***@***.*** ~ % ping 192.168.5.141:8080
ping: cannot resolve 192.168.5.141:8080: Unknown host
***@***.*** ~ % ping 192.168.5.141:9034
ping: cannot resolve 192.168.5.141:9034: Unknown host

Seems to be a no-go.

Dave

**Comment by grzegorz914** [comment]
So, it’s Your local network problem.

**Comment by DMcWetty** [comment]
I attached a SS of the Eero app with the port forwarded. I tried 9034 -> 8080 and 9034 -> 9034

Dave

**Comment by grzegorz914** [comment]
Why you forward the port, is the Homebridge not on the same network as the AV Receiver?

**Comment by DMcWetty** [comment]
I got the two denon avr working. Still can’t get the Marantz to work. But I’m sure it’s not an issue with the plug-in. Thanks.

Dave

**Comment by DMcWetty** [comment]
I tried 80, 8080, 23, and 1255.

Dave

**Comment by DMcWetty** [comment]
I tried 80, 8080, 23, and 1255. The Marantz uses the HEOS app just like the Denons.

Dave
