### ISSUE TITLE
Default input at power on :enhancement 

### ISSUE THREAD

**Issue by oigroigm** [grzegorz914/homebridge-denon-tv#15]
Would it be possible to add the default input at power on?

**Comment by grzegorz914** [comment]
U can define default input creating scene in HomeKit app.

**Comment by oigroigm** [comment]
thanks for the reply, but it doesn't work, creating a scene always turns on with the last selected input

**Comment by grzegorz914** [comment]
OK, I will test it.

**Comment by grzegorz914** [comment]
I have tested scene and working every time, no any problem. Are U defined Input in Your scene?

**Comment by oigroigm** [comment]
I tried again but the input does not change, in my opinion it would take a delay between switching on and sending the input command

**Comment by grzegorz914** [comment]
How du You create the scene?

**Comment by oigroigm** [comment]
![Istantanea schermo 2020-04-20 (13 49 38) 75608](https://user-images.githubusercontent.com/46646276/79748582-fbc49780-830d-11ea-82ce-32dd7bb6b97d.png)
![Istantanea schermo 2020-04-20 (13 51 38)](https://user-images.githubusercontent.com/46646276/79748705-27478200-830e-11ea-9f94-8e9097bad2e6.png)

**Comment by grzegorz914** [comment]
This is not a a scene, U create automation. Scene working OK, automation need to testing and I will report today.

**Comment by oigroigm** [comment]
I also tried to create a scene but it doesn't work anyway
the denon turns on but the input set before remains

![Istantanea schermo 2020-04-20 (17 03 58)](https://user-images.githubusercontent.com/46646276/79767015-0cced200-8329-11ea-844f-474b97564a60.png)

**Comment by grzegorz914** [comment]
What a model U have? on my AVRX-6300H all working without any problems.

**Comment by oigroigm** [comment]
I have a DRA-N5, normally the input change works regularly, the thing that I found that it takes a while to turn on

**Comment by sbernhardt81** [comment]
I tested your approach as well. Created a scence with AUX as input and it works fine.
It powers up and changes to AUX. I turned it off with a different input.
My Model is the AVR-X2500H

**Comment by grzegorz914** [comment]
> I have a DRA-N5, normally the input change works regularly, the thing that I found that it takes a while to turn on

Please Run Homebridge in debug mode -D, and get the log while start the scene.

**Comment by grzegorz914** [comment]
> I tested your approach as well. Created a scence with Activate AV Receiver and set AUX as input and it works fine.
> It powers up and changes to AUX. I turned it off with a different input.
> My Model is the AVR-X2500H

Thanks for testing.

**Comment by oigroigm** [comment]
[4/20/2020, 5:55:54 PM] [DenonTv] Device: 192.168.1.6, get current Power state successfull: STANDBY
[4/20/2020, 5:55:54 PM] [DenonTv] Device: 192.168.1.6, get current Input successfull: IPOD
[4/20/2020, 5:55:54 PM] [DenonTv] Device: 192.168.1.6, set new Power state successfull: ON
[4/20/2020, 5:55:54 PM] [DenonTv] Device: 192.168.1.6, set new Input successfull: AUXD

everything seems to be working but my denon needs more time after the power on to change the input

**Comment by grzegorz914** [comment]
May be U have connected something with HDMI CEC which switch the input back.

**Comment by oigroigm** [comment]
I only connected the TV via AUXD, I checked and after turning on before I can change something it takes a few seconds, the power on procedure is slow in this denon

**Comment by grzegorz914** [comment]
That can be problem, but I think U can live wit this small problem.

**Comment by oigroigm** [comment]
if it is not complicated can you insert a delay to be set in config.json?

**Comment by grzegorz914** [comment]
check latest version please and get feedback
