### ISSUE TITLE
No buttons or switches present

### ISSUE THREAD

**Issue by kolakub** [grzegorz914/homebridge-denon-tv#153]
Hello,

I was having difficulty with my current Denon install in the home app, so I removed the app and made the DenonTv into a child node. I can add the hub, but there are no buttons or switches created in the home app.

The hub is attached to the home app and listed in the home hubs and bridges section, but nothing else.

**Comment by grzegorz914** [comment]
Look here: https://github.com/grzegorz914/homebridge-denon-tv/wiki

**Comment by kolakub** [comment]
Thank you, I was able to get it installed on the HOME app using the directions below. Unfortunately, Siri does not seem to recognize the switches but they work if I use the home app. Is there a naming scheme that you suggest?Appreciate the help.Sent from my iPadOn Oct 16, 2022, at 12:56 PM, Grzegorz ***@***.***> wrote:﻿
Look here: https://github.com/grzegorz914/homebridge-denon-tv/wiki

**Comment by HVR88** [comment]
Deleting the files from terminal allow the device to show up and it can then be added.  But as soon as the power button is pressed on the device details in Home, it goes unresponsive.

The logs in Homebridge also don't show the correct input as Homebridge starts up.

Running iOS 16.2, tvOS 16.2, and Homepod OS 16.2 - homekit has been updated to the new architecture.

**Comment by grzegorz914** [comment]
@HVR88  I can not reproduce this issue, you can enable debug mode in plugin config and post the log during make this procedure.
