### ISSUE TITLE
AxiosError: read ETIMEDOUT     at Function.AxiosError.from

### ISSUE THREAD

**Issue by Garia666** [grzegorz914/homebridge-denon-tv#154]
Hi Sadly i still get the Axios error, it doesnt fail as bad as the previous anymore however it still stops working. 

i get the following

[18/10/2022, 07:40:04] [homebridge-denon-tv] This plugin slows down Homebridge. The write handler for the characteristic 'Active Identifier' on the accessory 'G666 AV Receiver 792E' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.

[18/10/2022, 07:41:08] [DenonTv] Device: 192.168.2.32 G666 AV Receiver, Send command error: Error: read ETIMEDOUT
[18/10/2022, 07:41:08] [DenonTv] Device: 192.168.2.32 G666 AV Receiver, can not set Input. Might be due to a wrong settings in config, error: AxiosError: read ETIMEDOUT
    at Function.AxiosError.from (/usr/lib/node_modules/homebridge-denon-tv/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/usr/lib/node_modules/homebridge-denon-tv/node_modules/axios/lib/adapters/http.js:515:25)
    at RedirectableRequest.emit (node:events:513:28)
    at ClientRequest.eventHandlers.<computed> (/usr/lib/node_modules/homebridge-denon-tv/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:481:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  syscall: 'read',
  code: 'ETIMEDOUT',
  errno: -110,
  config: [Object],
  request: [Writable],
  cause: [Error]
}

followed by 

[18/10/2022, 07:41:13] [DenonTv] Device: 192.168.2.32 G666 AV Receiver, State error: Error: read ETIMEDOUT, reconnect in 15s.

when i make the reciever powerless and turn it back on it works again for a while untill it doesnt.

**Comment by grzegorz914** [comment]
This must be your specific problem in local network environment or problem with the AVR server. The plugin just have no access to your AVR, the server just not response.
I don’t observe this issue on my side, my Denon working without any issue.

**Comment by Garia666** [comment]
It has something to do with zone 2, as when the problem is their zone 2 is activated the original app shows heos is activated.  Why this happens I have no clue

**Comment by grzegorz914** [comment]
Can you post your config?

**Comment by Garia666** [comment]
"devices": [
                {
                    "name": "G666 AV Receiver",
                    "host": "192.168.2.32",
                    "port": 8080,
                    "zoneControl": 0,
                    "volumeControl": 2,
                    "masterPower": true,
                    "masterVolume": true,
                    "masterMute": false,
                    "infoButtonCommand": "MNINF",
                    "disableLogInfo": false,
                    "disableLogDeviceInfo": false,
                    "enableDebugMode": false,
                    "inputs": [
                        {
                            "name": "Tv",
                            "reference": "TV",
                            "mode": "SI",
                            "displayType": 0
                        },
                        {
                            "name": "KPN",
                            "reference": "SAT/CBL",
                            "mode": "SI"
                        },
                        {
                            "name": "NintendoSwitch ",
                            "reference": "GAME",
                            "mode": "SI"
                        },
                        {
                            "name": "Spotify",
                            "reference": "SPOTIFY",
                            "mode": "SI"
                        },
                        {
                            "name": "AirPlay ",
                            "reference": "NET",
                            "mode": "SI"
                        },
                        {
                            "name": "OnlineMusic",
                            "reference": "FVP",
                            "mode": "SI"
                        }
                    ],
                    "buttonsMainZone": [
                        {
                            "name": "Power on Denon",
                            "reference": "ZMON",
                            "displayType": 0
                        },
                        {
                            "name": "Power off denon",
                            "reference": "ZMOFF",
                            "displayType": 0
                        },
                        {
                            "name": "DTS",
                            "reference": "MSDTS SURROUND",
                            "displayType": 1
                        },
                        {
                            "name": "STEREO",
                            "reference": "MSMCH STEREO",
                            "displayType": 1
                        },
                        {
                            "name": "ROCK",
                            "reference": "MSROCK ARENA",
                            "displayType": 1
                        }
                    ],
                    "enableMqtt": false,
                    "mqttAuth": false,
                    "mqttDebug": false
                }
            ],
            "platform": "DenonTv"
        },

**Comment by grzegorz914** [comment]
Here is no zone 2 configured

**Comment by PelagicDev** [comment]
I was having a similar issue here and the issue was that my IP address had changed. Double check and make sure that your config is using the correct IP address for your device.

**Comment by Robnbill** [comment]
You may want to try reseting the network module.  I did and have not had an error with the current version.  See this thread:  https://www.avsforum.com/threads/the-official-2016-denon-s-series-x-series-avr-owners-thread-faq.2444306/

**Comment by Garia666** [comment]
Network reset didn’t work, I have switched from Ethernet to WiFi and so far no more crashes.  The crashes were building up getting more often. I have no clue as why this would even work.  Anyway I’ll give it some time.

**Comment by Garia666** [comment]
Sadly it has come back on WiFi,  is there any other way I can help troubleshooting this issue?

**Comment by Garia666** [comment]
I have updates all iPads and iPhones to the latest iOS versions. Maybe that helps

**Comment by Garia666** [comment]
There has been een firmware update for the Denon receiver, finger crossed.  I also updated everything to 16.2.    I am hoping this will resolve my issues

**Comment by kwhittenberger** [comment]
Adding myself to this thread as I am seeing the same issue.

**Comment by kwhittenberger** [comment]
> Adding myself to this thread as I am seeing the same issue. Note: I did not experience errors controlling the receiver (Marantz SR1603) until I upgraded my devices to iOS/tvOS 16.2 and upgraded my Home.

After pulling the power cord and restarting, this error went away for me.

**Comment by Garia666** [comment]
Sadly it came back, everything is up to date, latest architecture, updated firmware of the Denon receiver.  Out for the blue it starts and then keep building up crashing faster and faster.  I can probably downgrade to an very old version and see if that keeps stable.

**Comment by Garia666** [comment]
> > Adding myself to this thread as I am seeing the same issue. Note: I did not experience errors controlling the receiver (Marantz SR1603) until I upgraded my devices to iOS/tvOS 16.2 and upgraded my Home.
> 
> After pulling the power cord and restarting, this error went away for me.

This just works temporary

**Comment by grzegorz914** [comment]
Tej problem is in AVR server, it’s freezes after couple of times. To fixed it need to power cycle the AVR. In my environment with AVR-X6300H no any crash or freezing observed. I’m connected with LAN and use DHC on AVR side and reserve address on router side. I will and in next release the possibility to set custom polling time, may be this help someone.

**Comment by grzegorz914** [comment]
In 3.18.7 added possibility to set custom data refresh time in plugin settings advanced section. This can help to fix AVR server freezing.

**Comment by Garia666** [comment]
Thanks allot man I am testing it right now!

**Comment by Garia666** [comment]
Well it’s been a while and the error has not reoccurred after that, I changed the setting to the max possible. So it safe to say it’s fixed.  And like I promised I’ll make another small donation to the project.   Thanks man
