### ISSUE TITLE
Power Status via sensor

### ISSUE THREAD

**Issue by bwt615** [grzegorz914/homebridge-denon-tv#156]
I know you have it for each input, but what about one for overall power? Would be great for automation as third-party apps don't recognize AV receivers.

**Comment by grzegorz914** [comment]
I can add this to the buttons sections, same way as for inputs.

**Comment by bwt615** [comment]
> I can add this to the buttons sections, same way as for inputs.

You are awesome!

**Comment by grzegorz914** [comment]
3.18.0 published, 
## Changes
- added Power Motion Sensor for use with automations
- added Volume Motion Sensor for use with automations (every volume change report motion)
- added Mute Motion Sensor for use with automations
- config.schema updated
- other small fixes
