### ISSUE TITLE
AxiosError

### ISSUE THREAD

**Issue by Cesco117** [grzegorz914/homebridge-denon-tv#157]
Hi,

Since yesterday, I have this message, and I don't know how to resolve it.
I tried to test reverting to the older version, still the same issue.
IP is OK, static IP, do you have any tip to help resolve this please ?

Thanks a lot !

[11/6/2022, 10:28:02 PM] [DenonTv] Device: 192.168.0.107 Marantz, Info error: AxiosError: timeout of 10000ms exceeded, reconnect in 15s.

**Comment by grzegorz914** [comment]
Power cycle AVR

**Comment by Cesco117** [comment]
Seems like an UniFi AP WiFi issue, since I switched to Ethernet and working again.
Thanks for your quick reply anyway, I will test power cycling AVR next time if there's the same issue.
