### ISSUE TITLE
Error Log in Homebridge if the Reciver is not connected to electricity 

### ISSUE THREAD

**Issue by alert82** [grzegorz914/homebridge-denon-tv#158]
Hello Folks 

because of recent electricity costs i unplug all stuff i don't need always. 

i get following Error Code: 
[DenonTv] Device: 192.168.0.7 Denon, Info error: Error: connect ECONNREFUSED 192.168.0.7:8080, reconnect in 15s.

is there any way to turn that off?

**Comment by grzegorz914** [comment]
Stop child bridge
