### ISSUE TITLE
Turn on All Zones

### ISSUE THREAD

**Issue by ntableman** [grzegorz914/homebridge-denon-tv#16]
When I use this plugin it turns on all the zones. If possible would love to see the home kit devices (one for each zone) or for the single device to ignore zone 2.

**Comment by xxxchris** [comment]
thumbs up

**Comment by grzegorz914** [comment]
Be patient please😀

**Comment by grzegorz914** [comment]
Check latest version, added zone control.

**Comment by grzegorz914** [comment]
I close this because zone control was added.

**Comment by xxxchris** [comment]
Thank you :-)

**Comment by ntableman** [comment]
Awesome! Can I make a volume and control for both zones? It seems I can turn both on and off, but not volume and all that.

**Comment by grzegorz914** [comment]
> Awesome! Can I make a volume and control for both zones? It seems I can turn both on and off, but not volume and all that.

Are U sure If U set "zoneControl" to "Main Zone" the volume do not change the zone 2 volume?

**Comment by grzegorz914** [comment]
in 2.2.0 added master volume control (if enabled volume will change volume in all zones)

please test it and report

**Comment by grzegorz914** [comment]
bumped to 2.3.0
- removed master volume and power control
- added all zones control (if enabled all zones will be control togheter, (power, source input, volume, mute))
