### ISSUE TITLE
AxiosError still there…

### ISSUE THREAD

**Issue by 5v3n31** [grzegorz914/homebridge-denon-tv#161]
Device: 192.168.0.xyz Marantz SR7012, Info error: AxiosError: timeout of 10000ms exceeded, reconnect in 15s.

**Comment by grzegorz914** [comment]
In 3.18.7 added possibility to set custom data refresh time in plugin settings advanced section. This can help to fix AVR server freezing.

**Comment by 5v3n31** [comment]
After a couple of days at 10s refresh time, today it stopped working again.

**Comment by grzegorz914** [comment]
its not a plugin problem.
