### ISSUE TITLE
Volume control info

### ISSUE THREAD

**Issue by piejanssens** [grzegorz914/homebridge-denon-tv#163]
Volume control is either through the RC app (works great btw), or as a light/fan control in Home?
It's not possible to get a speaker or other volume control in the Home app?

My use case is volume control of Apple Music over multiple zones.
Since Denon shows up a a single receiver in Apple Music, there is no distinctive control through that app over different zones.
I'm very happy with the ability to add the different zones and control it via the Remote app, but I was just wondering if that would also make it appear as a speaker/tv control within the Home app. (At the moment, I see them as 'amp' devices)

**Comment by grzegorz914** [comment]
For speaker or other volume control just create extra buttons for every zone/surround.
