### ISSUE TITLE
Version 3.20 no connection to device

### ISSUE THREAD

**Issue by Heukers** [grzegorz914/homebridge-denon-tv#165]
I installed version 3.20 and after a reboot the device was vissibel in homekit, but without connection (reaction). Checked if i had to change something in the configuration, but everytihng looked fine... switcht back to version 3.19.2 and everything was oké... Do i have to do something else in the configuration or is there a problem with this version?

**Comment by grzegorz914** [comment]
fixed in 3.20.1
