### ISSUE TITLE
Support for old AVR like 3311CI…

### ISSUE THREAD

**Issue by IIHiradorII** [grzegorz914/homebridge-denon-tv#166]
Hi!
i'm facing this error with Denon AVR-3311

`[homebridge-denon-tv] Device: 192.168.1.109 DENON AVR-3311, debug: Info: undefined`
`[homebridge-denon-tv] Device: 192.168.1.109 DENON AVR-3311, Info error: TypeError: Cannot read properties of undefined (reading 'BrandCode'), reconnect in 15s.`

Just have made multiple attempts in both starndard and child bridge mode, even copied your configuration example and corrected Ip and port (80) but i still get this error.

Am I doing something wrong?

**Comment by grzegorz914** [comment]
Are you updated plugin to the latest version, if yes please enable debug mode in plugin Config advanced section and get the log

**Comment by grzegorz914** [comment]
@IIHiradorII any info?

**Comment by IIHiradorII** [comment]
> @IIHiradorII any info?
Today I'll check and let you know!

**Comment by IIHiradorII** [comment]
I've reinstalled everything first, the error is the same.
The model is an AVR-3311 which uses port 80 for remote controlling, no known network issues.
just to you knowledge, i've tried [THIS](https://github.com/stfnhmplr/homebridge-denon-marantz-avr#readme) plugin and, even if it has really limited functions, it worked at the first shot

log and Debug info:

`[13/02/2023, 13:06:41] [homebridge-denon-tv] Launched child bridge with PID 60516
[13/02/2023, 13:06:41] Registering platform 'homebridge-denon-tv.DenonTv'
[13/02/2023, 13:06:41] [homebridge-denon-tv] Loaded homebridge-denon-tv v3.24.0 child bridge successfully
[13/02/2023, 13:06:41] Loaded 0 cached accessories from cachedAccessories.0E996973D8FC.
[13/02/2023, 13:06:41] Homebridge v1.6.0 (HAP v0.11.0) (homebridge-denon-tv) is running on port 38440.
[13/02/2023, 13:06:41] [homebridge-denon-tv] Device: 192.168.1.109 DENON, debug: Info: undefined
[13/02/2023, 13:06:41] [homebridge-denon-tv] Device: 192.168.1.109 DENON, Info error: TypeError: Cannot read properties of undefined (reading 'BrandCode'), reconnect in 15s.`

**Comment by grzegorz914** [comment]
try this 3.24.1-beta.0 and get me log again

**Comment by grzegorz914** [comment]
Try this in your browser and get the output:
`http//ipaddress:port/goform/Deviceinfo.xml`
`http//ipaddress:port/goform/formMainZone_MainZoneXml.xml`
`http//ipaddress:60006/upnp/desc/aios_device/aios_device.xml`

**Comment by boffix** [comment]
Hey,
tried it in the browser, second line gives back:
Error 403: Forbidden
Access Forbidden

Also updated the plugin today, my log says
Device: 192.xxx.xxx.xx Denon, State error: TypeError: Cannot read properties of undefined (reading '0'), reconnect in 15s.

**Comment by grzegorz914** [comment]
what is output from other links?

**Comment by salemsayed** [comment]
Same error as @boffix, nothing worth noting when debug mode enabled. Will grab the output from the links you mentioned when I’m back home in a couple of hours

**Comment by boffix** [comment]
Hey output from the other links is here.
[Deviceinfo.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/10774658/Deviceinfo.txt)
[aios_device.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/10774659/aios_device.txt)

**Comment by grzegorz914** [comment]
@boffix  are You report any problem?
@salemsayed what same error as @boffix , @boffix do not report any error

**Comment by salemsayed** [comment]
I mean having this same message every 15s in the logs
Device: 192.xxx.xxx.xx Denon, State error: TypeError: Cannot read properties of undefined (reading '0'), reconnect in 15s

**Comment by grzegorz914** [comment]
@salemsayed its not the same error, please open new issue, enable debug mode in plugin settings advanced section and get the log please.

**Comment by grzegorz914** [comment]
@IIHiradorII  any output from other links?

also try `http://ipaddress:port/goform/formMainZone_MainZoneXmlStatusLite.xml`

**Comment by tobihoby** [comment]
since the update to version 4.0.0 I have the same problem. I'm back to version 3.25.21, the problem doesn't exist there.

25.2.2023, 06:11:45] [homebridge-denon-tv] Device: 192.168.0.7 AV Receiver, Info error: TypeError: Cannot read properties of undefined (reading '0'), reconnect in 15s.

**Comment by grzegorz914** [comment]
@tobihoby debug log please

**Comment by grzegorz914** [comment]
try 4.0.1-beta and let me know

**Comment by TheTeeDot** [comment]
Was getting the same error (TypeError: Cannot read properties of undefined (reading '0'), reconnect in 15s.) and 4.0.1-beta has resolved it for me.

**Comment by tobihoby** [comment]
4.0.1-beta has resolved it for me too

**Comment by IIHiradorII** [comment]
I'm terribly sorry for the late reply, 
I get no response from :
http://ipaddress:port/goform/Deviceinfo.xml
http://ipaddress:60006/upnp/desc/aios_device/aios_device.xml

From
http://ipaddress:port/goform/formMainZone_MainZoneXml.xml
i get this
[view-source_192.168.1.109_goform_formMainZone_MainZoneXml.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/10831292/view-source_192.168.1.109_goform_formMainZone_MainZoneXml.txt)

and from
http://ipaddress:port/goform/formMainZone_MainZoneXmlStatusLite.xml
i get this
[view-source_192.168.1.109_goform_formMainZone_MainZoneXmlStatusLite.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/10831297/view-source_192.168.1.109_goform_formMainZone_MainZoneXmlStatusLite.txt)

I've updated to the latest versione 4.01, i thing the problems rely on the deviceinfo.xml, maybe my specific DENON model (AVR-3311) do not store those informations that way

**Comment by grzegorz914** [comment]
@IIHiradorII 
i will Try to add support for Your AVR

**Comment by grzegorz914** [comment]
Please install 4.0.2-beta.11 enable Support for Old AVR and Debug mode in plugin settings advanced section and get the debug log.

**Comment by IIHiradorII** [comment]
`[25/02/2023, 14:42:13] [homebridge-denon-tv] Launched child bridge with PID 279219`
`[25/02/2023, 14:42:13] Registering platform 'homebridge-denon-tv.DenonTv' `
`[25/02/2023, 14:42:13] [homebridge-denon-tv] Loaded homebridge-denon-tv v4.0.2-beta.11 child bridge successfully`
`[25/02/2023, 14:42:13] Loaded 0 cached accessories from cachedAccessories.0E996973D8FC.`
`[25/02/2023, 14:42:13] Homebridge v1.6.0 (HAP v0.11.0) (homebridge-denon-tv) is running on port 38440.`
`[25/02/2023, 14:42:13] [homebridge-denon-tv] Device: 192.168.1.109 DENON, debug: Info: undefined`
`[25/02/2023, 14:42:13] [homebridge-denon-tv] Device: 192.168.1.109 DENON, Info error: TypeError: Cannot convert undefined or null to object, reconnect in 15s.`

**Comment by IIHiradorII** [comment]
If it can be helpful, i can provide to you a mirror of the 3311 webserver (even if i think is not 100% complete)

**Comment by grzegorz914** [comment]
My fault Try beta 12. the server access will be very helpfull

**Comment by IIHiradorII** [comment]
Updated, same error:

`[25/02/2023, 14:55:37] [homebridge-denon-tv] Launched child bridge with PID 279670`
`[25/02/2023, 14:55:37] Registering platform 'homebridge-denon-tv.DenonTv'`
`[25/02/2023, 14:55:38] [homebridge-denon-tv] Loaded homebridge-denon-tv v4.0.2-beta.12 child bridge successfully`
`[25/02/2023, 14:55:38] Loaded 0 cached accessories from cachedAccessories.0E996973D8FC.`
`[25/02/2023, 14:55:38] Homebridge v1.6.0 (HAP v0.11.0) (homebridge-denon-tv) is running on port 38440.`
`[25/02/2023, 14:55:38] [homebridge-denon-tv] Device: 192.168.1.109 DENON, debug: Info: undefined`
`[25/02/2023, 14:55:38] [homebridge-denon-tv] Device: 192.168.1.109 DENON, Info error: TypeError: Cannot convert undefined or null to object, reconnect in 15s.`
Here you have the mirror:
[DENON-AVR3311.zip](https://github.com/grzegorz914/homebridge-denon-tv/files/10831466/DENON-AVR3311.zip)

**Comment by grzegorz914** [comment]
Are you sure you have correct IP and Port

**Comment by grzegorz914** [comment]
Try 13 please

**Comment by IIHiradorII** [comment]
I'm using ip 192.168.1.109 (My denon ip) and port 80 (the one where the webserver responds me as you can see with the screenshot)
![Screenshot](https://user-images.githubusercontent.com/63920290/221364159-5ac89f95-d04f-4b84-930b-fe8fe4c73dd1.png)

**Comment by IIHiradorII** [comment]
Updated Logs:

`[25/02/2023, 15:04:27] [homebridge-denon-tv] Launched child bridge with PID 280458`
`[25/02/2023, 15:04:27] Registering platform 'homebridge-denon-tv.DenonTv'`
`[25/02/2023, 15:04:28] [homebridge-denon-tv] Loaded homebridge-denon-tv v4.0.2-beta.13 child bridge successfully`
`[25/02/2023, 15:04:28] Loaded 0 cached accessories from cachedAccessories.0E996973D8FC.`
`[25/02/2023, 15:04:28] Homebridge v1.6.0 (HAP v0.11.0) (homebridge-denon-tv) is running on port 38440.`
`[25/02/2023, 15:04:28] [homebridge-denon-tv] Device: 192.168.1.109 DENON, Info error: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ClientRequest'
    |     property 'socket' -> object with constructor 'Socket'
    --- property '_httpMessage' closes the circle, reconnect in 15s.`

``

**Comment by grzegorz914** [comment]
14 ready

**Comment by IIHiradorII** [comment]
updated beta 14 logs:

`[25/02/2023, 15:11:14] [homebridge-denon-tv] Launched child bridge with PID 280756
[25/02/2023, 15:11:14] Registering platform 'homebridge-denon-tv.DenonTv'
[25/02/2023, 15:11:14] [homebridge-denon-tv] Loaded homebridge-denon-tv v4.0.2-beta.14 child bridge successfully
[25/02/2023, 15:11:14] Loaded 0 cached accessories from cachedAccessories.0E996973D8FC.
[25/02/2023, 15:11:14] Homebridge v1.6.0 (HAP v0.11.0) (homebridge-denon-tv) is running on port 38440.
[25/02/2023, 15:11:14] [homebridge-denon-tv] Device: 192.168.1.109 DENON, debug: Info: "<?xml version=\"1.0\" encoding=\"utf-8\" ?>\n<item>\n<Power><value>ON</value></Power>\n<ZonePower><value>ON</value></ZonePower>\n<InputFuncList>\n<value>SOURCE</value>\n<value>TUNER</value>\n<value>PHONO</value>\n<value>CD</value>\n<value>DVD</value>\n<value>BD</value>\n<value>TV</value>\n<value>SAT/CBL</value>\n<value>GAME</value>\n<value>DOCK</value>\n<value>DVR</value>\n<value>V.AUX</value>\n<value>NET/USB</value>\n<value>SIRIUS</value>\n<value>HDRADIO</value>\n</InputFuncList>\n<RenameSource>\n<value></value>\n<value>TUNER   </value>\n<value>PHONO   </value>\n<value>        </value>\n<value>DVD     </value>\n<value>APPLE TV</value>\n<value>TV      </value>\n<value>COMPUTER</value>\n<value>PS4     </value>\n<value>DOCK    </value>\n<value>DVR     </value>\n<value>V.AUX   </value>\n<value>NET/USB </value>\n<value></value>\n<value></value>\n</RenameSource>\n<RenameZone><value>MAIN ZONE \r</value></RenameZone>\n<SourceDelete>\n<value>DEL</value>\n<value>DEL</value>\n<value>DEL</value>\n<value>USE</value>\n<value>DEL</value>\n<value>USE</value>\n<value>DEL</value>\n<value>USE</value>\n<value>USE</value>\n<value>DEL</value>\n<value>USE</value>\n<value>DEL</value>\n<value>USE</value>\n<value>DEL</value>\n<value>DEL</value>\n</SourceDelete>\n<TopMenuLink><value>OFF</value></TopMenuLink>\n<ModelId><value>1</value></ModelId>\n<SalesArea><value>1</value></SalesArea>\n<InputFuncSelect><value>Media Server</value></InputFuncSelect>\n<NetFuncSelect><value>SERVER</value></NetFuncSelect>\n<InputFuncSelectMain><value>NET/USB</value></InputFuncSelectMain>\n<VolumeDisplay><value>Absolute</value></VolumeDisplay>\n<MasterVolume><value>-25.5</value></MasterVolume>\n<Mute><value>off</value></Mute>\n<RemoteMaintenance><value>OFF</value></RemoteMaintenance>\n<GameSourceDisplay><value>TRUE</value></GameSourceDisplay>\n<LastfmDisplay><value>TRUE</value></LastfmDisplay>\n<SubwooferDisplay><value>FALSE</value></SubwooferDisplay>\n</item>\n"
[25/02/2023, 15:11:14] [homebridge-denon-tv] Device: 192.168.1.109 DENON, debug: Info1: {
  "item": {
    "Power": [
      {
        "value": [
          "ON"
        ]
      }
    ],
    "ZonePower": [
      {
        "value": [
          "ON"
        ]
      }
    ],
    "InputFuncList": [
      {
        "value": [
          "SOURCE",
          "TUNER",
          "PHONO",
          "CD",
          "DVD",
          "BD",
          "TV",
          "SAT/CBL",
          "GAME",
          "DOCK",
          "DVR",
          "V.AUX",
          "NET/USB",
          "SIRIUS",
          "HDRADIO"
        ]
      }
    ],
    "RenameSource": [
      {
        "value": [
          "",
          "TUNER   ",
          "PHONO   ",
          "        ",
          "DVD     ",
          "APPLE TV",
          "TV      ",
          "COMPUTER",
          "PS4     ",
          "DOCK    ",
          "DVR     ",
          "V.AUX   ",
          "NET/USB ",
          "",
          ""
        ]
      }
    ],
    "RenameZone": [
      {
        "value": [
          "MAIN ZONE \r"
        ]
      }
    ],
    "SourceDelete": [
      {
        "value": [
          "DEL",
          "DEL",
          "DEL",
          "USE",
          "DEL",
          "USE",
          "DEL",
          "USE",
          "USE",
          "DEL",
          "USE",
          "DEL",
          "USE",
          "DEL",
          "DEL"
        ]
      }
    ],
    "TopMenuLink": [
      {
        "value": [
          "OFF"
        ]
      }
    ],
    "ModelId": [
      {
        "value": [
          "1"
        ]
      }
    ],
    "SalesArea": [
      {
        "value": [
          "1"
        ]
      }
    ],
    "InputFuncSelect": [
      {
        "value": [
          "Media Server"
        ]
      }
    ],
    "NetFuncSelect": [
      {
        "value": [
          "SERVER"
        ]
      }
    ],
    "InputFuncSelectMain": [
      {
        "value": [
          "NET/USB"
        ]
      }
    ],
    "VolumeDisplay": [
      {
        "value": [
          "Absolute"
        ]
      }
    ],
    "MasterVolume": [
      {
        "value": [
          "-25.5"
        ]
      }
    ],
    "Mute": [
      {
        "value": [
          "off"
        ]
      }
    ],
    "RemoteMaintenance": [
      {
        "value": [
          "OFF"
        ]
      }
    ],
    "GameSourceDisplay": [
      {
        "value": [
          "TRUE"
        ]
      }
    ],
    "LastfmDisplay": [
      {
        "value": [
          "TRUE"
        ]
      }
    ],
    "SubwooferDisplay": [
      {
        "value": [
          "FALSE"
        ]
      }
    ]
  }
}
[25/02/2023, 15:11:14] [homebridge-denon-tv] Device: 192.168.1.109 DENON, Info error: ReferenceError: devInfo is not defined, reconnect in 15s.`

**Comment by grzegorz914** [comment]
Install beta 15 and again get the log

**Comment by grzegorz914** [comment]
nice, try 18

**Comment by IIHiradorII** [comment]
We are quite there!!

![DENON](https://user-images.githubusercontent.com/63920290/221369921-9f3619ad-f9ad-4d05-b840-db41dd852e98.png)

Just one problem: added a new input but is not displaying in the homebridge accessoeries list 
Then added the bridge to homekit but no accessories are displayed at all

[homebridge.log.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/10831807/homebridge.log.txt)

**Comment by grzegorz914** [comment]
The inputs can be loaded from AVR direct go to the plugin config, section Inputs and enable load inputs from device then all inputs and its named will be loaded automatically..
Homebridge accesories do not support Television accessory so the inputs not be displayed here only in Home.app ass inputs list. If you want inputs in Homebridge displayed need to create Buttons.  Beta 20 ready, all log please.

**Comment by grzegorz914** [comment]
You need add the accessory itself not the bridge to the Homa.app

**Comment by IIHiradorII** [comment]
Yes i thougt it was me miss configuring something, i'm going to play it around bit and let you know first
Here's the log, i think you have mistaken the version (is beta 28 not 20

[homebridge.log (2).txt](https://github.com/grzegorz914/homebridge-denon-tv/files/10831945/homebridge.log.2.txt)

**Comment by grzegorz914** [comment]
yes actually beta 28, test and let me know if all passed

**Comment by grzegorz914** [comment]
beta 29 fixed load renamed inputs names from device

**Comment by IIHiradorII** [comment]
Installed, everything seems to be working fine exept that there is no DVR in Reference Input, 
in addition, i've also tried to change surce via Siri creating specific buttons like ZM input Game (my actual ps4 channel) or at the same way with quick select (settin it up first on denon) with no like, i see that the buttons work for Z2 though

**Comment by grzegorz914** [comment]
Im pushed beta 31, added DVR and V.AUX inputs.
Siri is irrelevant at this time, please write what is not working now. We need fixed the issues step by step because I don't have possibility to test it in my environment.

**Comment by IIHiradorII** [comment]
Okay DVR is now working but it is ignoring the custom name set by me

**Comment by grzegorz914** [comment]
Where the name is ignored In Buttons or wheel ?

**Comment by IIHiradorII** [comment]
it's ignored in the denon input selector, the wheel i think

**Comment by grzegorz914** [comment]
you can change it in Tile settings

**Comment by grzegorz914** [comment]
<img width="595" alt="Zrzut ekranu 2023-02-25 o 23 10 27" src="https://user-images.githubusercontent.com/28867813/221381790-682c7700-41a1-45ab-859c-b534223df98c.png">

**Comment by IIHiradorII** [comment]
Okay great, i'll continue testing and let you know

**Comment by grzegorz914** [comment]
@IIHiradorII any info?

**Comment by IIHiradorII** [comment]
> @IIHiradorII any info?

Still testing, want to make you a full debugging list of what is working or not

**Comment by IIHiradorII** [comment]
[Debug.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/10851578/Debug.txt)
This is a first Debug, i will continue with it as far as we figure out this problems

**Comment by grzegorz914** [comment]
@IIHiradorII  what is your AVR model which have 4 Zones?

**Comment by grzegorz914** [comment]
try beta.59

**Comment by IIHiradorII** [comment]
Installed beta.59
Button still not working, i've set them up like you can see in the screenshot:
If i switch to another source i expect this button to set the DENON to GAME source

![image](https://user-images.githubusercontent.com/63920290/221950935-b84104ea-ff1b-4fdb-8248-887c4f2b6648.png)

**Comment by grzegorz914** [comment]
Sorry but No any Marantz and Denon receiver have 4 Zones

**Comment by IIHiradorII** [comment]
> 



> Sorry but No any Marantz and Denon receiver have 4 Zones

See [This](https://www.google.com/search?q=denon+rc1148&sxsrf=AJOqlzWgQlRqqpis7NQm3iAfPioA-PaGcw:1677611069943&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiTqpSf9Lj9AhX6Q_EDHTCJCN0Q_AUoAXoECAEQAw&biw=1920&bih=961&dpr=1#imgrc=lrZfNhLyrHZ2BM), maybe is fake i don't know, i have to remote btw

**Comment by grzegorz914** [comment]
3311 have only Main Zone Zone 2 und 3

**Comment by IIHiradorII** [comment]
> 3311 have only Main Zone Zone 2 und 3

yes yes i know, i've sent you the remote model only for information

**Comment by grzegorz914** [comment]
Can you power on and off AVR with plugin?

**Comment by IIHiradorII** [comment]
I think something has broken down the plugin, i was trying to change the button behaviour to turn off the main zone but anytime i tried to save the config was still keeping the old settings.
I've reinstalled the plugin now i can't fill any field, nothing remains even without rebooting but simply by saving and repoening the setting, the inputs section is also gone

**Comment by grzegorz914** [comment]
Here is all OK, your environment must be broken.

**Comment by IIHiradorII** [comment]
I'm sorry to tell you, i don't think is my enviroment: 
I've deleted everything, installed denon 4.0,0, edit the config and it was keeping the info and writing them correctly, updated to 4.0.1 and the same was happening (added a button, everything ok), installed beta.62, i thick the support for old denon, add another input, saved and nothing remained in the settings page, nothing is written to the configuration.
Again, i think something went wrong from version 58/59 to 62

**Comment by IIHiradorII** [comment]
yes yes i'm using the gui, i'm just double checking if it is writting the modifications to the config

**Comment by grzegorz914** [comment]
Already checked and all is saved correct in config 58/59 62 and 64 now.

**Comment by IIHiradorII** [comment]
If you agree, i would like to speed up everything and continue this conversation without chatting on github, don't know if you have a discord channel or something else where we can talk and cooperate having a live feedback

**Comment by grzegorz914** [comment]
If the power on off working then the inputs and other functions must be working too. If not post debug log during presentation input button

**Comment by IIHiradorII** [comment]
![image](https://user-images.githubusercontent.com/63920290/222158957-6382ee20-be36-492b-bbdb-ed714d3f079f.png)

this is the button i'm pressing (i've seen that now all zones are cropped)

the debug gives me this

[01/03/2023, 14:50:43] [homebridge-denon-tv] Device: 192.168.1.109 DENON, set Button Name: PS4, Reference: GAME
[01/03/2023, 14:50:45] [homebridge-denon-tv] Device: 192.168.1.109 DENON, Power: ON
[01/03/2023, 14:50:45] [homebridge-denon-tv] Device: 192.168.1.109 DENON, Input Name: APPLE TV, Reference: BD
[01/03/2023, 14:50:45] [homebridge-denon-tv] Device: 192.168.1.109 DENON, Mute: OFF
[01/03/2023, 14:50:45] [homebridge-denon-tv] Device: 192.168.1.109 DENON, Volume: -29
[01/03/2023, 14:50:45] [homebridge-denon-tv] Device: 192.168.1.109 DENON, debug: State: {
  "Power": [
    {
      "value": [
        "ON"
      ]
    }
  ],
  "InputFuncSelect": [
    {
      "value": [
        "BD"
      ]
    }
  ],
  "MasterVolume": [
    {
      "value": [
        "-29.5"
      ]
    }
  ],
  "Mute": [
    {
      "value": [
        "off"
      ]
    }
  ]
}

Nothing happens aftr button prassing, source is not changed

**Comment by grzegorz914** [comment]
install 66 and get also debug

**Comment by IIHiradorII** [comment]
Installed beta.66
Still nothing happens:
`01/03/2023, 21:55:43] [homebridge-denon-tv] Device: 192.168.1.109 DENON, set Button Name: PS4, Reference: GAME
[01/03/2023, 21:55:46] [homebridge-denon-tv] Device: 192.168.1.109 DENON, debug: State: {
  "Power": [
    {
      "value": [
        "ON"
      ]
    }
  ],
  "InputFuncSelect": [
    {
      "value": [
        "NET/USB"
      ]
    }
  ],
  "MasterVolume": [
    {
      "value": [
        "-44.5"
      ]
    }
  ],
  "Mute": [
    {
      "value": [
        "off"
      ]
    }
  ]
}`

**Comment by grzegorz914** [comment]
its nothing more in the log?

**Comment by grzegorz914** [comment]
strange, try 67

**Comment by IIHiradorII** [comment]
Nothing again, you confirm that if I press this button the source should change from DVR (for example) to the one that I've set right?

**Comment by grzegorz914** [comment]
ok try 68 and log please

**Comment by IIHiradorII** [comment]
Same issue:
[homebridge.log.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/10865847/homebridge.log.txt)

**Comment by grzegorz914** [comment]
again 69

**Comment by IIHiradorII** [comment]
beta.74 same issue:
[homebridge.log.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/10866205/homebridge.log.txt)

**Comment by grzegorz914** [comment]
ok, 77 ready

**Comment by IIHiradorII** [comment]
mmh something went wrong:

[homebridge.log.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/10866290/homebridge.log.txt)

**Comment by grzegorz914** [comment]
sorry, 78 fixed

**Comment by IIHiradorII** [comment]
no worries, installed beta.78 still no luck:

[homebridge.log.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/10866317/homebridge.log.txt)

**Comment by grzegorz914** [comment]
latest test today 79

**Comment by IIHiradorII** [comment]
Still no luck beta.79:
[homebridge.log.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/10866355/homebridge.log.txt)
no worries, let's continue tomorrow. 
I'll be availeble all day, just write me here and we will continue. Have a nice rest!

**Comment by grzegorz914** [comment]
try 80 and check PS4 button

**Comment by grzegorz914** [comment]
32 ready to test, please configure your buttons again

**Comment by IIHiradorII** [comment]
Installed beta.86:

IT WORKS!! 

i'll have some tests and write you back!

**Comment by grzegorz914** [comment]
Nice, also debug log please

**Comment by IIHiradorII** [comment]
Configured other buttons also as switch and they are working,
i have to press more then once on both outlet or switches but i think this is a normal behaviour on the homebridge server, havent tested on homekit:
 
[homebridge.log.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/10871221/homebridge.log.txt)

**Comment by grzegorz914** [comment]
what you mean exactly about this:
`i have to press more then once on both outlet or switches but i think this is a normal behaviour`

**Comment by IIHiradorII** [comment]
> if you mean to switch execute need to press more times as once try beta 88

Yes i mean that i need to press twice to the buttons to activate them
updated to beta.88 still need to press twice

**Comment by grzegorz914** [comment]
then try 89

**Comment by IIHiradorII** [comment]
still have to doubleclick beta.89:
[homebridge.log.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/10871591/homebridge.log.txt)

**Comment by grzegorz914** [comment]
90 ready

**Comment by IIHiradorII** [comment]
tried, it's strange beacuse it works at times:
[homebridge.log.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/10872064/homebridge.log.txt)

**Comment by IIHiradorII** [comment]
i wanted to try with homekit also but i can't find any device exept from the child bridge

**Comment by grzegorz914** [comment]
Clear homebridge casche

**Comment by IIHiradorII** [comment]
Cleared, child bridge availeble only

**Comment by grzegorz914** [comment]
![Uploading IMG_0805.jpeg…]()

**Comment by IIHiradorII** [comment]
> ![IMG_0805](https://user-images.githubusercontent.com/28867813/222453161-d594a3e9-b0ad-4883-87c3-da1139f3f3d7.jpeg)

Yes is what i've made to clear homebridge cache

**Comment by grzegorz914** [comment]
Are You trying this https://github.com/grzegorz914/homebridge-denon-tv/wiki#troubleshooting

**Comment by IIHiradorII** [comment]
> Are You trying this https://github.com/grzegorz914/homebridge-denon-tv/wiki#troubleshooting

Yes, rebooting homebridge right now. I had a lot of files to delete in there

**Comment by IIHiradorII** [comment]
Added denon to homekit, in here all buttons works flawlessly

**Comment by grzegorz914** [comment]
nice, then can be related now

**Comment by grzegorz914** [comment]
thanks for testing and patience, 4.1.0 released

**Comment by IIHiradorII** [comment]
no worries, thank you for your work.
Is there any way i can donate to you?
