### ISSUE TITLE
Volume at 100% each time I open the AVR card in Home

### ISSUE THREAD

**Issue by Seexelas** [grzegorz914/homebridge-denon-tv#167]
Hi, 

Since one of the last updates of the plugin, (I had also one on the AVR). My volume card in Home is always at 100%, even if it's not the current level of my Denon AVR. 

I can set the volume I want, it changes on the AVR, when I close the volume card and go back to it, it is reseted to 100%.

I have attached a video showing this. 

https://www.dropbox.com/s/nr16vu27o0fzzj7/HB%20-%20Denon.mp4?dl=0

------------------------------------------------------------------------------------

HB Version : v.1.6.0
OS | Ubuntu Focal Fossa (20.04.5 LTS)
Node.js Version	[v18.12.0]
Plugin version : homebridge-denon-tv v3.21.9

AVR Denon : X-4500H

------------------------------------------------------------------------------------

Many thanks for the help.

**Comment by kleingunni** [comment]
same issue.
AVR-X1500H
