### ISSUE TITLE
amp-assign speaker configuration?

### ISSUE THREAD

**Issue by vincent0794** [grzegorz914/homebridge-denon-tv#17]
Very useful plugin - thank you. Have begun using it (with a Denon X3600H).

I'm interested in trying to contribute some work to enable the plugin to adjust the speaker layout on the fly.  This can be done through the amp-assign settings in the receiver's web interface (see the image attached), where it is helpful to be able to quickly swap between some of these settings (in my case "9.1ch" vs "7.1ch + ZONE2").  While I'm an experienced programmer, I'm new to Homebridge and javascript.  Any advice on how to get started with experimenting with additions to this plugin?

<img width="1143" alt="Speakers" src="https://user-images.githubusercontent.com/64140023/79977379-19246d80-8496-11ea-8469-02197c03b003.png">

**Comment by vincent0794** [comment]
As an FYI - using a simple http-switch I've managed to get this to work very nicely...

 {
            "accessory": "HTTP-SWITCH",
            "name": "AddZone2",
            "switchType": "stateful",
            "debug": false,
            "onUrl": "https://192.168.1.93:10443/ajax/speakers/set_config?type=2&data=%3CAmpAssign%3E%3CAssignMode%3E2%3C%2FAssignMode%3E%3C%2FAmpAssign%3E&_=1587642388217",
            "offUrl": "https://192.168.1.93:10443/ajax/speakers/set_config?type=2&data=%3CAmpAssign%3E%3CAssignMode%3E1%3C%2FAssignMode%3E%3C%2FAmpAssign%3E&_=1587642388217",
            "statusUrl": "https://192.168.1.93:10443/ajax/speakers/get_config?type=2",
            "statusPattern": ".*<AssignMode>2</AssignMode>.*"
        }

**Comment by grzegorz914** [comment]
Amp assign is one time config, no need to ad it.

**Comment by vincent0794** [comment]
Just to be clear, the way I use this, it is not a one-time config. The amp (as shown in the screenshot) has a 9ch amplifier. I have a 7.1.2 surround setup (9 channels) AND a 2-speaker second zone. So I use this switch to swap between playing only surround sound for movies (and therefore second zone being out of use) vs being able to play in both zones simultaneously (when the ".2" height speakers in zone 1 are out of use).

I understand this is not a common use-case, so please do feel free to close!
