### ISSUE TITLE
Input selector jumps to top

### ISSUE THREAD

**Issue by badgertastic** [grzegorz914/homebridge-denon-tv#170]
Hi. Irrespective of input chosen, the display in the HomeKit input selector button always jumps to top choice. Input is selected correctly, but choice one is always shown. On 3.23.5.  Noticed since having to reset HomeKit and create accessory from scratch.

**Comment by grzegorz914** [comment]
Check please 3.23.6-beta.0 and let me know.

**Comment by badgertastic** [comment]
Same issue

**Comment by badgertastic** [comment]
Actually, left it slightly longer. Looks to be working.

**Comment by grzegorz914** [comment]
This problem was with load inputs from device?

**Comment by badgertastic** [comment]
Thank for quick fix
