### ISSUE TITLE
Buttons disappeared, now everything is gone

### ISSUE THREAD

**Issue by SawkeeReemo** [grzegorz914/homebridge-denon-tv#171]
I’m not entirely sure how to even describe this, so please bear with me.

I used to have this set up and working, but I was very confused on how this all works since i wasn’t able to find clear definitions of what things did. So I did a lot of trial an error. 

About a week ago, my input buttons would no longer show up in HomeKit. I’ve spent an hour or so tonight trying to get things back, but gave up and finally uninstalled this plugin all together. I figured I would start fresh now that I understand it better. 

So I copied the JSON config, uninstalled the plugin, then reinstalled. Then pasted my JSON config back in, and turned on child bridge. When I scan the QR code for the child bridge into HomeKit, it connects, but it no longer shows any accessories attached to it. And none of my buttons or anything show up anymore. 

Any idea how to fix this? I couldn’t find any discussion tab here or any other help contact of any kind, so please point in that direction if needs be. I have no idea what to do at this point. (I even tried clearing the cache in HoneBridge and changing the MAC address for DenonTV… nothing has worked.)

Thanks!

**Comment by SawkeeReemo** [comment]
UPDATE: I just reinstalled again, pasted the JSON back over, etc, NS now I got my inputs back. But the problem of “Extra Input Tile Type” persists. Any idea how to get those back?

I have an input called “Music” and I set the extra tile type to outlet, but it is nowhere to be found.

**Comment by grzegorz914** [comment]
Can you post your config.json here?

**Comment by SawkeeReemo** [comment]
ah, ok. I'll give the beta a try. here is my JSON. And thanks for responding! If there is a better way for me to get support please let me know, i don't want to clutter your Issues lost.

{
    "devices": [
        {
            "name": "AVR Main",
            "host": "192.168.1.71",
            "port": 8080,
            "zoneControl": 0,
            "volumeControl": 1,
            "masterPower": false,
            "masterVolume": false,
            "masterMute": false,
            "sensorPower": false,
            "sensorVolume": false,
            "sensorMute": false,
            "sensorInput": false,
            "infoButtonCommand": "MNINF",
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "enableDebugMode": false,
            "getInputsFromDevice": false,
            "inputs": [
                {
                    "name": "Music",
                    "reference": "NET",
                    "mode": "SI",
                    "displayType": 0
                },
                {
                    "name": "Record Player",
                    "reference": "CD",
                    "mode": "SI",
                    "displayType": 0
                },
                {
                    "name": "AppleTV",
                    "reference": "MPLAY",
                    "mode": "SI",
                    "displayType": 0
                }
            ],
            "buttonsMainZone": [
                {
                    "name": "LFC On",
                    "reference": "PSLFC ON",
                    "displayType": 0
                },
                {
                    "name": "LFC Off",
                    "reference": "PSLFC OFF",
                    "displayType": 0
                },
                {
                    "name": "DynVol Day",
                    "reference": "PSDYNVOL LIT",
                    "displayType": 0
                },
                {
                    "name": "DynVol Night",
                    "reference": "PSDYNVOL MED",
                    "displayType": 0
                },
                {
                    "name": "DynVol Heavy",
                    "reference": "PSDYNVOL HEV",
                    "displayType": 0
                },
                {
                    "name": "DynVol Off",
                    "reference": "PSDYNVOL OFF",
                    "displayType": 0
                }
            ],
            "refreshInterval": 5,
            "enableMqtt": false,
            "mqttAuth": false,
            "mqttDebug": false
        },
        {
            "name": "Record AirPlay",
            "host": "192.168.1.71",
            "port": 8080,
            "zoneControl": 1,
            "masterPower": false,
            "masterVolume": false,
            "masterMute": false,
            "sensorPower": false,
            "sensorVolume": false,
            "sensorMute": false,
            "sensorInput": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "enableDebugMode": false,
            "getInputsFromDevice": false,
            "inputs": [
                {
                    "name": "Turntable",
                    "reference": "CD",
                    "mode": "SI",
                    "displayType": 0
                },
                {
                    "name": "AppleTV",
                    "reference": "CBL/SAT",
                    "mode": "SI",
                    "displayType": -1
                }
            ],
            "refreshInterval": 5,
            "enableMqtt": false,
            "mqttAuth": false,
            "mqttDebug": false
        },
        {
            "name": "Sound Mode",
            "host": "192.168.1.71",
            "port": 8080,
            "zoneControl": 3,
            "masterPower": false,
            "masterVolume": false,
            "masterMute": false,
            "sensorPower": false,
            "sensorVolume": false,
            "sensorMute": false,
            "sensorInput": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "enableDebugMode": false,
            "getInputsFromDevice": false,
            "surrounds": [
                {
                    "name": "Multi-Stereo",
                    "reference": "MCH STEREO",
                    "displayType": -1
                },
                {
                    "name": "Stereo",
                    "reference": "STEREO",
                    "displayType": -1
                },
                {
                    "name": "DTS",
                    "reference": "DTS SURROUND",
                    "displayType": -1
                },
                {
                    "name": "Dolby Digital",
                    "reference": "DOLBY DIGITAL",
                    "displayType": -1
                },
                {
                    "name": "AUTO",
                    "reference": "AUTO",
                    "displayType": -1
                },
                {
                    "name": "Direct",
                    "reference": "DIRECT"
                },
                {
                    "name": "Pure Direct",
                    "reference": "PURE DIRECT",
                    "displayType": -1
                }
            ],
            "refreshInterval": 5,
            "enableMqtt": false,
            "mqttAuth": false,
            "mqttDebug": false
        }
    ],
    "_bridge": {
        "username": "0E:AD:2F:83:8B:AE",
        "port": 40617
    },
    "platform": "DenonTv"
}

**Comment by SawkeeReemo** [comment]
Installed the beta, and now the input tiles are there! Thank you!

**Comment by grzegorz914** [comment]
I see Apple TV input extra tile is set to -1 disabled,  and all surrounds extra buttons too. Best way to configure plugin is use GUI Configurator not the json example.

**Comment by SawkeeReemo** [comment]
I actually did use the GUI. I haven’t altered anything in the JSON, I just went there to see if I could tell what the problem is.
