### ISSUE TITLE
Volume slider unavailable since last update v3.24.0

### ISSUE THREAD

**Issue by Seexelas** [grzegorz914/homebridge-denon-tv#172]
Hi, 

Since the last update, the volune slider (lightbulb mode) doesn't work anymore. If I set it to Fan, it's working. 

Here is my config.json :

"devices": [
                {
                    "name": "Denon X4500H",
                    "host": "192.168.1.11",
                    "port": 8080,
                    "zoneControl": 0,
                    "volumeControl": 0,
                    "masterPower": false,
                    "masterVolume": false,
                    "masterMute": false,
                    "sensorPower": true,
                    "sensorVolume": true,
                    "sensorMute": true,
                    "sensorInput": true,
                    "infoButtonCommand": "MNMEN ON",
                    "disableLogInfo": false,
                    "disableLogDeviceInfo": false,
                    "disableLogConnectError": false,
                    "enableDebugMode": false,
                    "getInputsFromDevice": true,
                    "inputs": [
                        {
                            "name": "Apple TV",
                            "reference": "MPLAY",
                            "mode": "SI"
                        },
                        {
                            "name": "4K Bluray",
                            "reference": "BD",
                            "mode": "SI"
                        },
                        {
                            "name": "PS5",
                            "reference": "CBL/SAT",
                            "mode": "SI"
                        },
                        {
                            "name": "Xbox S. X.",
                            "reference": "GAME",
                            "mode": "SI"
                        },
                        {
                            "name": "Zappiti NEO",
                            "reference": "DVD",
                            "mode": "SI"
                        },
                        {
                            "name": "N. Switch",
                            "reference": "AUX2",
                            "mode": "SI"
                        },
                        {
                            "name": "Mister FPGA",
                            "reference": "AUX1",
                            "mode": "SI"
                        },
                        {
                            "name": "Analogue",
                            "reference": "CD",
                            "mode": "SI"
                        },
                        {
                            "name": "ARC Tv",
                            "reference": "TV",
                            "mode": "SI"
                        }
                    ],
                    "refreshInterval": 5,
                    "enableMqtt": false,
                    "mqttAuth": false,
                    "mqttDebug": false
                }
            ],
            "platform": "DenonTv"
        },

HB Config : 

OS | Ubuntu Focal Fossa (20.04.5 LTS)
Node.js Version	[v18.13.0]
HB : v1.6.0

Many thanks for the help,

**Comment by grzegorz914** [comment]
Fan is now 0 and Lightbulb 1, see in readme

**Comment by Seexelas** [comment]
I put the last update you provided, but nothing changed despite successfull update.

I thought of uninstalling the plugin and start fresh but : 

USER: root
DIR: /var/lib/homebridge
CMD: npm uninstall --save homebridge-denon-tv

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /homebridge/node_modules/homebridge-denon-tv
npm ERR! dest /homebridge/node_modules/.homebridge-denon-tv-WAX8R0VA
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/homebridge/node_modules/homebridge-denon-tv' -> '/homebridge/node_modules/.homebridge-denon-tv-WAX8R0VA'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2023-02-13T16_13_22_005Z-debug-0.log

Operation failed. Please review log for details.

I tried rebooting the whole server, but it's not changing anything.

Thanks for the help,

**Comment by grzegorz914** [comment]
Here is npm error nothing with plugin, check your local environment. Are you using Config Gui X to install and uninstall or console?

**Comment by Seexelas** [comment]
Yes, I use the Config Gui X.

I deleted the folders of the plugin, and unpaired the Denon, I will retry and let you know.

**Comment by Seexelas** [comment]
So, I got rid of my Homebridge vm and started over. 

With a fresh install and this config : 

"devices": [
                {
                    "name": "Denon AVR-X4500H",
                    "host": "192.168.1.11",
                    "port": 8080,
                    "zoneControl": 0,
                    "getInputsFromDevice": true,
                    "sensorPower": true,
                    "sensorVolume": true,
                    "sensorMute": true,
                    "sensorInput": true,
                    "enableDebugMode": false,
                    "disableLogInfo": false,
                    "disableLogDeviceInfo": false,
                    "disableLogConnectError": false,
                    "masterPower": false,
                    "masterVolume": false,
                    "masterMute": false,
                    "infoButtonCommand": "MNMEN ON",
                    "volumeControl": 0,
                    "refreshInterval": 5,
                    "enableMqtt": false,
                    "mqttDebug": false,
                    "mqttAuth": false
                }
            ],
            "platform": "DenonTv"
        }

I still got nothing, when I set volume control to 1, the Fan appears, when I switch back to 0, nothing.

Thanks for the help

**Comment by grzegorz914** [comment]
fixed

**Comment by Seexelas** [comment]
Great, it's working again :) many thanks
