### ISSUE TITLE
Occupancy/Motion Sensor not available anymore

### ISSUE THREAD

**Issue by elministerr** [grzegorz914/homebridge-denon-tv#173]
My denon tv plugin stopped working since last update. I found the problem:

"inputs": [
                {
                    "name": "AirPlay",
                    "reference": "NET",
                    "mode": "SI",
                    "displayType": 3
                },
                {
                    "name": "MOVIE",
                    "reference": "TV",
                    "mode": "SI",
                    "displayType": 3
}

The displayType was the "Motion Sensor" I think. In the last update only Switch/Outlet are possible. Is there a reason for this ?

**Comment by grzegorz914** [comment]
Yes, all described in readme, -1 none, 0 outlet, 1 switch
