### ISSUE TITLE
State error: TypeError: Cannot read properties of undefined (reading '0'), reconnect in 15s.

### ISSUE THREAD

**Issue by tjq100** [grzegorz914/homebridge-denon-tv#175]
I’m having same issue as @salemsayed who posted in the thread 166 re the BrandingCode error

error is: State error: TypeError: Cannot read properties of undefined (reading '0'), reconnect in 15s.

I’m using the Denon AVR X1400H and I believe everything worked until I ran update this morning.  

I also have an x3700H that still works fine.  

Logs are attached.  

Thanks,
TQ

[homebridge.log.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/10774826/homebridge.log.txt)

**Comment by mtressl** [comment]
Watching. Same issue.

**Comment by grzegorz914** [comment]
fixed

**Comment by tjq100** [comment]
Thanks!
