### ISSUE TITLE
Volume bulb is added in each zone, despite volume set to false

### ISSUE THREAD

**Issue by badgertastic** [grzegorz914/homebridge-denon-tv#176]
Volume bulb is added in each zone, despite zone volume (and master volume) set to false

3.25.10

**Comment by grzegorz914** [comment]
get config please

**Comment by badgertastic** [comment]
"devices": [
        {
            "name": "Theatre",
            "host": "10.0.20.63",
            "port": 8080,
            "zoneControl": 0,
            "getInputsFromDevice": true,
            "sensorPower": false,
            "sensorVolume": false,
            "sensorMute": false,
            "sensorInput": false,
            "enableDebugMode": false,
            "disableLogInfo": true,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "masterPower": false,
            "masterVolume": false,
            "masterMute": false,
            "volumeControl": 0,
            "refreshInterval": 5,
            "enableMqtt": false,
            "mqttDebug": false,
            "mqttAuth": false
        },
        {
            "name": "Bathroom",
            "host": "10.0.20.63",
            "port": 8080,
            "zoneControl": 2,
            "getInputsFromDevice": false,
            "inputs": [
                {
                    "name": "BBC Radio 1",
                    "reference": "SMART1",
                    "mode": "MS"
                },
                {
                    "name": "BBC Radio 2",
                    "reference": "SMART2",
                    "mode": "MS"
                },
                {
                    "name": "BBC Radio 6",
                    "reference": "SMART3",
                    "mode": "MS"
                },
                {
                    "name": "BBC 3CR",
                    "reference": "SMART4",
                    "mode": "MS"
                }
            ],
            "sensorPower": false,
            "sensorVolume": false,
            "sensorMute": false,
            "sensorInput": false,
            "enableDebugMode": false,
            "disableLogInfo": true,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "masterPower": false,
            "masterVolume": false,
            "masterMute": false,
            "volumeControl": 0,
            "refreshInterval": 5,
            "enableMqtt": false,
            "mqttDebug": false,
            "mqttAuth": false
        },
        {
            "name": "Den Media",
            "host": "10.0.20.63",
            "port": 8080,
            "zoneControl": 1,
            "getInputsFromDevice": true,
            "inputs": [
                {
                    "name": "Apple TV",
                    "reference": "SMART1",
                    "mode": "MS"
                },
                {
                    "name": "Blu-Ray",
                    "reference": "SMART2",
                    "mode": "MS"
                },
                {
                    "name": "HEOS",
                    "reference": "SMART3",
                    "mode": "MS"
                },
                {
                    "name": "Source",
                    "reference": "SMART4",
                    "mode": "MS"
                }
            ],
            "sensorPower": false,
            "sensorVolume": false,
            "sensorMute": false,
            "sensorInput": false,
            "enableDebugMode": false,
            "disableLogInfo": true,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "masterPower": false,
            "masterVolume": false,
            "masterMute": false,
            "volumeControl": 0,
            "refreshInterval": 5,
            "enableMqtt": false,
            "mqttDebug": false,
            "mqttAuth": false
        }
    ],

**Comment by badgertastic** [comment]
I realised you changed previous default 0 to bulb and have since changed to -1 to resolve issue.

**Comment by grzegorz914** [comment]
I have described all states in readme for sensors, volume and buttons.

**Comment by badgertastic** [comment]
> I have described all states in readme for sensors, volume and buttons.

Thanks. Maybe consider to merge the rows:

<!DOCTYPE html>

volumeControl | Here choice what a additional volume control mode You want to use (None/Disabled, Lightbulb, Fan).
-- | --


<!DOCTYPE html>

Volume Control | -1 - None/Disabled, 0 - Slider, 1 - Fan.
-- | --
