### ISSUE TITLE
"Hey Siri, lights off" mutes AVR

### ISSUE THREAD

**Issue by rpungello** [grzegorz914/homebridge-denon-tv#177]
I'm noticing some odd behavior with versions of this plugin > 3.23.8.
If I say "Hey Siri, lights off", my AVR mutes itself.
Saying "Hey Siri, lights on" raises the volume a tick

Downgrading to 3.23.8 resolved the issue.

In my config file I have "volumeControl": 0

Can't figure this one out. I checked the Home app and there's no mention of the AVR in the "lights" section, but the fact that it resolves itself by downgrading suggests it must be something with this plugin, I just can't figure out what.

**Comment by grzegorz914** [comment]
0 is volume control lightbulb, if you say “Hey Siri Light Off” then make it off, all is correct here. 
Use - 1 to Disabled/None or 1 Fan.
