### ISSUE TITLE
Volume Control as Fan not reporting current setting

### ISSUE THREAD

**Issue by col-forbin** [grzegorz914/homebridge-denon-tv#179]
Steps to repro:
1. Setup Volume as Fan AXR-X2700H
2. Setup in Home
3. Adjust volume to any setting

Actual result:
Volume (Fan) slider works to adjust volume, but immediately displays 0% after setting is complete.

Expected Result:
I would expect the Home app tile to reflect the current volume setting such as 35%.

Regression:
This feature worked in the previous version.

**Comment by kleingunni** [comment]
same issue.
AVR-X1500H
