### ISSUE TITLE
X3500H - SAT/CBL vs CBL/SAT issue

### ISSUE THREAD

**Issue by adamgb** [grzegorz914/homebridge-denon-tv#180]
Using input reference CBL/SAT, correctly pulls the alias name from Receiver but will not switch inputs to the CBL/SAT input.
Using input reference SAT/CBL, does not pull alias name from Receiver, but will switch to the input "CBL/SAT" on the receiver and shows CBL/SAT as the display name in HomeKit.
Looks like in the /denonTv/ folder, the inputsNames_XXX file creates a mapping for CBL/SAT that pulls the correct alias name from the receiver, but then creates another item for SAT/CBL and maps it to a display of "CBL/SAT".
Would like this to work so that when "CBL/SAT" is selected as the inputs reference, it uses that input on the receiver.

**Comment by grzegorz914** [comment]
You can change the name itself in home app. The custom names are stored in inputNames file and loaded every plugin restart.
Reference SAT/CBL is correct reference but If you read inputs from device the AVR inputs list reported it as CBL/SAT and need to be maped to SAT/CBL in other case the inputs will not be switched.

**Comment by grzegorz914** [comment]
I close this because its not a issue.
