### ISSUE TITLE
Zone change?

### ISSUE THREAD

**Issue by Garia666** [grzegorz914/homebridge-denon-tv#184]
After the update to v4 my accessory was unavailable.  I have been troubleshooting for hours and it seems something has changed with the zones.  My config has two zones and only zone 2 was visible. When I changed the zones from 0 to 1 and zone 2  to 2 (config file zone numbers) both are visible again and can be re added to HomeKit.  Only problem now is that the sources stopped working.  I cannot switch between sources .  I am still looking but putting this as an heads up.

**Comment by grzegorz914** [comment]
Get your Config please. Please always configure with GUI this way is safe.

**Comment by grzegorz914** [comment]
Are you read changelog? For 4.0 and 4.1?

**Comment by Garia666** [comment]
So now I can see the mainzone which I am happy about and it’s responding again aswell.

only problem is that the inputs do not switch,  and there is no more volume bar for automation. 

        "name": "G666AV2",
                    "host": "192.168.2.32",
                    "port": 8080,
                    "zoneControl": 1,
                    "getInputsFromDevice": false,
                    "getFavoritesFromDevice": false,
                    "getQuickSmartSelectFromDevice": false,
                    "inputs": [
                        {
                            "name": "Tv",
                            "reference": "TV",
                            "mode": "SI"
                        },
                        {
                            "name": "KPN",
                            "reference": "SAT/CBL",
                            "mode": "SI"
                        },
                        {
                            "name": "NintendoSwitch",
                            "reference": "GAME",
                            "mode": "SI"
                        },
                        {
                            "name": "Spotify",
                            "reference": "SPOTIFY",
                            "mode": "SI"
                        },
                        {
                            "name": "AirPlay",
                            "reference": "NET",
                            "mode": "SI"
                        },
                        {
                            "name": "OnlineMusic",
                            "reference": "FVP",
                            "mode": "SI"
                        }
                    ],
                    "buttons": [
                        {
                            "name": "Power on Denon",
                            "reference": "0ZMON",
                            "displayType": 0
                        },
                        {
                            "name": "Power off denon",
                            "reference": "0ZMOFF",
                            "displayType": 0
                        },
                        {
                            "name": "DTS",
                            "reference": "0MSDTS SURROUND",
                            "displayType": 0
                        }
                    ],
                    "sensorPower": false,
                    "sensorVolume": false,
                    "sensorMute": false,
                    "sensorInput": false,
                    "enableDebugMode": false,
                    "disableLogInfo": false,
                    "disableLogDeviceInfo": false,
                    "disableLogConnectError": false,
                    "supportOldAvr": false,
                    "masterPower": true,
                    "masterVolume": true,
                    "masterMute": false,
                    "infoButtonCommand": "MNINF",
                    "volumeControl": 1,
                    "refreshInterval": 30,
                    "enableMqtt": false,
                    "mqttDebug": false,
                    "mqttAuth": false
                },
                {
                    "name": "Zone 2",
                    "host": "192.168.2.32",
                    "port": 8080,
                    "zoneControl": 2,
                    "getInputsFromDevice": false,
                    "getFavoritesFromDevice": false,
                    "getQuickSmartSelectFromDevice": false,
                    "sensorPower": false,
                    "sensorVolume": false,
                    "sensorMute": false,
                    "sensorInput": false,
                    "enableDebugMode": false,
                    "disableLogInfo": false,
                    "disableLogDeviceInfo": false,
                    "disableLogConnectError": false,
                    "supportOldAvr": false,
                    "masterPower": false,
                    "masterVolume": false,
                    "masterMute": false,
                    "infoButtonCommand": "MNMEN ON",
                    "refreshInterval": 30,
                    "enableMqtt": false,
                    "mqttDebug": false,
                    "mqttAuth": false
                }
            ],
            "platform": "DenonTv"
        }

**Comment by Garia666** [comment]
It seems that g666av2 was actually zone 2 and not the main zone. I set it back to 0 and 1 but then I cannot find it on home kit.

**Comment by grzegorz914** [comment]
Zones was not changed during update 0 - Main Zone 1 - Zone 2 and 2 - Zone 3.  
Are you try to add it from home.app or is not doscobered to add it. If look in Wiki https://github.com/grzegorz914/homebridge-denon-tv/wiki#troubleshooting

**Comment by grzegorz914** [comment]
Due to not response from user close this issue.
