### ISSUE TITLE
How to check for input setting for automation?

### ISSUE THREAD

**Issue by SawkeeReemo** [grzegorz914/homebridge-denon-tv#185]
Hello, I unfortunately wasn’t able to get v4.1 working, and didn’t have time to troubleshoot, so I downgraded back to v3.24. 

One thing I have never been able to figure out how to do is use whatever input setting I’m on in automation. In my automation, I convert it to a shortcut so I can use if/then statements. But I don’t know how to tell it something like “If AVR Main is on Apple TV input then do <action>.” These are the only options I see:
![CEAE3B2D-C8FC-4F30-8498-F68CB9E8E393](https://user-images.githubusercontent.com/60272670/227436273-a6f2955d-0e15-4fa9-b363-f89ed95b9386.jpeg)
So which one of those do I use? Or is there some other way to set the automation to trigger only when a specific input is being used?

Thanks!

**Comment by SawkeeReemo** [comment]
And again… suddenly after posting this I figured it out, and it wasn’t even difficult, I’m just apparently blind or something. My apologies. Please delete this.

**Comment by grzegorz914** [comment]
What is not working in 4.1, can you post the debug log?
