### ISSUE TITLE
Buttons not getting name from HB config

### ISSUE THREAD

**Issue by GeoAlta-admin** [grzegorz914/homebridge-denon-tv#187]
All the Button's that I configure are being loaded in HomeKit as the name of the room they are assigned in and "Speakers", not the name given in the configuration. As an example:

- I have a Denon receiver configured in HB with 2 buttons

1. Multi-Channel Stereo
2. Source Direct

- Both buttons show up with a name of "Living Room Speakers" where I would have expected "Multi-Channel Stereo" and "Source Direct"

The following is the JSON config:
`{
    "devices": [
        {
            "name": "Denon Living Room",
            "host": "10.0.1.45",
            "port": 80,
            "zoneControl": 0,
            "getInputsFromDevice": false,
            "getFavoritesFromDevice": false,
            "getQuickSmartSelectFromDevice": false,
            "inputs": [
                {
                    "name": "AppleTV",
                    "reference": "MPLAY",
                    "mode": "SI"
                }
            ],
            "buttons": [
                {
                    "name": "Multi-Channel Stereo",
                    "reference": "0MSMCH STEREO",
                    "displayType": 1
                },
                {
                    "name": "Source Direct",
                    "reference": "0MSPURE DIRECT",
                    "displayType": 0
                }
            ],
            "sensorPower": false,
            "sensorVolume": false,
            "sensorMute": false,
            "sensorInput": false,
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "supportOldAvr": false,
            "masterPower": false,
            "masterVolume": false,
            "masterMute": true,
            "infoButtonCommand": "MNINF",
            "volumeControl": 0,
            "refreshInterval": 5,
            "enableMqtt": false,
            "mqttDebug": false,
            "mqttAuth": false
        },
        {
            "name": "Denon Dining Room",
            "host": "10.0.1.45",
            "port": 80,
            "zoneControl": 1,
            "getInputsFromDevice": false,
            "getFavoritesFromDevice": false,
            "getQuickSmartSelectFromDevice": false,
            "inputs": [
                {
                    "name": "Power On",
                    "reference": "MPLAY",
                    "mode": "SI"
                }
            ],
            "sensorPower": false,
            "sensorVolume": false,
            "sensorMute": false,
            "sensorInput": false,
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "supportOldAvr": false,
            "masterPower": false,
            "masterVolume": false,
            "masterMute": true,
            "volumeControl": 0,
            "refreshInterval": 5,
            "enableMqtt": false,
            "mqttDebug": false,
            "mqttAuth": false
        }
    ],
    "platform": "DenonTv"
}`

If you go into the Home  app and edit the name, when you delete the name the underlying name appears to be what the button is connected to, but not the name that is configured in HB.

**Comment by grzegorz914** [comment]
This is know issue with HBand iOS16  https://github.com/homebridge/homebridge/issues/3210

**Comment by grzegorz914** [comment]
fixed in latest version
