### ISSUE TITLE
UI Config never saves

### ISSUE THREAD

**Issue by randomhouston** [grzegorz914/homebridge-denon-tv#190]
When I try to add my receiver and setting via the UI the config never saves into hombridge.

**Comment by john2691** [comment]
Same issue, rolling back to an older version (4.1.0) doesn't solve it either.

**Comment by partymild** [comment]
Same issue here, fresh install and it never saves the config. I manually installed the latest 3.x version for it to work; the different 4.x versions all had the same problem.

**Comment by john2691** [comment]
> Same issue here, fresh install and it never saves the config. I manually installed the latest 3.x version for it to work; the different 4.x versions all had the same problem.

This workaround fixed it for me also.

**Comment by randomhouston** [comment]
same, I did the rollback to version 3 workaround and have my receiver back in homekit too

**Comment by julians** [comment]
Same for me

**Comment by TechnoDarkOne** [comment]
I have the same issue, it won't save the config.

**Comment by grzegorz914** [comment]
I don't see any issue with config save, all working correct. Check please your environment, permission, etc...

**Comment by cosnomode** [comment]
same here, other config for other plugins works fine.

**Comment by vanakema** [comment]
same here, no issues with my other plugins

**Comment by Coder84619** [comment]
Same issue for me. Tried to change the IP and it won't save.

**Comment by grzegorz914** [comment]
What happening if you change the config.json manually?

**Comment by Coder84619** [comment]
> What happening if you change the config.json manually?

Where is it located?

**Comment by grzegorz914** [comment]
Check please #196

**Comment by alegend2k** [comment]
Great maybe this is the issue for others also! Try another browser or maybe homemanager app on IOS...there it also works...

**Comment by partymild** [comment]
I've tried with Chrome, Firefox and Edge (newest versions) - same issue, changes I make for the plugin via config-ui doesn't save.

**Comment by alegend2k** [comment]
tried it with an app like homemanger? this was the first step i did and there it saved! then i went to safari und here it saved also...

**Comment by tjq100** [comment]
Homemanager app worked for me as well.  They offer a free 14 day trial but seems like a nice app so I may just get it.

**Comment by grzegorz914** [comment]
@tjq100 

can you try with safari browser?

**Comment by tjq100** [comment]
I was using Safari on an iPad when it wasn’t working.  Just checked and still not saving changes via Safari on iPad.  Here’s a video in case it helps.  Happy to troubleshoot other things if you’d like.  Just let me know.  Cheers,Tim1 Videoshare.icloud.comSent from my iPadOn Jul 5, 2023, at 7:40 AM, Grzegorz ***@***.***> wrote:﻿
@tjq100
can you try with safari browser?

**Comment by grzegorz914** [comment]
What other things would You Troubleshoot ?

**Comment by alegend2k** [comment]
> Homemanager app worked for me as well. They offer a free 14 day trial but seems like a nice app so I may just get it.

let me know if it works with that - for me it did...and since I used it it works on my mac also again...

**Comment by tjq100** [comment]
Should have said, if you want me to try anything elseSent from my iPadOn Jul 5, 2023, at 10:28 AM, alegend2k ***@***.***> wrote:﻿

Homemanager app worked for me as well. They offer a free 14 day trial but seems like a nice app so I may just get it.

let me know if it works with that - for me it did...and since I used it it works on my mac also again...

**Comment by shadegits** [comment]
Same issue, could not delete existing buttons using safari on an iPhone.  Worked just fine using safari on a Mac though.

**Comment by ValadAmoleo** [comment]
Same issue here.  Having to use the last v3 for it to work.  Moving to v4 also stops my second device from working.

**Comment by grzegorz914** [comment]
Please update Config-Ui-X to 4.50.5-test.6 and let me know

**Comment by grzegorz914** [comment]
@ValadAmoleo 

please open new issue regarding stop working of second device, post the config and debug log

**Comment by grzegorz914** [comment]
Any info after update to: 
Config-Ui-X to 4.50.5-test.

**Comment by partymild** [comment]
No change for me unfortunately, tried it with `homebridge-config-ui-x v4.50.5-test.6` and `homebridge-denon-tv v4.3.1` on `homebridge v1.6.1.` with `Node.js Version	v18.13.0`

**Comment by nickp85** [comment]
I was able to edit with Safari, not Chrome, very strange

**Comment by hubertm600** [comment]
I can save setting with android phone chrome broswer

**Comment by Travel-tech** [comment]
Issue still present with latest update. Still need to save the config using Safari. Chrome/Chromium/Edge based browsers simply don't work.

**Comment by Jelledb** [comment]
Same issue here. Config never saves from the UI

**Comment by bsoener** [comment]
Had exactly the same problem always had to edit manually. This does not work with Firefox. I then used Safari and it works with Safari.

**Comment by grzegorz914** [comment]
Probably fixed, 4.7.0-beta published to test, please let me know.

**Comment by bsoener** [comment]
I have the latest version: 4.7.1 and I still can't change anything with Firefox

**Comment by grzegorz914** [comment]
It’s not fixed yet

**Comment by grzegorz914** [comment]
Fixedin 4.8.0

**Comment by anon1y4012** [comment]
Confirmed its working now, nice work @grzegorz914
