### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by mishakim** [grzegorz914/homebridge-denon-tv#191]
Problem started in the last couple of days, my setup had been working. HomeKit now shows the receiver as Not Responding, error below in the Homebridge logs

This is showing every 15 seconds in my log:
`[4/13/2023, 10:23:36 AM] [DenonTv] Device: 10.0.1.109 Home Theater, Info error: TypeError: Cannot convert undefined or null to object, reconnect in 15s.`

Restarting both Homebridge and the receiver did not resolve it. Device is a Marantz NR1510

**Comment by grzegorz914** [comment]
Enable debug please in plugin Config advanced section and get the log

**Comment by mishakim** [comment]
log attached
[homebridge.log](https://github.com/grzegorz914/homebridge-denon-tv/files/11225456/homebridge.log)

**Comment by grzegorz914** [comment]
Try 4.1.12-beta.0 and let me know

**Comment by mishakim** [comment]
Working correctly with 4.1.12-beta.4.  Thanks!
