### ISSUE TITLE
Can’t disable light bulb for volume option

### ISSUE THREAD

**Issue by Seaniak** [grzegorz914/homebridge-denon-tv#193]
For some reason it doesn’t work to change the volume control setting under advanced settings to none. I go in and set it to none, restart homebridge and it’s just not applied. 

My home smart automation that deals with lamps through the HomePod mini will now turn on/off the volume randomly if it controls an automation in the same room as the Denon AVR.

**Comment by Seaniak** [comment]
Strange, must have been something on my end. I reinstalled all of it and that did the trick, strange since I hadn’t touched it for a year and it was working fine up until the latest update.

**Comment by grzegorz914** [comment]
can you post your config.json
