### ISSUE TITLE
Plugin isn’t working anymore since update to 4.x

### ISSUE THREAD

**Issue by Levtos** [grzegorz914/homebridge-denon-tv#198]
Hello, 
last week I had updated the Denon plugin after a few months. From 3.x to the current version. 

Since then, my Denon is only shown as Offline in the Home App. The status "on" is no longer displayed.

Which has pretty much destroyed all my automations. 

I had already tried to change the plugin settings, but they are not saved. 

A new installation including a Homebridge cache reset did not solve the problem.

Need help here. 

The Log from the Homebridge display this: 

`[8.8.2023, 20:58:01] Denon A9C2 is running on port 33135.

[8.8.2023, 20:58:01] Please add [Denon A9C2] manually in Home app. Setup Code: XXX

[8.8.2023, 20:58:02] [homebridge-denon-tv] Device: 192.168.178.31 Denon, Power: OFF

[8.8.2023, 20:58:02] [homebridge-denon-tv]Device: 192.168.178.31 Denon, Input Name: undefined, Reference: undefined

[8.8.2023, 20:58:02] [homebridge-denon-tv] Device: 192.168.178.31 Denon, Mute: ON

[8.8.2023, 20:58:02] [homebridge-denon-tv] Device: 192.168.178.31 Denon, Volume: -64
`

Small note: I have already added the Denon A9C2 manually in the Home App, yet the log shows me to add the device. Is this perhaps already the error?

**Comment by grzegorz914** [comment]
You can edit the config manually and save it, sample-config.json help you to configure the plugin correctly.
If you have any problems with the plugin please post your config.json and debug log.

**Comment by nickp85** [comment]
I have this same issue. I just installed the plugin today and none of my changes in the UI are saved

**Comment by deeloke** [comment]
Hi, same here, The web interface and Homerbidge web interface are working fine, but the homekit shows no response. Node: [v18.16.0]

**Comment by grzegorz914** [comment]
Remove plugin from homeki, clear home bridge cashes and add it again.

**Comment by Levtos** [comment]
> Remove plugin from homeki, clear home bridge cashes and add it again.

I have done the steps several times. Even with a clean Homebridge installation. 

It always comes up with the same result. The plugin does not work.

**Comment by grzegorz914** [comment]
Are you try this: https://github.com/grzegorz914/homebridge-denon-tv/wiki#troubleshooting

Please post your config too?

**Comment by deeloke** [comment]
> Remove plugin from homekit, clear home bridge caches and add it again.

That worked for me. Thanks!

**Comment by Levtos** [comment]
> Are you try this: https://github.com/grzegorz914/homebridge-denon-tv/wiki#troubleshooting
> 
> Please post your config too?

```

{
  "buttons" : [

  ],
  "disableLogConnectError" : false,
  "disableLogDeviceInfo" : false,
  "disableLogInfo" : false,
  "enableDebugMode" : false,
  "enableMqtt" : false,
  "enableRestFul" : false,
  "getInputsFromDevice" : false,
  "host" : "192.168.178.31",
  "infoButtonCommand" : "MNOPT",
  "masterMute" : false,
  "masterPower" : true,
  "masterVolume" : false,
  "name" : "Denon",
  "port" : 8080,
  "refreshInterval" : 5,
  "sensorInput" : false,
  "sensorInputs" : [

  ],
  "sensorMute" : false,
  "sensorPower" : false,
  "sensorVolume" : false,
  "supportOldAvr" : false,
  "surrounds" : [

  ],
  "volumeControl" : 1,
  "zoneControl" : 0
}

```

**Comment by grzegorz914** [comment]
@Levtos 
all ok with your config, you need completely remove the device from Home.app then remove/clear denon cashes from homebridge/persist folder, restart Homebridge and add the device to the Home.app again.

**Comment by Levtos** [comment]
> @Levtos all ok with your config, you need completely remove the device from Home.app then remove/clear denon cashes from homebridge/persist folder, restart Homebridge and add the device to the Home.app again.

Hello, I tried the steps you mentioned yesterday. It still didn’t work.

After that, I reset the entire Homebridge, but that didn’t solve the issue either.

Then, I changed the zone in the configuration from Main to Surround, and since then, it’s been working again. Very strange… 😵‍💫

**Comment by grzegorz914** [comment]
Yes it is very strange, can you post debug log?
please  enable in plugin settings>>>advanced section>>>system save and restart the plugin.

**Comment by Levtos** [comment]
Ok, you find the (full) log here: 

https://privatebin.net/?fbf2cd884b95d5e8#EztVKmMEtyuhFMeEitK44MQLAxp5UMcoJMoZwQNcPsAx

**Comment by grzegorz914** [comment]
It’s not a debug from denon, please enable it as Indescriebed steps in my previous post.

**Comment by Levtos** [comment]
Yes I had actually done that, but now the bug with saving the config is back... that no changes are applied.... 

How do I enable debug mode in the config file?

**Comment by grzegorz914** [comment]
Edit it manually and save

**Comment by Levtos** [comment]
https://privatebin.net/?8c99ba8789f08bf0#CpHko8AN9ZWwbPCZiwdQtqdSskMiEY8x64HDau3NiYeU

**Comment by grzegorz914** [comment]
Ok all looks correct in the log, in Your case you can configure Main Zone, Zone 1 and Surrounds. Please do it and post full config.json.

**Comment by Levtos** [comment]
Here is my full config.json

https://privatebin.net/?b95aa5a4d5bcf3b9#7daa8S5wmpda9j3DN72NtabQsEnTaX6djwnBGFv3hvj6

Regarding the bug with the "not saving," is there a fix or workaround available? Because the configuration interface works with other plugins (even with your LG WebOS plugin), but it's only the Denon plugin that's not functioning correctly. So, the question is, can this be somehow "repaired"?

**Comment by grzegorz914** [comment]
Ok, you have configured only Main Zone and I think is working correct.
To fix saving problem please try to use Safari web browser. This is bug in Config Ui X which need to be fixed.

**Comment by grzegorz914** [comment]
@Levtos still the issue exist with latest release?

**Comment by Levtos** [comment]
I don’t know. I switched last month to Home Assistant. Am 03.01.2024 um 13:14 schrieb Grzegorz ***@***.***>:﻿
@Levtos still the issue exist with latest release?

**Comment by grzegorz914** [comment]
OK, then close this now.
