### ISSUE TITLE
Volume switch on/off to mute/unmute

### ISSUE THREAD

**Issue by guysbrown** [grzegorz914/homebridge-denon-tv#20]
Hey,

Great plugin. 

Could you change the Volume switch so that the on/off state of the switch mutes or unmutes the volume in addition to the brightness controlling the volume level. 

Also, once implemented could you automatically set the state of the volume switch to off when the receiver is off. 

Best Regards 

Guy

**Comment by grzegorz914** [comment]
State mute switch automatically assigned to the powerSwitch state.
