### ISSUE TITLE
Feature request: specify HomeKit port

### ISSUE THREAD

**Issue by tchan09** [grzegorz914/homebridge-denon-tv#200]
Could we have an option to specify the port for HomeKit connect to? I believe right now it defaults to a random port on start.

For example, port 41155 is chosen at random below:
```
[8/23/2023, 10:04:37 PM] denon-avr EFBD is running on port 41155.
[8/23/2023, 10:04:37 PM] Please add [denon-avr EFBD] manually in Home app. Setup Code: 421-31-355
```

Thanks!

**Comment by grzegorz914** [comment]
Port is automatically assigned from Homebridge, you can set range port for all plugins in HB settings. Right now HB doesn’t allow to set manually port for every plugin, only for child bridge can be changed. For more info please refer to HB Wiki.

**Comment by tchan09** [comment]
Thanks for the pointer, I was able to figure it out.

For future readers, the syntax is:
```json
{
    "bridge": { },
    "ports": {
        "start": 12345,
        "end": 12345
    }
}
```
