### ISSUE TITLE
denon completely off

### ISSUE THREAD

**Issue by bsoener** [grzegorz914/homebridge-denon-tv#202]
Hi. Thanks for the plugin for my AVR 3313. Can I actually turn off the message (not reachable) on my Homebridge that my Denon is not reachable? I only use my AVR when I listen to music, otherwise I switch it off completely. 

But what I also noticed is that if I change something under the plugin settings and save and restart it, it is not saved?

**Comment by grzegorz914** [comment]
Yes

![Zrzut ekranu 2023-08-30 o 17 13 33](https://github.com/grzegorz914/homebridge-denon-tv/assets/28867813/b33cc16c-24c5-48b7-98d7-fc5eaa8fbf28)

**Comment by bsoener** [comment]
ok thanks for the info. I overlooked it. Unfortunately, I can't save it. After restarting the Homebridge the hook is out again

**Comment by grzegorz914** [comment]
You can add manually to your config.json “disableLogConnectError”: true, save and restart HB

**Comment by bsoener** [comment]
ok worked. Thank you
