### ISSUE TITLE
Volume, mute and other controls not appearing

### ISSUE THREAD

**Issue by nebosphere19** [grzegorz914/homebridge-denon-tv#203]
It might be that I don't understand how this plugin is supposed to work, but the only controls I have available are the input and the power of my Denon x3800h. Is this expected? Anything I need to change? 

`
    "devices": [
        {
            "name": "Denon-AVR-X3800H",
            "host": "10.0.0.40",
            "port": 8080,
            "zoneControl": 0,
            "getInputsFromDevice": true,
            "getFavoritesFromDevice": true,
            "getQuickSmartSelectFromDevice": true,
            "sensorPower": true,
            "sensorVolume": true,
            "sensorMute": true,
            "sensorInput": true,
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "supportOldAvr": false,
            "masterPower": true,
            "masterVolume": true,
            "masterMute": true,
            "refreshInterval": 5,
            "enableRestFul": false,
            "restFulDebug": false,
            "enableMqtt": false,
            "mqttDebug": false,
            "mqttAuth": false
        }
    ],
    "platform": "DenonTv"
}`

**Comment by grzegorz914** [comment]
You can change Volume using hardware button after you go to RC app on iPhone/Ipad or enable legacy volume control in plugin Advanced Settings>>Device>>Volume Control Mode, in this case will appear extra tile.

**Comment by nebosphere19** [comment]
What’s weird is that legacy volume control is on but I don’t have an extra
tile in the home app. I’ll try it with the rc app without the legacy flag.

**Comment by grzegorz914** [comment]
The tile appear inside the main zone tile.

**Comment by nebosphere19** [comment]
Got it, it works for volume. I don't have one for mute however and the mute
button in the RC app is non-functional for the Denon....

**Comment by grzegorz914** [comment]
Hardware mute button do not have its own characteristics, will newer work. Use legacy volume control instead.
