### ISSUE TITLE
Feature request: SCREEN DIMMER CHOICE

### ISSUE THREAD

**Issue by Joaav** [grzegorz914/homebridge-denon-tv#205]
Hi, I am trying to add a multiple choice for screen dimmer similary as it is done for inputs. I do not think it is possible. Could you please add such function?

**Comment by grzegorz914** [comment]
You can create buttons with this functions: 
![Zrzut ekranu 2023-10-22 o 20 56 11](https://github.com/grzegorz914/homebridge-denon-tv/assets/28867813/17fe14b0-7c07-4f0a-a8a2-95bc5c61d100)

**Comment by Joaav** [comment]
> You can create buttons with this functions: ![Zrzut ekranu 2023-10-22 o 20 56 11](https://user-images.githubusercontent.com/28867813/277186385-17fe14b0-7c07-4f0a-a8a2-95bc5c61d100.png)

It does not work on my Denon AVR-X2000. What about select toggle?

**Comment by grzegorz914** [comment]
What is not work, the buttons are not displayed, no function, any debug log?

**Comment by Joaav** [comment]
All I get is "[10/22/2023, 9:28:01 PM] [homebridge-denon-tv] Device: 192.168.0.53 Denon AVR-X2000, set Button Name: SCREEN OFF, Reference: DIM OFF".  Buttons show up but nothing happens on the screen.

**Comment by grzegorz914** [comment]
Go to advanced settings > system, enable debug and get the log during press the button.

**Comment by Joaav** [comment]
Nothing more appears, sometimes when i press many times i get this:

[10/22/2023, 9:47:11 PM] [homebridge-denon-tv] Device: 192.168.0.53 Denon AVR-X2000, set Button Name: SCREEN DIMMED, Reference: DIM DIM
[10/22/2023, 9:47:12 PM] [homebridge-denon-tv] Device: 192.168.0.53 Denon AVR-X2000, set Button Name: SCREEN DIMMED, Reference: DIM DIM
(node:27764) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by grzegorz914** [comment]
I will check this tomorrow

**Comment by grzegorz914** [comment]
I’m tested on my side AVR-X6300H and working OK, the lcd display changed its brightness. Can you change the brightness with RC ?

**Comment by Joaav** [comment]
I can do so through settings

Wiadomość napisana przez Grzegorz ***@***.***> w dniu 23.10.2023, o godz. 15:16:

﻿

I’m tested on my side AVR-X6300H and working OK, the lcd display changed its brightness. Can you change the brightness with RC ?

**Comment by grzegorz914** [comment]
Hi, i have checked Denon Control Protocol for AVR-X2000 and direct LCD Dimm functionis not supported, so will not work in your case.
