### ISSUE TITLE
Marantz PM7000N not Compatible?

### ISSUE THREAD

**Issue by DMcWetty** [grzegorz914/homebridge-denon-tv#207]
I have a Denon X3800H AVR connected to HB via this plug in (it works great, thanks so much). However, I also have a Marantz PM7000N I'd like to bring into HB, but it refuses to connect on either port 80 or 8080. I suspect this has something to do with newer Marantz amps not supporting HTTP connections. Has anyone managed a work around for this?

EDIT: Forgot the log error message: `[homebridge-denon-tv] Device: 192.168.7.163 Marantz PM7000N, Info error: Error: connect ECONNREFUSED 192.168.7.163:8080, reconnect in 15s.`

**Comment by grzegorz914** [comment]
get the debug log please, go to plugin settings >> advanced section >>> system >> enable debug and get the log please

**Comment by DMcWetty** [comment]
`[11/1/2023, 8:19:35 AM] [homebridge-denon-tv] Device: 192.168.6.243 Theater Denon X3800H, debug: State: {
  "Power": {
    "value": "OFF"
  },
  "InputFuncSelect": {
    "value": "MPLAY"
  },
  "VolumeDisplay": {
    "value": "Absolute"
  },
  "MasterVolume": {
    "value": -35
  },
  "Mute": {
    "value": "off"
  }
}
[11/1/2023, 8:19:37 AM] [homebridge-denon-tv] Device: 192.168.7.163 Marantz PM7000N, Info error: Error: connect ECONNREFUSED 192.168.7.163:8080, reconnect in 15s.
[11/1/2023, 8:19:40 AM] [homebridge-denon-tv] Device: 192.168.6.243 Theater Denon X3800H, debug: State: {
  "Power": {
    "value": "OFF"
  },
  "InputFuncSelect": {
    "value": "MPLAY"
  },
  "VolumeDisplay": {
    "value": "Absolute"
  },
  "MasterVolume": {
    "value": -35
  },
  "Mute": {
    "value": "off"
  }
}
[11/1/2023, 8:19:45 AM] [homebridge-denon-tv] Device: 192.168.6.243 Theater Denon X3800H, debug: State: {
  "Power": {
    "value": "OFF"
  },
  "InputFuncSelect": {
    "value": "MPLAY"
  },
  "VolumeDisplay": {
    "value": "Absolute"
  },
  "MasterVolume": {
    "value": -35
  },
  "Mute": {
    "value": "off"
  }
}
[11/1/2023, 8:19:50 AM] [homebridge-denon-tv] Device: 192.168.6.243 Theater Denon X3800H, debug: State: {
  "Power": {
    "value": "OFF"
  },
  "InputFuncSelect": {
    "value": "MPLAY"
  },
  "VolumeDisplay": {
    "value": "Absolute"
  },
  "MasterVolume": {
    "value": -35
  },
  "Mute": {
    "value": "off"
  }
}
[11/1/2023, 8:19:52 AM] [homebridge-denon-tv] Device: 192.168.7.163 Marantz PM7000N, Info error: Error: connect ECONNREFUSED 192.168.7.163:8080, reconnect in 15s.
[11/1/2023, 8:19:55 AM] [homebridge-denon-tv] Device: 192.168.6.243 Theater Denon X3800H, debug: State: {
  "Power": {
    "value": "OFF"
  },
  "InputFuncSelect": {
    "value": "MPLAY"
  },
  "VolumeDisplay": {
    "value": "Absolute"
  },
  "MasterVolume": {
    "value": -35
  },
  "Mute": {
    "value": "off"
  }
}
[11/1/2023, 8:20:00 AM] [homebridge-denon-tv] Device: 192.168.6.243 Theater Denon X3800H, debug: State: {
  "Power": {
    "value": "OFF"
  },
  "InputFuncSelect": {
    "value": "MPLAY"
  },
  "VolumeDisplay": {
    "value": "Absolute"
  },
  "MasterVolume": {
    "value": -35
  },
  "Mute": {
    "value": "off"
  }
}`

**Comment by grzegorz914** [comment]
23 is telnet port cannot be used here, I will check possibility to add support for this new device

**Comment by DMcWetty** [comment]
Thank you for your dedication!

**Comment by grzegorz914** [comment]
@DMcWetty 

look here #211 and let me know if this work for You.
