### ISSUE TITLE
No configuration found for homebridge-denon-tv

### ISSUE THREAD

**Issue by shanekelly55** [grzegorz914/homebridge-denon-tv#213]
Hi There,

I have my json configured but i dont think anything is being applied persistently to the plugin.

attached the JSOn for your review.  Nothing is present in the Configs of the plugin.  I am running this a child bridge.
[new 2.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/13790111/new.2.txt)

**Comment by grzegorz914** [comment]
The config have two time `DenonTv` platform in different place, it can not be working. Use Config UI X to config this plugin.
