### ISSUE TITLE
Nothing shows up in HomeKit v4.4.2

### ISSUE THREAD

**Issue by SawkeeReemo** [grzegorz914/homebridge-denon-tv#214]
I've been running v3 for a really long time since I haven't had time to rebuild all of my automations. I decided to take the plunge today, and of course, nothing is working because that's my luck. (Homebridge is running in Docker on a Rpi4)

I decided to do a clean install of Denon TV and just start over. So I backed up my old version's config, and removed the plugin. There is nothing listed in the homebridge cache for Denon TV at all now, so there's nothing for me to clear (unless there's another way to do this that I'm unfamiliar with).

I installed Denon TV 4.4.2 set it all up, started a a child bridge, scanned the QR code, etc etc... But when I go to add accessory, nothing is there. When I type the code in manually, still, nothing is there. The plugin logs show that it can see my Denon AVR-3400X no problem, plus all the settings. I've tried uninstalling/reinstalling the plugin, restarting homebridge 500 times, unpaired from home kit, disabling/re-enabling/repairing child bridge... But nothing ever appears in HomeKit. I'm at a loss. All of my other plugins work.

How do I make this new version work? Thanks!

EDIT: Here is my config file - https://hastebin.com/share/asuqaxasib.json

**Comment by SawkeeReemo** [comment]
I just tried reverting back to v3 of the plugin, but again, when I add the Child Bridge to HomeKit, nothing shows up. So I'm sorta screwed now.

**Comment by grzegorz914** [comment]
May be try to change its Name in config.

**Comment by SawkeeReemo** [comment]
Which thing? And it's been so long I can't remember, after I link the child bridge, it should show all my accessories when I go to the bridge menu in HomeKit, right? Because it shows zero. The bride connects, but no accessories. I tried nuking the entire persist folder, but that just broke all my other child bridges... haha

**Comment by grzegorz914** [comment]
Just the name from AVR Main to Receiver or so

**Comment by SawkeeReemo** [comment]
Ok, I'll try that. I just made a whole new Homebridge container with nothing in it. Added DenonTv, put my info in as Receiver with the IP, etc... then I see this error in the log:
![Screen Shot 2024-01-01 at 9 25 23 PM](https://github.com/grzegorz914/homebridge-denon-tv/assets/60272670/af6a5bb8-b1cc-4647-9754-d531c514b2a1)

**Comment by grzegorz914** [comment]
The error appear only after plugin restart or in the first run, will be fixed today.

**Comment by SawkeeReemo** [comment]
Right on. So, after building a whole new Homebridge from scratch, I've just been able to see things show up. So, I'm not sure what would cause this, I'm going to just rebuild everything and see what happens.

**Comment by SawkeeReemo** [comment]
FYI: The complete rebuild of Homebridge seems to be working. So, something must have been borked on my end.
