### ISSUE TITLE
How to stop buttons from being renamed when adding a new one?

### ISSUE THREAD

**Issue by SawkeeReemo** [grzegorz914/homebridge-denon-tv#215]
Is there a way to stop having all the buttons get renamed with the accessory name as a prefix every time you add a new button?

For example, my main accessory is AVR Main. And every time I add a new button it renames all of my existing buttons to "AVR Main-ButtonName"... After I've already renamed them how I want them to look in HomeKit. 
![IMG_6893](https://github.com/grzegorz914/homebridge-denon-tv/assets/60272670/9a6a7e32-c730-45a6-8a2f-033f99c480aa)

**Comment by grzegorz914** [comment]
added in 4.5.0 for buttons and sensors

**Comment by SawkeeReemo** [comment]
Wow! That was fast! Thank you!
