### ISSUE TITLE
Error showing up every couple minutes

### ISSUE THREAD

**Issue by SawkeeReemo** [grzegorz914/homebridge-denon-tv#216]
I'm pretty sure you already know about this and are working on a fix, but I figured I'd log it here as a bug so we can see once you've addressed it. Thanks again for all your work on this! It's pretty great!

![Screen Shot 2024-01-02 at 3 32 39 AM](https://github.com/grzegorz914/homebridge-denon-tv/assets/60272670/8dbd614d-6561-4aea-b341-f2b0dab9e3a1)

**Comment by grzegorz914** [comment]
I don't see this error on my side, can you post debug log, go to plugin settings Advanced Section>>>System>>>Debug enable it and restart plugin.

**Comment by SawkeeReemo** [comment]
https://hastebin.com/share/saruqebeva.css

**Comment by SawkeeReemo** [comment]
https://hastebin.com/share/saruqebeva.css

**Comment by WJKramer** [comment]
I am seeing the same thing since 4.4.0. No response in homekit as a result. Going back to 4.3.33 resolves the error.

**Comment by grzegorz914** [comment]
Can you try 4.5.0

**Comment by grzegorz914** [comment]
OK probably found what is going wrong, please try 4.5.1-beta

**Comment by SawkeeReemo** [comment]
Still happening with the beta unfortunately. https://hastebin.com/share/iqojusiwar.csharp
Also, I have to go to bed now, been up all night working on this. (almost 4:30am here) Thanks again for taking a look. I'll check back in once I get some sleep.

**Comment by grzegorz914** [comment]
Very strange because I can not reproduce this issue on my side

**Comment by grzegorz914** [comment]
beta.1 ready to test

**Comment by WJKramer** [comment]
> beta.1 ready to test

Beta1 does not resolve unfortunately.

[1/2/2024, 7:36:36 AM] [DenonTv] Device: 192.168.10.39 Denon AVR, Read saved Input Names error: SyntaxError: Unexpected end of JSON input
[1/2/2024, 7:36:36 AM] [DenonTv] Device: 192.168.10.39 Denon AVR, Read saved Input Target Visibility error: SyntaxError: Unexpected end of JSON input

[1/2/2024, 7:36:39 AM] [homebridge-denon-tv] This plugin threw an error from the characteristic 'Active Identifier': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'name'). See https://homebridge.io/w/JtMGR for more info.

**Comment by grzegorz914** [comment]
please remove inputsNames and inputsTargetVisibility files from home bridge/denonTv folder and restart plugin again

**Comment by WJKramer** [comment]
> please remove inputsNames and inputsTargetVisibility files from home bridge/denonTv folder and restart plugin again

Deleted the 2 files as requested....restarted plug in and the error presists. Also saw beta 2 and updated.

**Comment by grzegorz914** [comment]
try beta.14 please

**Comment by WJKramer** [comment]
Installed beta.14 and this error remains along with no response in homekit.

`[1/2/2024, 12:39:42 PM] [homebridge-denon-tv] This plugin threw an error from the characteristic 'Active Identifier': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'name'). See https://homebridge.io/w/JtMGR for more info.`

Interesting though I no longer get the SyntaxError's I included above. I did delete the two files as you requested so I wonder if that solved that particular part.

Again falling back to 4.3.33 solves the issues. Thanks for you continued support with this.

**Comment by SawkeeReemo** [comment]
FYI: The issue has not returned for me so far. I'll report back here if I see it again. Thanks again for being such a great developer.

**Comment by WJKramer** [comment]
Just want to let you know I solved this by removing the plug-in and deleting any cache in Homebridge then re-adding v4.5.1. I had to use Safari to save the plug-in configuration as it wasn't sticking in chrome per this issue:

https://github.com/grzegorz914/homebridge-denon-tv/issues/190

Thank you for your hard work on this!
