### ISSUE TITLE
'Active Identifier': Unhandled error

### ISSUE THREAD

**Issue by badgertastic** [grzegorz914/homebridge-denon-tv#217]
See https://github.com/grzegorz914/homebridge-denon-tv/issues/212#issuecomment-1874123627

**Comment by grzegorz914** [comment]
try beta.14 please

**Comment by badgertastic** [comment]
v4.5.1-beta.14. Active identifier error gone thanks. 

Input selection not corresponsiding issue remains. See https://github.com/grzegorz914/homebridge-denon-tv/issues/212#issuecomment-1874123627

**Comment by grzegorz914** [comment]
Input selector must be also OK, I have tested this and in log the info corresponded with selector every time on my side. May be try to remove old cache.

**Comment by badgertastic** [comment]
Stopped the child bridge. Removed the bridge cache for the problem marantz zone (main zone) from HomeKit (other zone 2 and zone 3 seem ok, so left). removed the main zone device from Home app, restarted entire homebridge. Readded into home. Same issue.

Even repeated all above, with addition of remove, rename and put main zone in different order in config.json.. same issue.

changed from a sending by name to name, restarted. Same issue.

force quit all home apps on iOS devices. No joy. 

restarted AppleTV acting as bridge. Home hub active device changed to other appletv… same issue. 

I guess I’ll just change my scenes and automations to select the input that actually works rather than the configured name.

**Comment by badgertastic** [comment]
Anything worth removing in .homebridge/denonTv (like was needed with lgwebosTv) ?

**Comment by grzegorz914** [comment]
Yes, you can same files remove if get same error.

**Comment by badgertastic** [comment]
Not the same error, but the inputs not corresponding

**Comment by grzegorz914** [comment]
Try remove both files and check.

**Comment by badgertastic** [comment]
Ok it fixed it. Whoop, finally :)

rm .homebridge/denonTv/inputs*

(Also removed target*, looks like legacy name no longer used)

**Comment by grzegorz914** [comment]
Yes, legacy name is only used if not changed by user.

**Comment by ValadAmoleo** [comment]
> Ok it fixed it. Whoop, finally :)
> 
> rm .homebridge/denonTv/inputs*
> 
> (Also removed target*, looks like legacy name no longer used)

Thank you for this.  It solved the issue for me too.

Might be worth adding to the Troubleshooting page.

**Comment by grzegorz914** [comment]
This will newer happen in future, this fix need to be applied only one time.
