### ISSUE TITLE
Problem Reciever Marantz M-CR611,

### ISSUE THREAD

**Issue by tomasroud73** [grzegorz914/homebridge-denon-tv#219]
I suddenly had a problem at Homebrudge. Homebebridge plugin homebridge-denon-tv. So far it worked, without changing the configuration. Suddenly the status in Homekit - Not Responding. The Homebridge log says "Device: 192.168.10.121 Reciever, No any inputs are configured, check your config and settings"
[Denon.docx](https://github.com/grzegorz914/homebridge-denon-tv/files/13834702/Denon.docx)

**Comment by grzegorz914** [comment]
Please go to homebridge/denontv/ folder and remove inputs, inputsNames, inputsTargetVisibility files, restart plugin

**Comment by tomasroud73** [comment]
So I did, I deleted said files. Performed a reboot of Homebridge, but the errors are still the same. When I list the directory, it prints the following: devInfo_19216810121 devInfo_MZ19216810121 devInfo_Z219216810121 inputsNames_MZ19216810121 inputsTargetVisibility_MZ19216810121 inputs_MZ19216810121

**Comment by grzegorz914** [comment]
Please enable debug mode in plugin config Advanced Settings>>.System>>>Debug restart plugin and get the whole log

**Comment by tomasroud73** [comment]
[homebridge.log.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/13835470/homebridge.log.txt)

**Comment by grzegorz914** [comment]
please update to 4.5.6 and let me know

**Comment by tomasroud73** [comment]
Proveden upgrade na v 4.5.6 beta. posílám debug.
[Uploading homebridge.log.txt…]()

**Comment by tomasroud73** [comment]
[homebridge.log.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/13838325/homebridge.log.txt)

**Comment by grzegorz914** [comment]
check please 4.5.6-beta.7 and let me know

**Comment by tomasroud73** [comment]
After updating to 4.5.6 beta 8

[homebridge.log-2.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/13839619/homebridge.log-2.txt)

**Comment by grzegorz914** [comment]
check please 4.5.6-beta.10 and let me know

**Comment by tomasroud73** [comment]
I've done the update. In the accessories Homebridge is added, but after adding the bridge to Homekit only the bridge is added, but the buttons are not visible in Homekit. Reciever cannot be controlled.
[Uploading homebridge.log-3.txt…]()

**Comment by grzegorz914** [comment]
Log please

**Comment by tomasroud73** [comment]
sorry
[homebridge.log-4.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/13844290/homebridge.log-4.txt)

**Comment by tomasroud73** [comment]
I tried renaming the bridge when adding it, but that didn't help. How do I know which file in the /var/lib/homebridge/persist path to delete. there are many

**Comment by grzegorz914** [comment]
Inside the file is `{"displayName":"AV Receiver"}`,  search for your receiver name

**Comment by tomasroud73** [comment]
Thank you very much. Removed the bridge from Homekit, deleted the files containing the words Marantz and Reciever. Rebooted Homebridge. Then added the Denon bridge and the Reciever accessories and it is now working.
