### ISSUE TITLE
DC and MS Command sets from AVR Control Protocol

### ISSUE THREAD

**Issue by intrepidsilence** [grzegorz914/homebridge-denon-tv#22]
Is there any chance that you will be implementing the DC and MS command sets from the control Protocol to retrieve and set the Sound Modes?

**Comment by grzegorz914** [comment]
This is possible but I don’t have idea how to integrate this in TV service. I don’t want to create extra tile for this. I will check if is possible to add extra list with Sound Modes I siede same Tile.

**Comment by intrepidsilence** [comment]
Cool, thanks for looking into this. I was wondering the same thing about whether or not you could have two lists beside each other.  Curious to hear what you find out.

**Comment by grzegorz914** [comment]
Hi,
Please update to the latest version 1.6.0
- added possibility to set Surrounds Mode
- added possibility to set Digital Input Mode
- added possibility to set Favorite
all selectable from the same list as inputs.

**Comment by intrepidsilence** [comment]
Whoa!  Nice job!  Thanks so much!

**Comment by intrepidsilence** [comment]
Do you have config examples and a list of the possible entries? I think I can guess how it works but =it would be better if it was spelled out in the docs.  This is so awesome that I can't wait to try it out.

Thanks again!

**Comment by grzegorz914** [comment]
https://www.heimkinoraum.de/upload/files/product/IP_Protocol_AVR-Xx100.pdf

**Comment by intrepidsilence** [comment]
Ok, so I used that to create these additions to my config:

			{
                            "name": "Auto Sound Mode",
                            "reference": "MSAUTO",
                            "type": "MS"
                        },
                        {
                            "name": "Multi-Channel Stereo",
                            "reference": "MSMCH STEREO",
                            "type": "MS"
                        },
                        {
                            "name": "DTS Neo:X Music",
                            "reference": "MSDTS NEO:X M",
                            "type": "MS"
                        }

However, even when I have them as "separate tiles" when I click on them all they do is open the config for that tile.  What did I miss?

**Comment by intrepidsilence** [comment]
I got the bright idea to remove the accessory from Home completely and then re-add it.  When I did that the sound modes show up in the input list and so are not very useful there. Am I still doing it wrong?

**Comment by grzegorz914** [comment]
> Ok, so I used that to create these additions to my config: { "name": "Auto Sound Mode", "reference": "MSAUTO", "type": "MS" }, { "name": "Multi-Channel Stereo", "reference": "MSMCH STEREO", "type": "MS" }, { "name": "DTS Neo:X Music", "reference": "MSDTS NEO:X M", "type": "MS" } However, even when I have them as "separate tiles" when I click on them all they do is open the config for that tile. What did I miss?
> […](#)

Do not add Extra MS commanf to reference

**Comment by grzegorz914** [comment]
I close this as resolved. All tested and working as excepted.
