### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by ValadAmoleo** [grzegorz914/homebridge-denon-tv#220]
Updating to version 4.5.3 results in a crash loop with this error:

Cinema Denon Surround Mode, State error: TypeError: Cannot read properties of undefined (reading 'name'), reconnect in 5s.

I tried going to the homebridge/denontv/ folder and removing inputs, inputsNames, inputsTargetVisibility files but it didn't work this time.

Going back to version 4.5.2 and everything works fine.

**Comment by grzegorz914** [comment]
Debug please

**Comment by grzegorz914** [comment]
fixed 4.5.4
