### ISSUE TITLE
Cannot rename buttons [v4.5.12]

### ISSUE THREAD

**Issue by DasKraut37** [grzegorz914/homebridge-denon-tv#225]
I’ve noticed with at least this latest version, that renaming buttons in the config UI doesn’t work once you restart the child bridge. I have not tested previous versions, or manually adjusting the JSON yet to see if that will work. Will report back when I do. 

UPDATE: It works if I edit the JSON config by hand, it just didn’t work if I trying it in the UI Config.

**Comment by grzegorz914** [comment]
This is know issue #190  not fixed yet.
