### ISSUE TITLE
`inputs.mode` documentation

### ISSUE THREAD

**Issue by DonutEspresso** [grzegorz914/homebridge-denon-tv#227]
Hello - I wanted to clarify what the `inputs.mode` configuration is for. In the config UI I see values for `input`, `favorite`, and `quick/smart select`. Does this basically specify what bucket to attempt to pull the "reference" value from? e.g., if you specified a string that doesn't exist in the bucket, presumably that would be a failed configuration?

**Comment by grzegorz914** [comment]
The `inputs, favorite, quick/smart select` for `reference` use different prefix to set correct input on device,  the inputs list contain all inputs and also favourite and quick/smart select programable  buttons, so in this case need to set correct prefix.

**Comment by grzegorz914** [comment]
I can this identify automatically, will add it in next release.

**Comment by grzegorz914** [comment]
added in 4.7.0-beta.3, can You check correct functionality on Your side

**Comment by DonutEspresso** [comment]
Thanks! Just tried beta7, seems to work as expected. This is helpful, makes it harder for users to get something wrong accidentally. Also verified the fix for #226. Thank you! 👍
