### ISSUE TITLE
Error with 4.7.0 and empty config page and config ui won't save

### ISSUE THREAD

**Issue by MichlW** [grzegorz914/homebridge-denon-tv#228]
After updating from 4.6.0 to 4.7.0 i continiously get this error:
`[DenonTv] Device: 172.16.3.31 Receiver, Info error: AxiosError: Request failed with status code 403, reconnect in 15s.`

I tried to fix it by one time editing through ConfigUI, but it stays empty at first:
![image](https://github.com/grzegorz914/homebridge-denon-tv/assets/49558935/905391b8-02a2-4f91-a497-e5b6a2199522)

After clicking around the window and switched through some browser tabs, the config ui comes up and i discovered a new generation selector. After changing this to "middle gen", saving and restarting homebridge, the same error occurs.
There are no generation changes in config.json.

Any ideas?

**Comment by MichlW** [comment]
I fixed this by manually adding `"generation": 1,` to config.json.

**Comment by MichlW** [comment]
OT: There is a small typo in config ui:
![image](https://github.com/grzegorz914/homebridge-denon-tv/assets/49558935/96889e6b-df86-486f-afb6-3d197ce2fda4)

**Comment by grzegorz914** [comment]
The config not save its changes because of use very big `oneOf` functions, I will investigate to fix this.
The typo will be fixed in next update.

**Comment by tobihoby** [comment]
Hi.

After updating to version 4.7.1, all Denon devices no longer respond in the Apple Home app. According to the log, the name of the connected device has changed?! I can see it when I compare version 4.6.0 and 4.7.1 in the log.

Greets
Tobi

**Comment by grzegorz914** [comment]
Was nothing changed about name, just add `generation` property to the config because UI do not save its changes. Just edit it manually.

**Comment by tobihoby** [comment]
thats it! Thank you.

**Comment by kleingunni** [comment]
> Hi.
> 
> After updating to version 4.7.1, all Denon devices no longer respond in the Apple Home app. According to the log, the name of the connected device has changed?! I can see it when I compare version 4.6.0 and 4.7.1 in the log.
> 
> Greets
> Tobi

same issue
BR Gunnar

**Comment by grzegorz914** [comment]
Same fix as before

**Comment by kleingunni** [comment]
Yes
BR Gunnar

**Comment by grzegorz914** [comment]
fixed in 4.8.0

**Comment by bsoener** [comment]
I did the latest update earlier and now I get this error message:

[17.1.2024, 13:19:09] [DenonTv] Device: 192.168.178.113 Denon 4800, prepare accessory error: TypeError: serviceType is not a constructor
