### ISSUE TITLE
After updating from version 4.7.1 to 4.8.1 no responding in HomeKit

### ISSUE THREAD

**Issue by kleingunni** [grzegorz914/homebridge-denon-tv#229]
After updating from version 4.7.1 to 4.8.1 I get the following error message.

[17.1.2024, 05:42:02] [homebridge-denon-tv] Device: 192.168.178.100 Denon Receiver, Reference: TV
[17.1.2024, 05:42:02] [homebridge-denon-tv] Device: 192.168.178.100 Denon Receiver, Volume: -53dB
[17.1.2024, 05:42:02] [homebridge-denon-tv] Device: 192.168.178.100 Denon Receiver, Mute: ON
[17.1.2024, 05:42:02] [homebridge-denon-tv] Device: 192.168.178.100 Denon Receiver, Volume Control Type: Absolute
[17.1.2024, 05:42:02] [homebridge-denon-tv] Device: 192.168.178.100 Denon Receiver, Picture Mode: OFF
[17.1.2024, 05:42:02] [homebridge-denon-tv] Device: 192.168.178.100 Denon Receiver, Disconnected.
[17.1.2024, 05:42:10] [homebridge-denon-tv] Device: 192.168.178.100 Denon Receiver, State error: Error: connect EHOSTUNREACH 192.168.178.100:8080, reconnect in 5s.
[17.1.2024, 05:42:10] [homebridge-denon-tv] Device: 192.168.178.100 Denon Receiver, Power: OFF

**Comment by grzegorz914** [comment]
4.7.9 was never released, go to plugin config and update your settings.

**Comment by grzegorz914** [comment]
Get the debug log

**Comment by grzegorz914** [comment]
This is not debug, debug can be enabled in plugin settings Advanced Settings section

**Comment by grzegorz914** [comment]
Arę You set correct device generation?

**Comment by kleingunni** [comment]
> Are You set correct device generation?

Which mode do I have to set?
use the AVR-X1500H.

**Comment by grzegorz914** [comment]
middle

**Comment by kleingunni** [comment]
Plugin reinstalled.
config newly created.
it works again.

Thanks for the good support.

BR Gunnar

**Comment by tobihoby** [comment]
Hi,

I have the same problem, no response in Apple Home. I actually don't want to delete the plugin config because I would then have to adjust various scenes. Device generation is correct (middle). The log file looks okay.

**Comment by grzegorz914** [comment]
Get your config please

**Comment by tobihoby** [comment]
"platform": "DenonTv",
    "devices": [
        {
            "buttonsZone2": [],
            "mqttDebug": false,
            "buttons": [],
            "buttonsZ3": [],
            "masterMute": false,
            "mqttAuth": false,
            "surrounds": [],
            "getInputsFromDevice": false,
            "generation": 1,
            "inputsDisplayOrder": 0,
            "supportOldAvr": false,
            "disableLogConnectError": false,
            "zoneControl": 0,
            "enableDebugMode": false,
            "sensorMute": false,
            "inputs": [
                {
                    "reference": "SAT/CBL",
                    "name": "Sky Q",
                    "mode": "SI"
                },
                {
                    "mode": "SI",
                    "name": "TV Audio",
                    "reference": "TV"
                },
                {
                    "mode": "SI",
                    "name": "Apple TV",
                    "reference": "BD"
                },
                {
                    "mode": "SI",
                    "name": "Switch",
                    "reference": "AUX2"
                }
            ],
            "sensorPower": false,
            "buttonsZone3": [],
            "masterVolume": true,
            "enableMqtt": false,
            "volumeControl": 2,
            "port": 80,
            "masterPower": false,
            "buttonsZ2": [],
            "name": "Denon",
            "buttonsMainZone": [],
            "refreshInterval": 3,
            "host": "192.168.0.7",
            "sensorInput": false,
            "disableLogDeviceInfo": false,
            "disableLogInfo": false,
            "infoButtonCommand": "MNINF",
            "sensorVolume": false,
            "enableRestFul": false,
            "sensorInputs": []
        }
    ],
    "_bridge": {
        "port": 32432,
        "username": "0E:EE:5A:B8:82:90"
    }
}

**Comment by grzegorz914** [comment]
What is Your AVR Model?

try this and please use Config UI X to config plugin, do not make this manually 
```
"platform": "DenonTv",
"devices": [
{
"mqttDebug": false,
"buttons": [],
"masterMute": false,
"mqttAuth": false,
"getInputsFromDevice": false,
"generation": 1,
"inputsDisplayOrder": 0,
"disableLogConnectError": false,
"zoneControl": 0,
"enableDebugMode": false,
"sensorMute": false,
"inputs": [
{
"reference": "SAT/CBL",
"name": "Sky Q",
},
{
"name": "TV Audio",
"reference": "TV"
},
{
"name": "Apple TV",
"reference": "BD"
},
{
"name": "Switch",
"reference": "AUX2"
}
],
"sensorPower": false,
"masterVolume": true,
"enableMqtt": false,
"volumeControl": 2,
"port": 80,
"masterPower": false,
"name": "Denon",
"refreshInterval": 3,
"host": "192.168.0.7",
"sensorInput": false,
"disableLogDeviceInfo": false,
"disableLogInfo": false,
"infoButtonCommand": "MNINF",
"sensorVolume": false,
"enableRestFul": false,
"sensorInputs": []
}
],
"_bridge": {
"port": 32432,
"username": "0E:EE:5A:B8:82:90"
}
}
```

**Comment by tobihoby** [comment]
-denon-tv][39m Loaded homebridge-denon-tv v4.8.1 child bridge successfully

[37m[17.1.2024, 21:00:06] [39mLoaded 0 cached accessories from cachedAccessories.0EEE5AB88290.

[37m[17.1.2024, 21:00:06] [39mHomebridge v1.7.0 (HAP v0.11.1) (homebridge-denon-tv) is running on port 32432.

[37m[17.1.2024, 21:00:07] [39m[36m[homebridge-denon-tv][39m -------- Denon --------

[37m[17.1.2024, 21:00:07] [39m[36m[homebridge-denon-tv][39m Manufacturer: Denon

[37m[17.1.2024, 21:00:07] [39m[36m[homebridge-denon-tv][39m Model: *AVR-X3200W

[37m[17.1.2024, 21:00:07] [39m[36m[homebridge-denon-tv][39m Zones: 2

[37m[17.1.2024, 21:00:07] [39m[36m[homebridge-denon-tv][39m Control: Main Zone

[37m[17.1.2024, 21:00:07] [39m[36m[homebridge-denon-tv][39m Firmware: 0

[37m[17.1.2024, 21:00:07] [39m[36m[homebridge-denon-tv][39m Api version: 300

[37m[17.1.2024, 21:00:07] [39m[36m[homebridge-denon-tv][39m Serialnr: 0005CD626C8D

[37m[17.1.2024, 21:00:07] [39m[36m[homebridge-denon-tv][39m ----------------------------------

[37m[17.1.2024, 21:00:09] [39mDenon 7802 is running on port 46287.

**Comment by grzegorz914** [comment]
Working?

**Comment by SawkeeReemo** [comment]
I just had the same issue… noticed the addition of the old, middle, new AVRs selection. I change to middle for my AVR-X3400H since I wasn’t sure which one to use. It connected again, but all my buttons disappeared, breaking all my automation. …help? 😅

**Comment by tobihoby** [comment]
No

**Comment by grzegorz914** [comment]
Why you not read readme or sample config, buttons property for zone 1 is `buttons` zone 2  `buttonsZ2` zone 3 `buttonsZ3`.  
 Also all mandatory changes are described in update note and in changelog.

**Comment by SawkeeReemo** [comment]
> Why you not read readme or sample config, buttons property for zone 1 is `buttons` zone 2 `buttonsZ2` zone 3 `buttonsZ3`. Also all mandatory changes are described in update note and in changelog.

Yeah, but when you're just looking at Homebridge, and there's an update, you've got text in there telling us what is getting updated. But it seems to be stuck on old text for the last few versions. The warning about needing to recreate buttons was not there. I didn't see it until I came here trying to find a solution, and found it in the release notes. For example, when you did the big overhaul from v3 to v4, there was a nice big warning up there. And I actually stayed back on v3 for a really long time because I didn't have time to figure out the changes and rebuild all my automations again. I was just letting you know that the update text didn't mention this in Homebridge. 

I got things working again on my end, by the way. No bugs to report right now.

**Comment by horsenoggingit** [comment]
@SawkeeReemo has the correct fix. I appreciate this plugin but the notes should mention possible breaking changes.

**Comment by grzegorz914** [comment]
Ok, now the note about mandatory changes are moved to the top of changelog and will be always displayed by update.

**Comment by grzegorz914** [comment]
> No

@tobihoby what is not working now.?

**Comment by tobihoby** [comment]
Unfortunately I can only check this in the afternoon...

**Comment by tobihoby** [comment]
what do you mean with "configure again"?:
Note - after update to 4.8.x all buttons need to be configure again using config UI.
Note - after update to 4.7.x buttons, sensors, volume display type need to be configure again using config UI.
I don´t have buttons or sensors configured. Only inputs and volume display type are configured.

Can this really be the reason why the devices in Apple Home no longer respond?
The log looks correct:

[18.1.2024, 17:53:34] Registering platform 'homebridge-denon-tv.DenonTv'
[18.1.2024, 17:53:34] [homebridge-denon-tv] Loaded homebridge-denon-tv v4.8.3-beta.3 child bridge successfully
[18.1.2024, 17:53:34] Loaded 0 cached accessories from cachedAccessories.0EEE5AB88290.
[18.1.2024, 17:53:34] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-denon-tv) is running on port 32432.
[18.1.2024, 17:53:34] [homebridge-denon-tv] -------- Denon --------
[18.1.2024, 17:53:34] [homebridge-denon-tv] Manufacturer: Denon
[18.1.2024, 17:53:34] [homebridge-denon-tv] Model: *AVR-X3200W
[18.1.2024, 17:53:34] [homebridge-denon-tv] Zones: 2
[18.1.2024, 17:53:34] [homebridge-denon-tv] Control: Main Zone
[18.1.2024, 17:53:34] [homebridge-denon-tv] Firmware: 0
[18.1.2024, 17:53:34] [homebridge-denon-tv] Api version: 300
[18.1.2024, 17:53:34] [homebridge-denon-tv] Serialnr: 0005CD626C8D
[18.1.2024, 17:53:34] [homebridge-denon-tv] ----------------------------------
[18.1.2024, 17:53:36] Denon 7802 is running on port 45613.
[18.1.2024, 17:53:36] Please add [Denon 7802] manually in Home app. Setup Code: 601-70-477
[18.1.2024, 17:53:37] [homebridge-denon-tv] Device: 192.168.0.7 Denon, Power: OFF
[18.1.2024, 17:53:37] [homebridge-denon-tv] Device: 192.168.0.7 Denon, Input Name: Sky Q
[18.1.2024, 17:53:37] [homebridge-denon-tv] Device: 192.168.0.7 Denon, Reference: SAT/CBL
[18.1.2024, 17:53:37] [homebridge-denon-tv] Device: 192.168.0.7 Denon, Volume: -65dB
[18.1.2024, 17:53:37] [homebridge-denon-tv] Device: 192.168.0.7 Denon, Mute: ON
[18.1.2024, 17:53:37] [homebridge-denon-tv] Device: 192.168.0.7 Denon, Volume Control Type: Absolute
[18.1.2024, 17:53:37] [homebridge-denon-tv] Device: 192.168.0.7 Denon, Picture Mode: OFF

**Comment by grzegorz914** [comment]
The log is correct, may be just remove from Home app and add it again.

**Comment by tobihoby** [comment]
I removed the child bridge from Apple Home and also the devices. I can add the bridge from the plugin again, but the devices are not added. am I doing something wrong? :(

**Comment by tobihoby** [comment]
I tried everything...

**Comment by SawkeeReemo** [comment]
> I tried everything...

If that is true, then the problem is on your end and no one here can help you. The answer to the problem is as I stated. Anything more, and it sounds like you have an issue with Homebridge itself. I’ve had issues with Homebridge in the past as well, and I recently just completely reinstalled Homebridge and set everything back up again. Have not had any problems since.

**Comment by grzegorz914** [comment]
If you don see the accessory in home app to add it then try this https://github.com/grzegorz914/homebridge-denon-tv/wiki#troubleshooting

**Comment by tobihoby** [comment]
Thats it:
Remove AccessoryInfo.xxx file which contain Your device data: {"displayName":"AV Receiver"}

Thank you!!
