### ISSUE TITLE
No device showing up in Homekit

### ISSUE THREAD

**Issue by dgauche** [grzegorz914/homebridge-denon-tv#23]
I have several other things working with homebridge, but I have been unable to get my Denon AVR-X2100W to work. I think my config is right and I can see the device showing up in the log files, but it does not show up in Homekit.

Am I just being silly?

**Config:**
```
 "platform": "DenonTv",
            "devices": [
                {
                    "name": "Denon",
                    "host": "192.168.3.159",
                    "port": 80,
                    "zoneControl": 0,
                    "volumeControl": false,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "name": "Media player",
                            "reference": "MPLAY",
                            "type": "SI"
                        },
                        {
                            "name": "DVD",
                            "reference": "DVD",
                            "type": "SI"
                        }
                    ]
                }
            ]
```

**Logs:**
[5/7/2020, 3:35:53 PM] [DenonTv] Device: 192.168.3.159 Denon Main Zone, state: Online
[5/7/2020, 3:35:54 PM] [DenonTv] -------- Denon --------
[5/7/2020, 3:35:54 PM] [DenonTv] Manufacturer: Denon
[5/7/2020, 3:35:54 PM] [DenonTv] Model: *AVR-X2100W
[5/7/2020, 3:35:54 PM] [DenonTv] Zones: 2
[5/7/2020, 3:35:54 PM] [DenonTv] Api version: 0300
[5/7/2020, 3:35:54 PM] [DenonTv] Serialnumber: 0005CD44F2D2
[5/7/2020, 3:35:54 PM] [DenonTv] Firmware: 00
[5/7/2020, 3:35:54 PM] [DenonTv] ----------------------------------

**Comment by grzegorz914** [comment]
Try to rename the Device, Restart homebridge and add It again

**Comment by dgauche** [comment]
Duh, I was silly, reading the logs further, I was told to manually add it, it is there now.  Working.

Thanks!

**Comment by dgauche** [comment]
User error #472637 Please eject faulty user :-)
