### ISSUE TITLE
Error after updating to 4.8.1

### ISSUE THREAD

**Issue by TheTeeDot** [grzegorz914/homebridge-denon-tv#231]
Hi there, since updating the plugin to 4.8.1 I now receive this error in my home bridge status logs:

Device: 192.168.1.31 Living Room Denon AVR-3300w, Info error: TypeError: Cannot read properties of undefined (reading 'value'), reconnect in 15s.

Thanks,
T.

Edit, debug log below:

[1/18/2024, 6:27:33 AM] [DenonTv] Device: 192.168.1.31 Living Room Denon AVR-3300w, debug: Info: {
  "FriendlyName": {
    "value": "Denon AVR-X3300W"
  },
  "Power": {
    "value": "STANDBY"
  },
  "ZonePower": {
    "value": "OFF"
  },
  "RCSourceSelect": {
    "value": "POS"
  },
  "RenameZone": {
    "value": "MAIN ZONE"
  },
  "TopMenuLink": {
    "value": "ON"
  },
  "VideoSelectDisp": {
    "value": "OFF"
  },
  "VideoSelect": {
    "value": ""
  },
  "VideoSelectOnOff": {
    "value": "OFF"
  },
  "VideoSelectLists": {
    "value": [
      {
        "#text": "On",
        "@_index": "ON"
      },
      {
        "#text": "Off",
        "@_index": "OFF"
      },
      {
        "#text": "CBL/SAT",
        "@_index": "SAT/CBL"
      },
      {
        "#text": "DVD",
        "@_index": "DVD"
      },
      {
        "#text": "Blu-ray",
        "@_index": "BD"
      },
      {
        "#text": "Game",
        "@_index": "GAME"
      },
      {
        "#text": "AUX1",
        "@_index": "AUX1"
      },
      {
        "#text": "AUX2",
        "@_index": "AUX2"
      },
      {
        "#text": "Media Player",
        "@_index": "MPLAY"
      }
    ]
  },
  "ECOModeDisp": {
    "value": "ON"
  },
  "ECOMode": {
    "value": ""
  },
  "ECOModeLists": {
    "value": [
      {
        "@_index": "ON",
        "@_table": "ECO : ON",
        "@_param": ""
      },
      {
        "@_index": "OFF",
        "@_table": "ECO : OFF",
        "@_param": ""
      },
      {
        "@_index": "AUTO",
        "@_table": "ECO : AUTO",
        "@_param": ""
      }
    ]
  },
  "AddSourceDisplay": {
    "value": "FALSE"
  },
  "ModelId": {
    "value": 3
  },
  "BrandId": {
    "value": "DENON_MODEL"
  },
  "SalesArea": {
    "value": 4
  },
  "InputFuncSelect": {
    "value": "AUX2"
  },
  "NetFuncSelect": {
    "value": "FAVORITES"
  },
  "selectSurround": {
    "value": "Stereo"
  },
  "VolumeDisplay": {
    "value": "Absolute"
  },
  "MasterVolume": {
    "value": -28
  },
  "Mute": {
    "value": "off"
  },
  "RemoteMaintenance": {
    "value": ""
  },
  "SubwooferDisplay": {
    "value": "FALSE"
  },
  "Zone2VolDisp": {
    "value": "TRUE"
  },
  "SleepOff": {
    "value": "Off"
  }
}
[1/18/2024, 6:27:33 AM] [DenonTv] Device: 192.168.1.31 Living Room Denon AVR-3300w, saved device info: {
  "FriendlyName": {
    "value": "Denon AVR-X3300W"
  },
  "Power": {
    "value": "STANDBY"
  },
  "ZonePower": {
    "value": "OFF"
  },
  "RCSourceSelect": {
    "value": "POS"
  },
  "RenameZone": {
    "value": "MAIN ZONE"
  },
  "TopMenuLink": {
    "value": "ON"
  },
  "VideoSelectDisp": {
    "value": "OFF"
  },
  "VideoSelect": {
    "value": ""
  },
  "VideoSelectOnOff": {
    "value": "OFF"
  },
  "VideoSelectLists": {
    "value": [
      {
        "#text": "On",
        "@_index": "ON"
      },
      {
        "#text": "Off",
        "@_index": "OFF"
      },
      {
        "#text": "CBL/SAT",
        "@_index": "SAT/CBL"
      },
      {
        "#text": "DVD",
        "@_index": "DVD"
      },
      {
        "#text": "Blu-ray",
        "@_index": "BD"
      },
      {
        "#text": "Game",
        "@_index": "GAME"
      },
      {
        "#text": "AUX1",
        "@_index": "AUX1"
      },
      {
        "#text": "AUX2",
        "@_index": "AUX2"
      },
      {
        "#text": "Media Player",
        "@_index": "MPLAY"
      }
    ]
  },
  "ECOModeDisp": {
    "value": "ON"
  },
  "ECOMode": {
    "value": ""
  },
  "ECOModeLists": {
    "value": [
      {
        "@_index": "ON",
        "@_table": "ECO : ON",
        "@_param": ""
      },
      {
        "@_index": "OFF",
        "@_table": "ECO : OFF",
        "@_param": ""
      },
      {
        "@_index": "AUTO",
        "@_table": "ECO : AUTO",
        "@_param": ""
      }
    ]
  },
  "AddSourceDisplay": {
    "value": "FALSE"
  },
  "ModelId": {
    "value": 3
  },
  "BrandId": {
    "value": "DENON_MODEL"
  },
  "SalesArea": {
    "value": 4
  },
  "InputFuncSelect": {
    "value": "AUX2"
  },
  "NetFuncSelect": {
    "value": "FAVORITES"
  },
  "selectSurround": {
    "value": "Stereo"
  },
  "VolumeDisplay": {
    "value": "Absolute"
  },
  "MasterVolume": {
    "value": -28
  },
  "Mute": {
    "value": "off"
  },
  "RemoteMaintenance": {
    "value": ""
  },
  "SubwooferDisplay": {
    "value": "FALSE"
  },
  "Zone2VolDisp": {
    "value": "TRUE"
  },
  "SleepOff": {
    "value": "Off"
  }
}

**Comment by grzegorz914** [comment]
which version was before? are you select correct generation in config?

**Comment by grzegorz914** [comment]
can you try with middle generation

**Comment by TheTeeDot** [comment]
Changed - the error is no longer present and the device is now 'responding' and usable within HomeKit
That appears to have resolved things

Thanks.

**Comment by grzegorz914** [comment]
nice
