### ISSUE TITLE
Cannot add AVR to HomeKit with 4.8.1

### ISSUE THREAD

**Issue by traveling-walker** [grzegorz914/homebridge-denon-tv#232]
I had `No Response` issues following my update to 4.8.1 and deleted the AVR from my HomeKit. Resolved response failure by setting Generation to middle (using model AVR-X3700H). However, am unable to manually re-add the Denon to my Home. Have tried with & without a child bridge. Config below & debug logs attached. Any recommendations would be much appreciated!

[homebridge-denon-tv.log.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/13972176/homebridge-denon-tv.log.txt)

Config:
`{
    "devices": [
        {
            "name": "Denon",
            "host": "10.42.0.146",
            "port": 8080,
            "generation": 1,
            "zoneControl": 0,
            "getInputsFromDevice": true,
            "getFavoritesFromDevice": false,
            "getQuickSmartSelectFromDevice": false,
            "inputsDisplayOrder": 0,
            "sensorPower": false,
            "sensorVolume": false,
            "sensorMute": false,
            "sensorInput": false,
            "enableDebugMode": true,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "masterPower": false,
            "masterVolume": false,
            "masterMute": false,
            "infoButtonCommand": "MNMEN ON",
            "volumeControl": 0,
            "refreshInterval": 5,
            "enableRestFul": false,
            "restFulDebug": false,
            "enableMqtt": false,
            "mqttDebug": false,
            "mqttAuth": false
        }
    ],
    "_bridge": {
        "username": "0E:C3:C8:7E:88:6F",
        "port": 43013
    },
    "platform": "DenonTv"
}`

**Comment by grzegorz914** [comment]
You have all correct, try to change device name in config or https://github.com/grzegorz914/homebridge-denon-tv/wiki#troubleshooting

**Comment by traveling-walker** [comment]
Deleting the appropriate persist files did the trick! Thank you much
