### ISSUE TITLE
Latest version, 4.8.1, created new error

### ISSUE THREAD

**Issue by nebosphere19** [grzegorz914/homebridge-denon-tv#233]
[DenonTv] Device: 10.0.0.40 Denon-AVR-X3800H, Info error: AxiosError: Request failed with status code 403, reconnect in 15s. Repeats over and over.

**Comment by sirkirby** [comment]
@nebosphere19 check out this issue https://github.com/grzegorz914/homebridge-denon-tv/issues/229 to help resolve.

**Comment by nebosphere19** [comment]
Fixed! Thanks @sirkirby !
