### ISSUE TITLE
AVR being reported as on with Homebridge/Child Bridge Restart [v4.8.3]

### ISSUE THREAD

**Issue by SawkeeReemo** [grzegorz914/homebridge-denon-tv#235]
I’ve noticed that after a Homebridge or DenonTv child bridge restart, it’s reporting that my AVE is on to HomeKit when it is not. 
![IMG_7161](https://github.com/grzegorz914/homebridge-denon-tv/assets/60272670/84127340-e130-4d36-99d7-2af598381e7c)
My system is completely off right now. This is affecting my automations. Anyone else seeing this?

**Comment by grzegorz914** [comment]
I’m not observed this behavior.

**Comment by SawkeeReemo** [comment]
Yeah, not sure what the problem was, but it seems to have corrected itself. ¯\\\_(ツ)_/¯ I will close this.
