### ISSUE TITLE
DTS Virtual : X Sound choice in the button drop down menu 

### ISSUE THREAD

**Issue by juani13973** [grzegorz914/homebridge-denon-tv#238]
Dear grzegorz914.
I have a Marantz Cinema 70S and the plug in works perfectly.
I am struggling to find on Sound mode to configure it as a button in your drop down menu.
I would like to activate DTS Virtual : X

<img width="477" alt="image" src="https://github.com/grzegorz914/homebridge-denon-tv/assets/77895272/4b262cce-9050-485d-bf0f-52edd53d80af">

Thanks for letting me know if this option is available. Best Regards and thanks for building this plug in. Super useful !!!

**Comment by grzegorz914** [comment]
Will be added in next update.

**Comment by juani13973** [comment]
Thx !! do you have any timeframe for the next release ?
and I had another quick one : every time I change the config of the plug in (add a new button for exemple), it seems I need to re install everything in the hone up. Delete the bridge, erase it from home bridge and re do everything again. Is that normal ?

Thanks a lot for what you do in the community with this plug in !

**Comment by grzegorz914** [comment]
no, its not normal behaviour, if add new button just save restart and button appear automatically in home app.

**Comment by grzegorz914** [comment]
Can you post the debug log during switch to `DTS Virtual : X`

**Comment by juani13973** [comment]
Hi grzegorz914. Thx for the info on the behavior.
what do you mean by post the debug log during switch to DTS Virtual : x ? (I do not know how to do that).
I saw you updated the plug in. I guess Virtual x is now there. I will upgrade an comment later when I do it. thanks !!!!

**Comment by grzegorz914** [comment]
Go to plugin settings Advanced Settings>>>System>>>Ddebug, enable it and restart plugin. Next switch to `DTS Virtual : X ` and get me the log.

**Comment by juani13973** [comment]
grzegorz914 !! I tried the plug-in 4,9 and all works !!!
thank you very much !! you rock !!
Juan,

**Comment by juani13973** [comment]
you need the log ?  it works well.

**Comment by grzegorz914** [comment]
If all working ok, do not post the log.
