### ISSUE TITLE
can't get input slider to work

### ISSUE THREAD

**Issue by horstepipe** [grzegorz914/homebridge-denon-tv#24]
Hello
I'm getting crazy here I can't figure out why the input selection doesn't work here. Power On/Off and volume control works fine. 
Here's my test config:

`            "devices": [
                {
                    "name": "Receiver",
                    "host": "192.168.0.108",
                    "port": 8080,
                    "zoneControl": 0,
                    "volumeControl": true,
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "name": "GAME",
                            "reference": "GAME",
                            "type": "HDMI",
                            "mode": "SI"
                        },
                        {
                            "name": "MPLAY",
                            "reference": "MPLAY",
                            "type": "HDMI",
                            "mode": "SI"
                        }
                    ]
                }
            ],
            "platform": "DenonTv"
        }
    ]`

Log output looks fine:
`[5/14/2020, 21:41:16] [DenonTv] Device: 192.168.0.108 Receiver Main Zone, set new Input successful: GAME GAME
[5/14/2020, 21:41:21] [DenonTv] Device: 192.168.0.108 Receiver Main Zone, set new Input successful: MPLAY MPLAY`

may I also ask here whether the parameters "type" and "mode" are mandatory? What do they do exactly?

Thank's for the great work!

**Comment by horstepipe** [comment]
sorry, my device is a denon x2400h. Any tips are really appreciated!

**Comment by horstepipe** [comment]
Hmm I tried this plugin
https://github.com/Martvvliet/homebridge-denon-heos

and it works properly there. But I'd prefer to use yours as it integrates the volume control with the other buttons.

**Comment by MichlW** [comment]
My receiver is a AVR-X1500H.
I have the same problem but managed to get it work with the following address/command:

curl -s http://$RECEIVER_IP:8080/goform/formiPhoneAppDirect.xml?SIMPLAY
curl -s http://$RECEIVER_IP:8080/goform/formiPhoneAppDirect.xml?SINET

Maybe the "+ zone +" in line 486 of file index.js is problematic?

axios.get(me.url + '/goform/formiPhoneAppDirect.xml?' + zone + inputReference).then(response => {

Thanks for any info.

**Comment by grzegorz914** [comment]
Fixed in 2.0.8, thanks for test.

**Comment by MichlW** [comment]
I installed 2.0.11 and its working now. Many thanks for that really fast fix.

**Comment by MichlW** [comment]
Now the update of the active input no longer works if you change it via the remote control. Can someone confirm that?

**Comment by MichlW** [comment]
Sorry for the comment above. It works as aspected. Looks like it was a local network issue...
