### ISSUE TITLE
Inputs not showing as configured? Cache problem?

### ISSUE THREAD

**Issue by alegend2k** [grzegorz914/homebridge-denon-tv#240]
Hey there
Im having trouble with inputs on my brand new Marantz Cinema 40 
I configured them as you can see but whatever input a set up it doesn’t show in HomeKit.
It always stays the same….
The inputs are set like I configured them in .json editor…..
I tried to load from device (which works)  and then tried again to set up again on my own but as soon as  I don’t load from device always the same inputs show in HomeKit…

{
    "devices": [
        {
            "name": "Marantz",
            "host": "192.168.178.75",
            "port": 8080,
            "generation": 2,
            "zoneControl": 0,
            "getInputsFromDevice": false,
            "getFavoritesFromDevice": true,
            "getQuickSmartSelectFromDevice": true,
            "inputsDisplayOrder": 0,
            "inputs": [
                {
                    "name": "Radio",
                    "reference": "IRADIO"
                },
                {
                    "name": "APPLE TV",
                    "reference": "MPLAY"
                },
                {
                    "name": "Watch TV",
                    "reference": "TV"
                },
                {
                    "name": "Fernsehen",
                    "reference": "TV"
                }
            ],
            "buttons": [
                {
                    "name": "ATMOS",
                    "reference": "0SPPR 1",
                    "displayType": 1
                },
                {
                    "name": "AURO3D",
                    "reference": "0SPPR 2",
                    "displayType": 1
                },
                {
                    "name": "SmartATV1",
                    "reference": "0MSSMART1",
                    "displayType": 1
                },
                {
                    "name": "SmartLive2",
                    "reference": "0MSSMART2",
                    "displayType": 1
                },
                {
                    "name": "SmartRadio",
                    "reference": "0SMART3",
                    "displayType": 1
                },
                {
                    "name": "DenonLivetv",
                    "reference": "0MSSMART1",
                    "displayType": 1
                },
                {
                    "name": "DenonRadio",
                    "reference": "0SINET",
                    "displayType": 1
                }
            ],
            "sensorPower": true,
            "sensorVolume": false,
            "sensorMute": false,
            "sensorInput": true,
            "sensorInputs": [
                {
                    "name": "AppleTV",
                    "reference": "MPLAY",
                    "displayType": 1
                },
                {
                    "name": "TV",
                    "reference": "TV",
                    "displayType": 1
                }
            ],
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "masterPower": false,
            "masterVolume": true,
            "masterMute": true,
            "volumeControl": 1,
            "refreshInterval": 1,
            "enableRestFul": false,
            "restFulDebug": false,
            "enableMqtt": false,
            "mqttDebug": false,
            "mqttAuth": false
        }
    ],
    "_bridge": {
        "username": "0E:D8:0E:11:52:0E",
        "port": 30322
    },
    "platform": "DenonTv"
}
![IMG_4920](https://github.com/grzegorz914/homebridge-denon-tv/assets/26001704/a6cadc3b-71c6-4ff7-b788-cd6a731dfe89)
![IMG_4919](https://github.com/grzegorz914/homebridge-denon-tv/assets/26001704/69459e74-0a51-497c-acc6-615f86058dc7)

**Comment by grzegorz914** [comment]
`Watch TV` and `Fernsehen` use same reference `TV`, so will always display same name because the name is saved in file based on reference. In your case you have duplicate input configured. In the next release I will add check to prevent load duplicate input from manual configured inputs.

**Comment by grzegorz914** [comment]
Just change it from home app
