### ISSUE TITLE
Problem z State error: AxiosError: timeout of 10000ms exceeded

### ISSUE THREAD

**Issue by grzech1991** [grzegorz914/homebridge-denon-tv#242]
Cześć, przeczytałem wątki na forum.

Zmieniłem czas na 30s - jest to samo. Ustawiłem 60s - to samo.

[1/31/2024, 10:15:49 PM] [DenonTv] Device: 192.168.0.24 Denon x1300w, State error: AxiosError: timeout of 10000ms exceeded, reconnect in 60s.

This is my json file

> {
>     "devices": [
>         {
>             "name": "Denon x1300w",
>             "host": "192.168.0.24",
>             "port": 80,
>             "generation": 1,
>             "zoneControl": 0,
>             "getInputsFromDevice": true,
>             "getFavoritesFromDevice": false,
>             "getQuickSmartSelectFromDevice": false,
>             "inputsDisplayOrder": 0,
>             "buttons": [
>                 {
>                     "name": "Wycisz",
>                     "reference": "0MUON",
>                     "displayType": 2
>                 },
>                 {
>                     "name": "Wyłącz wyciszenie",
>                     "reference": "0MUOFF",
>                     "displayType": 2
>                 },
>                 {
>                     "name": "Apple TV",
>                     "reference": "0SIMPLAY",
>                     "displayType": 2
>                 }
>             ],
>             "sensorPower": true,
>             "sensorVolume": true,
>             "sensorMute": true,
>             "sensorInput": true,
>             "enableDebugMode": false,
>             "disableLogInfo": false,
>             "disableLogDeviceInfo": false,
>             "disableLogConnectError": false,
>             "masterPower": true,
>             "masterVolume": true,
>             "masterMute": true,
>             "infoButtonCommand": "MNMEN ON",
>             "volumeControl": 2,
>             "refreshInterval": 30,
>             "enableRestFul": false,
>             "restFulDebug": false,
>             "enableMqtt": false,
>             "mqttDebug": false,
>             "mqttAuth": false
>         }
>     ],
>     "platform": "DenonTv"
> }
> 

Ampli podłączony po wifi, wersja firmware najnowsza

**Comment by hansw1204** [comment]
Sorry, I don't speak Polish but the issue is solved. It seems that the network connection of my Marantz SR7007 was compromised. After fixing that all is working again
Thank you!

From: Grzegorz ***@***.***>
Date: Wednesday, January 31, 2024 at 16:18
To: grzegorz914/homebridge-denon-tv ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [grzegorz914/homebridge-denon-tv] Problem z State error: AxiosError: timeout of 10000ms exceeded (Issue #242)

Cześć, przeczytałem wątki na forum.

Zmieniłem czas na 30s - jest to samo. Ustawiłem 60s - to samo.

[1/31/2024, 10:15:49 PM] [DenonTv] Device: 192.168.0.24 Denon x1300w, State error: AxiosError: timeout of 10000ms exceeded, reconnect in 60s.

Ampli podłączony po wifi, wersja firmware najnowsza

**Comment by grzegorz914** [comment]
@grzech1991 just power cycle your AVR

**Comment by grzech1991** [comment]
@hansw1204 don't work i have arris from UPC and i have three options:
- types of wi-fi
- channel width
- channel

Changing the channel width did not help.

@grzegorz914 I read the threads before I wrote with this error and unplugging what reboot the receiver does not help. After restarting the receiver as if the connection problem is after 60s instead of 30s, then it lasts intermittently about 1 minute. I understand that it is the fault of the receiver or the network?

**Comment by grzegorz914** [comment]
Connect AVR with LAN cable and check again.

**Comment by grzech1991** [comment]
You have right, after connect to cable, i don't have any errors... Thank you @grzegorz914
