### ISSUE TITLE
Receiver not showing up after 4.9.9

### ISSUE THREAD

**Issue by my-axel** [grzegorz914/homebridge-denon-tv#243]
I've recently updated to 4.9.9. I think I was on 4.8.0 or 4.9.0 before. I'm not sure, but I update quite often. I found the following message in the logs:
```
[2/2/2024, 9:16:33 PM] [homebridge-denon-tv] Device: 192.168.0.38 Verstärker, Info error: TypeError: Cannot read properties of undefined (reading 'value'), reconnect in 15s.
```
As found in another issue, I've changed the generation to 2013-2022. This fixed the issue and the following message appeared:
```
[2/2/2024, 9:19:07 PM] [homebridge-denon-tv] -------- Verstärker --------
[2/2/2024, 9:19:07 PM] [homebridge-denon-tv] Manufacturer: Denon
[2/2/2024, 9:19:07 PM] [homebridge-denon-tv] Model: *AVR-X1200W
[2/2/2024, 9:19:07 PM] [homebridge-denon-tv] Zones: 2
[2/2/2024, 9:19:07 PM] [homebridge-denon-tv] Control: Main Zone
[2/2/2024, 9:19:07 PM] [homebridge-denon-tv] Firmware: 0
[2/2/2024, 9:19:07 PM] [homebridge-denon-tv] Api version: 300
[2/2/2024, 9:19:07 PM] [homebridge-denon-tv] Serialnr: xxxxxxxxxxxxx
[2/2/2024, 9:19:07 PM] [homebridge-denon-tv] ----------------------------------
```

Changes on the receiver are nearly directly visible in the HomeBridge logs. Then I've looked for the receiver in the Home App and it didn't show up anymore. I've tried the usual things:
- Restarting HomeBridge
- Removing the device from Home and trying to re-add it (but it doesn't show up)
- Deactivating & reactivating the Child Bridge for the plug-in
- Deactivate the Child Bridge and trying to add it in Home directly (but it doesn't show up)
- Removing the Child Bridge from Home and re-adding it
- Renaming the receiver in HomeBridge and repeat the steps above

Nothing seems to work. Adding the Child Bridge to Home does work without a problem. But the receiver does not show up. I've looked at the room, where the child bridge was added and I've looked for a "Standard room". But it's nowhere to be found.

My next step would be to save the config, remove the plug-in, reinstall the plug-in add the config again and hope that it works. Is this my only option right now or did I miss something obvious?

**Comment by grzegorz914** [comment]
Try this: https://github.com/grzegorz914/homebridge-denon-tv/wiki#troubleshooting

**Comment by my-axel** [comment]
Thanks for the tip! That was exactly what I was looking for. Shame on me for not looking deeper into the documentation.
Unfortunately, it did not help. When remove the files, I can see this in the logs:
```[2/3/2024, 1:56:47 PM] Loaded 0 cached accessories from cachedAccessories.0EDCFC156AB6.```

But I still can't add it in Home. I've also removed the two files, removed the bridge from Home, restarted Homebridge completely, re-added the bridge (which worked fine) but then I can't find or add the receiver itself.
Any other idea? Otherwise I'm simply removing the plugin and start from scratch.

**Comment by grzegorz914** [comment]
The log is correct, try to remove special character from name `ä`

**Comment by my-axel** [comment]
Removed the `ä` and tried again to remove the two cache files. Again with no luck.

**Comment by grzegorz914** [comment]
enable debug mode in plugin settings and get me the log please

**Comment by grzegorz914** [comment]
Restart whole homebridge after remove the files, not the child bridge only.

**Comment by grzegorz914** [comment]
One more tip: 
go to Homebridge Settings >> Disconnect bridge/camera/TV/Externall accessories then remove the AVR child bridge and the accessory, restart homebridge and try to add it again.

**Comment by my-axel** [comment]
> One more tip:
> go to Homebridge Settings >> Reset Options >> Disconnect bridge/camera/TV/Externall accessories then remove the AVR child bridge and the accessory, restart homebridge and try to add it again.

Yes! That did the trick. Thank you!
Just for the record, I tried restarting the child bridge and HomeBridge. This setting in HomeBridge worked like a charm. There were a lot of old deprecated bridges in the list. Seems like HomeBridge caches a lot of stuff. I guess removing and installing the plugin again, would have not worked.

**Comment by Caleb79** [comment]
Hi.
I cannot see the device in Homekit as well. I tried all the proposed solutions mentioned here but without success.
The device and the buttons are shown in Homebridge but nothing except the child-homebridge in Homekit. The child-homebridge also have no devices in Homekit (others have).

What else can I do?
