### ISSUE TITLE
GAME Input using incorrect input name in config 

### ISSUE THREAD

**Issue by an-ghinid** [grzegorz914/homebridge-denon-tv#244]
I’m using the latest version of the plugin  with an  X2800H and was having issues having my input in HomeKit “stay selected” as  an active input. If I switched to my GAME input it would change on the AVR but in HomeKit incorrect display my previously selected input as the current active one. 

Dug into the issue and it looks like adding “GAME” as a custom input from the dropdown sets the reference to “GAME” where it should be “GAME1”.

Manually changing the JSON fixes this for me but wanted to give a heads up. 

Thanks for the fantastic plugin!

**Comment by grzegorz914** [comment]
Fixed/Added in latest update
