### ISSUE TITLE
New error message

### ISSUE THREAD

**Issue by Cesco117** [grzegorz914/homebridge-denon-tv#245]
Hi,

From a day to another, my Marantz AV Receiver (SR5011) is not available on home bridge.
Everything is ok through Safari (http://192.168.0.107/SETUP/f_home.asp) and through the Marantz iOS app.
I tried to install a new home bridge instance to troubleshoot, and I have the same error.
Do you have any ideas ?
Thanks a lot !

The error message is the one below :

Device: 192.168.0.107 Marantz SR5011, Info error: AxiosError: maxContentLength size of -1 exceeded, reconnect in 15s.

**Comment by docgould3** [comment]
I am using HomeKit through Hoobs. I updated my Denon plugin and am now getting the following error:
2/18/2024, 6:13:03 PMDenon AVR bridgeDenonTvERRORDevice: 192.168.4.30 Movie Room AVR, Info error: AxiosError: Request failed with status code 403, reconnect in 15s.

Hoobs 4.3.1
Node version 16.20.2
Hombridge version 1.7.0
Denon Tv 4.9.14
Denon AVR-X3700H
