### ISSUE TITLE
What happened to releases post-4.9? What's really the latest?

### ISSUE THREAD

**Issue by mishakim** [grzegorz914/homebridge-denon-tv#247]
Homebridge is telling me to update from 4.9.10 to 4.9.0, which is three weeks old, and I'm not seeing any of the 4.9.x releases here for x>0.  What happened? Is there a rollback? Should I "update"

**Comment by grzegorz914** [comment]
4.9.14 is the latest 
![Zrzut ekranu 2024-02-17 o 19 05 37](https://github.com/grzegorz914/homebridge-denon-tv/assets/28867813/02b428ec-4272-4110-8c7b-bdf4bd6f328e)

**Comment by mishakim** [comment]
Thanks - found that though manual version selection. But see screenshots, Homebridge is advertising 4.9.0, and GitHub isn't showing anything past that, so it seems like something is misconfigured. Once I updated to 4.9.14 Homebridge is not longer pushing the 4.9.0 update.
![github](https://github.com/grzegorz914/homebridge-denon-tv/assets/15706027/4b651a02-1d08-4657-abff-0b654dd9cca2)
![plugin update](https://github.com/grzegorz914/homebridge-denon-tv/assets/15706027/bffde094-c3a7-4e4d-b106-2d45b806ec47)

**Comment by grzegorz914** [comment]
may be some mistake on npm side

**Comment by grzegorz914** [comment]
Ah this is just changelog not updated, not the plugin itself.
