### ISSUE TITLE
Plugin not working with AVR-X2000 after update

### ISSUE THREAD

**Issue by Joaav** [grzegorz914/homebridge-denon-tv#248]
Hi,

After newest update I get this code:

[2/22/2024, 8:18:36 AM] [homebridge-denon-tv] Device: 192.168.0.xxx Denon AVR-X2000, Info error: TypeError: Cannot read properties of undefined (reading 'value'), reconnect in 15s.

Any ideas how to fix it?

**Comment by grzegorz914** [comment]
Get the debug log..

**Comment by Joaav** [comment]
It was working flawlessly before update. IP address is fine when I have changed it to a wrong one i got different error.

This is the log I am getting with correct IP and port.

[2/22/2024, 8:30:47 AM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-denon-tv) is running on port 51884.
[2/22/2024, 8:30:47 AM] [homebridge-denon-tv] Name: undefined, host: undefined, port: undefined, zone: OK, in config wrong or missing.
[2/22/2024, 8:30:47 AM] [homebridge-denon-tv] Device: 192.168.0.53 Denon AVR-X2000, Info error: TypeError: Cannot read properties of undefined (reading 'value'), reconnect in 15s.

**Comment by grzegorz914** [comment]
As you see `Name: undefined, host: undefined, port: undefined ` this data in config is undefined, please set correct value.

**Comment by Joaav** [comment]
<img width="743" alt="Zrzut ekranu 2024-02-22 o 08 44 15" src="https://github.com/grzegorz914/homebridge-denon-tv/assets/148697234/a6f2cf50-3a2a-4f4e-90c0-8b2facf2540d">

But it is set!

**Comment by grzegorz914** [comment]
You have configured also other `device`

**Comment by Joaav** [comment]
I removed the other device, problem persists. I cannot add denon to homekit after removing it.

[2/22/2024, 12:15:45 PM] [homebridge-denon-tv] Device: 192.168.0.53 Denon AVR-X2000, Info error: TypeError: Cannot read properties of undefined (reading 'value'), reconnect in 15s.

**Comment by grzegorz914** [comment]
Get the debug please. And the config.json.

**Comment by Joaav** [comment]
There is nothing else in the debug

{
    "devices": [
        {
            "name": "Denon AVR-X2000",
            "host": "192.168.0.53",
            "port": 80,
            "generation": 0,
            "zoneControl": 0,
            "getInputsFromDevice": false,
            "getFavoritesFromDevice": false,
            "getQuickSmartSelectFromDevice": true,
            "inputsDisplayOrder": 0,
            "inputs": [
                {
                    "name": "TV AUDIO",
                    "reference": "TV"
                },
                {
                    "name": "TUNER",
                    "reference": "TUNER"
                },
                {
                    "name": "AIRPLAY",
                    "reference": "NET"
                }
            ],
            "buttons": [
                {
                    "name": "TUNER UP",
                    "reference": "0TPANUP",
                    "displayType": 1
                },
                {
                    "name": "TUNER DOWN",
                    "reference": "0TPANDOWN",
                    "displayType": 1
                }
            ],
            "sensorPower": false,
            "sensorVolume": false,
            "sensorMute": false,
            "sensorInput": false,
            "sensorInputs": [
                {
                    "name": "Power",
                    "reference": "masterPower",
                    "displayType": 2
                }
            ],
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "masterPower": false,
            "masterVolume": true,
            "masterMute": true,
            "volumeControl": 1,
            "refreshInterval": 5,
            "enableRestFul": false,
            "restFulDebug": false,
            "enableMqtt": false,
            "mqttDebug": false,
            "mqttAuth": false
        }
    ],
    "_bridge": {
        "username": "0E:13:6E:1D:C2:5D",
        "port": 51884
    },
    "platform": "DenonTv"
}

**Comment by kaskoo** [comment]
Hi, I have the exact same issue with a SR7007 Marantz.

**Comment by grzegorz914** [comment]
@kaskoo try to change to generation 1 and please get the debug log too.

**Comment by kaskoo** [comment]
My bad, I thought my AVR was older. 
With the right generation, I have no error. 
Thanks a lot for your dev !
