### ISSUE TITLE
Zone 2: auto-start, or create separate on/off switch?

### ISSUE THREAD

**Issue by robhester** [grzegorz914/homebridge-denon-tv#25]
Is there a way to:
(a) auto-start Main Zone + Zone 2 (together), or
(b) create a on/off switch for Zone 2?

I've tried reading the javascript for clues, but am not a programmer :( Thanks for creating such a wonderful plugin!

**Comment by grzegorz914** [comment]
OK,
nice idea in 2.1.0 added master power control (if enabled power button switch ON/OFF all zones).
Please make update and test.

thanks
