### ISSUE TITLE
Ports required open in firewall?

### ISSUE THREAD

**Issue by SawkeeReemo** [grzegorz914/homebridge-denon-tv#250]
By chance, do you know what ports need to be opened in a firewall for this plugin to work? I’m using Homebridge in a docker container on an Ubuntu system that is running UFW. I’ve looked in the configs for each plugin I use and opened them, but for some reason this is the only one I can’t figure out. Any idea?

**Comment by grzegorz914** [comment]
No need to open any port, the plugin connect to AVR over 80 or 8080 port

**Comment by SawkeeReemo** [comment]
I think that did it. I was using reverse proxy to access my Homebridge container, and opening ports 80 & 443 seemed to solve it. Figured I'd confirm here for others who may be googling. Thanks again for all your work on this. Probably my favorite plugin for Homebridge!
