### ISSUE TITLE
Denon plugin

### ISSUE THREAD

**Issue by AndrewAdventure** [grzegorz914/homebridge-denon-tv#252]
Witam. Używam pluginu od wieków, ale po ostatnich updatach mój denon zniknął z home app i nie mogę go dodać ponownie. Próbowałem juz wszystkiego, proszę o pomoc. 
Pozdrawiam Andrzej.

**Comment by grzegorz914** [comment]
Get the debug log, and config

**Comment by AndrewAdventure** [comment]
Hi,
Thanks for quick reply and please see attached. 
[config.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/14628480/config.txt)
[homebridge-denon-tv.log.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/14628481/homebridge-denon-tv.log.txt)

Thanks

**Comment by grzegorz914** [comment]
Try this: https://github.com/grzegorz914/homebridge-denon-tv/wiki#troubleshooting

**Comment by AndrewAdventure** [comment]
Hi. 
Thanks, will try it later on.

**Comment by AndrewAdventure** [comment]
Hi. All sorted thanks!
