### ISSUE TITLE
socket hang up error in log

### ISSUE THREAD

**Issue by roger-richards** [grzegorz914/homebridge-denon-tv#254]
first time setup, does not show as any accessories.  Log has this error:
` [DenonTv] Device: 192.168.50.220 Main AV, Info error: Error: socket hang up, reconnect in 15s.`
I have double checked the IP and port address (works in a browser to view the Denon receivers' network control page.
My receiver is: Denon AVR-X3600H

Any suggestions?

 [DenonTv] Device: 192.168.50.220 Main AV, did finish launching.
 [DenonTv] Device: 192.168.50.220 Main AV, Config: {
  "name": "Main AV",
  "host": "192.168.50.220",
  "port": 10443,
  "generation": 1,
  "zoneControl": 0,
  "getInputsFromDevice": false,
  "getFavoritesFromDevice": false,
  "getQuickSmartSelectFromDevice": false,
  "inputsDisplayOrder": 0,
  "sensorPower": true,
  "sensorVolume": false,
  "sensorMute": false,
  "sensorInput": false,
  "enableDebugMode": true,
  "disableLogInfo": false,
  "disableLogDeviceInfo": false,
  "disableLogConnectError": false,
  "masterPower": false,
  "masterVolume": false,
  "masterMute": false,
  "volumeControl": 0,
  "refreshInterval": 5,
  "enableRestFul": false,
  "restFulDebug": false,
  "enableMqtt": false,
  "mqttDebug": false,
  "mqttAuth": false
}
...
 [DenonTv] Device: 192.168.50.220 Main AV, Info error: Error: socket hang up, reconnect in 15s.

**Comment by grzegorz914** [comment]
May be extend refresh time or just power cycle AVR or reset AVR Processor.

**Comment by roger-richards** [comment]
power cycled. / set refreshInterval: 10
same error

**Comment by grzegorz914** [comment]
Please get the debug log

**Comment by roger-richards** [comment]
was mistaken about the port, thought it should be 10443 but is 8080 in my case.  Sorry to bother.
