### ISSUE TITLE
M-CR611 favorites

### ISSUE THREAD

**Issue by MrBrownFromLa** [grzegorz914/homebridge-denon-tv#256]
Hello grzegorz914!

I've got 8 radio station in my favorites, but I can't call them...
The "load inputs" function works perfectly (I see all of the inputs of my MCR611 in the wheel selector in Home app) but if I check "load favorites" option too, I've got the error: Device: 192.168.1.30 M-CR611, Info error: TypeError: deviceFavorites is not iterable, reconnect in 15s.
In the old version of your plug I used to create custom input sending "SI FVxx" to call my favorites and it was working, but now the plugin won't let me do that.
Am I missing something? Could you help me?
Thanks!

[homebridge.log.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/15050963/homebridge.log.txt)
[M-CR511_611_PROTOCOL_Ver1_0_0.pdf](https://github.com/grzegorz914/homebridge-denon-tv/files/15050969/M-CR511_611_PROTOCOL_Ver1_0_0.pdf)

Here is my json config:
{
    "devices": [
        {
            "name": "M-CR611",
            "host": "192.168.1.30",
            "port": 80,
            "generation": 1,
            "zoneControl": 0,
            "getInputsFromDevice": true,
            "getFavoritesFromDevice": false,
            "getQuickSmartSelectFromDevice": false,
            "inputsDisplayOrder": 0,
            "inputs": [
                {
                    "name": "AppleTV",
                    "reference": "DIGITALIN1"
                },
                {
                    "name": "France Inter",
                    "reference": " FV01"
                },
                {
                    "name": "FIP",
                    "reference": " FV02"
                },
                {
                    "name": "France Culture",
                    "reference": " FV03"
                },
                {
                    "name": "France Musique",
                    "reference": " FV04"
                },
                {
                    "name": "Le Djam",
                    "reference": " FV05"
                },
                {
                    "name": "Radio Meuh",
                    "reference": " FV06"
                },
                {
                    "name": "Le Gri-Gri",
                    "reference": " FV07"
                },
                {
                    "name": "Radio Nova",
                    "reference": " FV08"
                }
            ],
            "sensorPower": false,
            "sensorVolume": false,
            "sensorMute": false,
            "sensorInput": false,
            "sensorInputs": [
                {
                    "name": "AppleTV",
                    "reference": "DIGITALIN1",
                    "displayType": 3
                },
                {
                    "name": "iRadio",
                    "reference": "NET",
                    "displayType": 3
                }
            ],
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "masterPower": true,
            "masterVolume": false,
            "masterMute": false,
            "infoButtonCommand": "MNINF",
            "volumeControl": 2,
            "refreshInterval": 1,
            "enableRestFul": false,
            "restFulDebug": false,
            "enableMqtt": false,
            "mqttDebug": false,
            "mqttAuth": false
        }
    ],
    "_bridge": {
        "username": "0E:C9:EA:A2:75:35",
        "port": 52107
    },
    "platform": "DenonTv"
}

**Comment by MrBrownFromLa** [comment]
Hello again, thanks for your quick reply!
It now start with "load input"+"load favorite" but I still don't see my favorites in the input list.
![IMG_3159DA8B58DD-1](https://github.com/grzegorz914/homebridge-denon-tv/assets/47503944/3c75a2e3-80bd-45b9-bc6b-821cb84960e5)
Input show if I use my custom input but it won't call the favorite. My MCR-611 use the command "SI FVxx" (with a space between SI and FV, and xx is the number of the favorite to call.
In the log I see you use ZM for favorites, perhaps the problem come from that but not sure... I don't have your programming skills even if I try to understand it?
And thanks so much for the volume it work perfectly!!!
Hope you can help me.
See U!

**Comment by grzegorz914** [comment]
I don’t see any configured favorites in your log.

**Comment by MrBrownFromLa** [comment]
I got 8 radio station memorized from 1 to 8 but I think the plugin don't see them...

**Comment by MrBrownFromLa** [comment]
Could you add a favorite call for Marantz with the function "SI FV" so I can create my custom inputs?
