### ISSUE TITLE
MCR611 favorites

### ISSUE THREAD

**Issue by MrBrownFromLa** [grzegorz914/homebridge-denon-tv#258]
Hello again, thanks for your quick reply!
It now start with "load input"+"load favorite" but I still don't see my favorites in the input list.
![IMG_3159DA8B58DD-1](https://github.com/grzegorz914/homebridge-denon-tv/assets/47503944/3c75a2e3-80bd-45b9-bc6b-821cb84960e5)
Input show if I use my custom input but it won't call the favorite. My MCR-611 use the command "SI FVxx" (with a space between SI and FV, and xx is the number of the favorite to call.
In the log I see you use ZM for favorites, perhaps the problem come from that but not sure... I don't have your programming skills even if I try to understand it?
And thanks so much for the volume it work perfectly!!!
Hope you can help me.
See U!

[homebridge.log.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/15051361/homebridge.log.txt)

_Originally posted by @MrBrownFromLa in https://github.com/grzegorz914/homebridge-denon-tv/issues/256#issuecomment-2067984637_

**Comment by grzegorz914** [comment]
try 4.13.1-beta.0 and let me know, I have added FAV 1 to 20 in inputs list

**Comment by MrBrownFromLa** [comment]
I've tried it, custom inputs with "FAVORITE x (Marantz Only)" input don't show up
![IMG_F2DDFA1938CD-1](https://github.com/grzegorz914/homebridge-denon-tv/assets/47503944/cb5cb4bb-eecf-4f44-a7f2-c02cf4ec0376)
In earlier version of your plugin, I use to create custom item like this for my MCR611 and it was working well:
    "name": "France Inter",
    "reference": " 01",
    "mode": "FV"
I don't know if it can help you figure out why it's not working anymore.
Thanks again for all the time spend on solving my problem!

**Comment by grzegorz914** [comment]
try beta.2

**Comment by MrBrownFromLa** [comment]
custom inputs show up now
![IMG_CF01D0CDEFA7-1](https://github.com/grzegorz914/homebridge-denon-tv/assets/47503944/22c81517-c817-45d5-a359-f3250375060a)
but it won't launch the favorite on the amp...
Also, I notice that if I send this command http://192.168.1.30:80/goform/formiPhoneAppDirect.xml?FV%2001 it launch Favorite 1 perhaps it could help you find the problem.

**Comment by grzegorz914** [comment]
try beta.3

**Comment by grzegorz914** [comment]
buttons are also added
