### ISSUE TITLE
Refresh interval 500ms

### ISSUE THREAD

**Issue by roma0803** [grzegorz914/homebridge-denon-tv#259]
FYI: the plugin works fine with a Marantz SR8015. Thanks for your work on this plugin!

A request: Is it possible to set the refresh rate to 500ms? This will hopefully give a slightly faster refresh of the current status in Homekit.

**Comment by grzegorz914** [comment]
Right now min. Is 1sec, are you sure you need faster refresh time,?

**Comment by roma0803** [comment]
I hope this will achieve faster update of the current status in HomeKit. That refresh takes longer than with a plugin I used before. I prefer using your pugin, it offers more and nicer functions.
I don't have the technical background to judge whether this is really the solution for this.

**Comment by grzegorz914** [comment]
Will add this possibility in the next update

**Comment by roma0803** [comment]
I appreciate that, thank you.

**Comment by grzegorz914** [comment]
Added in 4.13.3

**Comment by roma0803** [comment]
He seems to react a little more responsive. Could be perception, it's only half a second, but still. 
Again, I appreciate your work in this and thanks for the quick fix Grzegorz
