### ISSUE TITLE
Zone2 Quick Select Reference is no longer working

### ISSUE THREAD

**Issue by doub09** [grzegorz914/homebridge-denon-tv#264]
Zone2 quick select reference seems to be invalid.  Confirmed this was working in 4.12

**Comment by grzegorz914** [comment]
Any debug?

**Comment by doub09** [comment]
the Reference in the log for 4.13.10 shows "QUICK1" instead of "Z2QUICK1" which I found in the Denon Control Protocol.xlsx. I downgraded to 4.12.3 and found reference does show "Z2QUICK1". I tried adjusting the config manually with "Z2QUICK1", but it was showing "2QUICK1" in the logs. 

4.13.10 - Log:
[5/22/2024, 10:56:38 AM] [homebridge-denon-tv] Device: xxx.xxx.xxx.xxx Speakers, set Button Name: Music, Reference: QUICK1

4.12.3 - Log:
[5/22/2024, 1:06:20 PM] [homebridge-denon-tv] Device: xxx.xxx.xxx.xxx Speakers, set Button Name: Music, Reference: Z2QUICK1

**Comment by grzegorz914** [comment]
Ok, I will look in to this.

**Comment by doub09** [comment]
Latest beta still not functioning as expected. Debug log attached. 

For what it is worth, I changed json config from "1QUICK1" to "1Z2QUICK1" and quick select works. 

[DenonTV_debug_1 .txt](https://github.com/grzegorz914/homebridge-denon-tv/files/15484914/DenonTV_debug_1.txt)

**Comment by grzegorz914** [comment]
I don’t se in the log that you try to set quick select.

**Comment by doub09** [comment]
Full log
[DenonTV_debug_2.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/15485366/DenonTV_debug_2.txt)

**Comment by grzegorz914** [comment]
OK, try beta.3. and let me know

**Comment by doub09** [comment]
Working now, thank you. And thanks for such a useful plugin!
