### ISSUE TITLE
default port is important to change

### ISSUE THREAD

**Issue by phenomeus** [grzegorz914/homebridge-denon-tv#27]
thanks for you plugin, I would suggest to edit your help page and state that its important to check what port the different AV models are using. the default port 8080 is not working 

for my X3300 I had to switch to port 80

**Comment by grzegorz914** [comment]
under .1 
https://github.com/grzegorz914/homebridge-denon-tv#configuration

**Comment by dgauche** [comment]
I also had to set my port to port 80 on my Denon X2100w

**Comment by phenomeus** [comment]
sorry I missed it. good work. keep it up
