### ISSUE TITLE
Custom Input Names Not Working

### ISSUE THREAD

**Issue by PappyChappy1** [grzegorz914/homebridge-denon-tv#270]
When I apply my own name to an input, it does not display the custom name in the Home app. For example I have AUX 1 named "Apple TV" but in the Home app is still shows just "AUX 1".  I've tried restarting Homebridge but it doesn't flow through.  Do I need to remove and re-add the device?

**Comment by grzegorz914** [comment]
try 4.13.28 and let me know

**Comment by PappyChappy1** [comment]
I’ve updated to the newest version of the plugin and the names still aren’t showing - do I need to delete and re-add? Trying to avoid if possible since I have automations set up but I can if that is required

**Comment by grzegorz914** [comment]
Can You be more specific, what is Custom Name in your case, and how do you configure it.

**Comment by grzegorz914** [comment]
The Inputs names can be changes direct in Home app, open Your Receiver tile then press gear icon and scroll down..

**Comment by PappyChappy1** [comment]
Yes that worked. Thank youOn Aug 4, 2024, at 10:13 AM, Grzegorz ***@***.***> wrote:﻿
The Inputs names can be changes direct in Home app, open Your Receiver tile then press gear icon and scroll down..
