### ISSUE TITLE
Error after upgrading to lates version

### ISSUE THREAD

**Issue by madegn** [grzegorz914/homebridge-denon-tv#276]
After upgrading I get the following error:   

9/2/2024, 12:48:00 PMDenon Tv BridgeDenonTvWARNINGDevice: 192.168.1.148 Denon AV, unknoen zone: 0. 

In the past I've had to roll back to version  4.3.28 and this would resolve the problem. I like to get this resolved once and for all so that I can continue to be on current version

**Comment by grzegorz914** [comment]
zone `0.` change to `0`

**Comment by madegn** [comment]
> zone `0.` change to `0`

Unfortunately that did not make a difference.

**Comment by grzegorz914** [comment]
Post the config.jaon please

**Comment by madegn** [comment]
{
    "accessories": [],
    "platforms": [
        {
            "platform": "DenonTv",
            "devices": [
                {
                    "name": "Denon-AVR",
                    "host": "192.168.1.148",
                    "port": 8080,
                    "zoneControl": 0,
                    "volumeControl": 0,
                    "inputs": [
                        {
                            "name": "Xfinity",
                            "reference": "SAT/CBL",
                            "mode": "SI"
                        },
                        {
                            "name": "Stream",
                            "reference": "DVD",
                            "mode": "SI"
                        },
                        {
                            "name": "Blu-Ray",
                            "reference": "BD",
                            "mode": "SI"
                        }
                    ]
                }
            ]
        }
    ]
}

**Comment by madegn** [comment]
> In your config are missing some required properties like generation

Im using Hoobs for configuration.  So Hoobs generated the config.jaon file from the Hoobs UI interface. So I'm unsure of what the Config file needs to have other that what Hoobs generated.

**Comment by grzegorz914** [comment]
Why you not install Config UI X

**Comment by grzegorz914** [comment]
You can just use sample config, adapt your purpose

**Comment by grzegorz914** [comment]
```
"devices": [
                {
                    "name": "AV Main Zone",
                    "host": "192.168.1.5",
                    "port": 8080,
                    "generation": 1,
                    "zoneControl": 0,
                    "getInputsFromDevice": false,
                    "getFavoritesFromDevice": false,
                    "getQuickSmartSelectFromDevice": false,
                    "inputsDisplayOrder": 0,
                    "inputs": [
                        {
                            "name": "Xbox One",
                            "reference": "GAME"
                        },
                        {
                            "name": "Television",
                            "reference": "TV"
                        }
                    ],
                    "sensorPower": false,
                    "sensorVolume": false,
                    "sensorMute": false,
                    "sensorInput": false,
                    "infoButtonCommand": "MNINF",
                    "masterPower": false,
                    "volumeControlNamePrefix": false,
                    "volumeControlName": "Volume",
                    "volumeControl": 0,
                    "volumeMax": 0,
                    "refreshInterval": 5,
                    "enableDebugMode": false,
                    "disableLogInfo": false,
                    "disableLogDeviceInfo": false,
                    "disableLogConnectError": false,
                    "enableRestFul": false,
                    "restFulPort": 3000,
                    "restFulDebug": false,
                    "enableMqtt": false,
                    "mqttDebug": false,
                    "mqttHost": "192.168.1.33",
                    "mqttPort": 1883,
                    "mqttPrefix": "home/denon",
                    "mqttAuth": false,
                    "mqttUser": "user",
                    "mqttPass": "password"
             ]
```

**Comment by madegn** [comment]
> ```
> "devices": [
>                 {
>                     "name": "AV Main Zone",
>                     "host": "192.168.1.5",
>                     "port": 8080,
>                     "generation": 1,
>                     "zoneControl": 0,
>                     "getInputsFromDevice": false,
>                     "getFavoritesFromDevice": false,
>                     "getQuickSmartSelectFromDevice": false,
>                     "inputsDisplayOrder": 0,
>                     "inputs": [
>                         {
>                             "name": "Xbox One",
>                             "reference": "GAME"
>                         },
>                         {
>                             "name": "Television",
>                             "reference": "TV"
>                         }
>                     ],
>                     "sensorPower": false,
>                     "sensorVolume": false,
>                     "sensorMute": false,
>                     "sensorInput": false,
>                     "infoButtonCommand": "MNINF",
>                     "masterPower": false,
>                     "volumeControlNamePrefix": false,
>                     "volumeControlName": "Volume",
>                     "volumeControl": 0,
>                     "volumeMax": 0,
>                     "refreshInterval": 5,
>                     "enableDebugMode": false,
>                     "disableLogInfo": false,
>                     "disableLogDeviceInfo": false,
>                     "disableLogConnectError": false,
>                     "enableRestFul": false,
>                     "restFulPort": 3000,
>                     "restFulDebug": false,
>                     "enableMqtt": false,
>                     "mqttDebug": false,
>                     "mqttHost": "192.168.1.33",
>                     "mqttPort": 1883,
>                     "mqttPrefix": "home/denon",
>                     "mqttAuth": false,
>                     "mqttUser": "user",
>                     "mqttPass": "password"
>              ]
> ```

Thanks
