### ISSUE TITLE
Homebridge reports latest plug-in version is 5.1.4.

### ISSUE THREAD

**Issue by WJKramer** [grzegorz914/homebridge-denon-tv#277]
But this repo says 5.1.0 is the latest so no update occurs.

**Comment by roma0803** [comment]
Update button is in my case available, but it does not execute an update proces. My current version 5.1.1.
<img width="698" alt="Scherm­afbeelding 2024-09-04 om 09 12 20" src="https://github.com/user-attachments/assets/3b81d982-a654-40df-beea-b2ed7e1b5691">

**Comment by grzegorz914** [comment]
5.1.4 is the latest

**Comment by grzegorz914** [comment]
Try remove the plugin without remove config and installl again

**Comment by roma0803** [comment]
> Try remove the plugin without remove config and installl it again

That worked. Thanks!
