### ISSUE TITLE
Multi Zone use case

### ISSUE THREAD

**Issue by dgauche** [grzegorz914/homebridge-denon-tv#28]
My Setup is as follows:

**Equipment:**
Denon AVR x2100w
Apple TV
Optoma Projector
iPhone / iPad (Airplay Source)

**Rooms:**
Cinema Room: 5.1 speaker setup with Apple TV playing Video through the AVR to a Projector
Patio: 2 Chanels from AVR

**Use Case**
I want to have the kids watch a movie in the Cinema Room on the Apple TV while the adults are on the patio listening to Airplay music from an iPhone or iPad.

I can achieve this using the Denon Remote App, but would like to activate it from homekit.

I just cant seem to find the right settings to control to different zones at the same time.

**Comment by grzegorz914** [comment]
No, U can not control separate tones at the same time right now, U have choice between control one selected zone or all tones together. The plugin is in development phase and this possibility will be added in the future.

**Comment by grzegorz914** [comment]
Please try to add 3 receivers with same iP but different names like AV Main Zone, AV Zone 1, AV Zone 2 and in every select corespondent zone to control. I think this will be working as 3 separate tile in HomeKit app.

**Comment by grzegorz914** [comment]
Added description how to control zones at the same time separate:
https://github.com/grzegorz914/homebridge-denon-tv#zones-control-and-settings
