### ISSUE TITLE
Inputs Not Showing Up

### ISSUE THREAD

**Issue by weissk93** [grzegorz914/homebridge-denon-tv#281]
[homebridge-denon-tv.log.txt](https://github.com/user-attachments/files/16920113/homebridge-denon-tv.log.txt)

Hi,

My inputs for my Marantz is not showing up anymore. At first I thought it was an issue with the latest version as I was getting a "Speakers, did finish launching error: TypeError: Cannot read properties of undefined (reading, stop).

I downgraded to 5.1.7 and it fixed that issue. However, cannot see the inputs still. 

Otherwise, I can turn the receiver on and off in HomeKit with no issues.

**Comment by simplytoast1** [comment]
I have the same issue with the inputs not showing up as well.  Denon AVR in this instance.

**Comment by grzegorz914** [comment]
post your debug logs please, I can help you without know what happen in your system

**Comment by weissk93** [comment]
> post your debug logs please, I can help you without know what happen in your system

Isn’t that what I attached in original post? Pardon my ignorance. Maybe I’m not sure what I’m doing. Any tips?

**Comment by MrBrownFromLa** [comment]
Same pb on my Marantz M-CR611, custom inputs not showing up.
Going down to v5.1.4 solve the issue.
Do you need the debug logs for v5.1.4 and last update?

**Comment by grzegorz914** [comment]
Yes I need the debug from the last update

**Comment by MrBrownFromLa** [comment]
Here you go:
[homebridge.log-v5.1.4.txt](https://github.com/user-attachments/files/16922228/homebridge.log-v5.1.4.txt)
[homebridge.log-v5.1.12.txt](https://github.com/user-attachments/files/16922230/homebridge.log-v5.1.12.txt)

**Comment by MrBrownFromLa** [comment]
Got this error after update to 5.1.12, perhaps it can help.
[08/09/2024, 14:45:46] [homebridge-denon-tv] Device: 192.168.1.48 M-CR611, did finish launching error: Error: Start error: Check state error: Cannot read properties of undefined (reading 'updateCharacteristic')., check again in 15s.

**Comment by weissk93** [comment]
> Same pb on my Marantz M-CR611, custom inputs not showing up. Going down to v5.1.4 solve the issue. Do you need the debug logs for v5.1.4 and last update?

I tried downgrading to v5.1.4. The inputs show up again if you press and hold the button and go Into all the settings. But not selectable from quick hold.

**Comment by weissk93** [comment]
This is still not fixed for me. I can see the inputs in the deeper settings but cannot select from them at all. Is there any other troubleshooting steps I can do for you?

![IMG_0676](https://github.com/user-attachments/assets/f6c0e136-1d5b-49b7-8851-c3f1b523f69a)
![IMG_0673](https://github.com/user-attachments/assets/a5ddba11-4efe-47e6-b69d-a7d74bb1d5f1)

**Comment by MrBrownFromLa** [comment]
Try unpairing and do it again, it works perfectly for me after updating.
Thanks grzegorz914 for all your hard work!

**Comment by grzegorz914** [comment]
> This is still not fixed for me. I can see the inputs in the deeper settings but cannot select from them at all. Is there any other troubleshooting steps I can do for you?
> 
> ![IMG_0676](https://private-user-images.githubusercontent.com/97804929/365453751-f6c0e136-1d5b-49b7-8851-c3f1b523f69a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MTU1ODQsIm5iZiI6MTcyNTgxNTI4NCwicGF0aCI6Ii85NzgwNDkyOS8zNjU0NTM3NTEtZjZjMGUxMzYtMWQ1Yi00OWI3LTg4NTEtYzNmMWI1MjNmNjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDE3MDgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYzNkNjU2MWE1ZjA2NDYxMDg4MWExN2E2NGM1MTE1YWQxZDQ0ZjMwNWUxNDI2NTdiNmY1MTE0NWE2MWMwYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n2AlN_06k3ioQGvZwu--ozepgclSPXYdSYnu08FlZx0) ![IMG_0673](https://private-user-images.githubusercontent.com/97804929/365453760-a5ddba11-4efe-47e6-b69d-a7d74bb1d5f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MTU1ODQsIm5iZiI6MTcyNTgxNTI4NCwicGF0aCI6Ii85NzgwNDkyOS8zNjU0NTM3NjAtYTVkZGJhMTEtNGVmZS00N2U2LWI2OWQtYTdkNzRiYjFkNWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDE3MDgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNDgzMmExNzYzN2NhZDg0OGRkNTcyN2IwNWE0OTE3ZTdhOTcxMzNiYWRhMzhhZTYyNDhjM2UzNDkzOTMyN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1PlCxzBLE5QwGR8WBa9l-nPBEvzMsRRyblOOYPH8r0s)

Can You post your debug log, try to restart whole homebridge.

**Comment by weissk93** [comment]
> Try unpairing and do it again, it works perfectly for me after updating. Thanks grzegorz914 for all your hard work!

This worked for me. Did not think to do that even though I redid my entire plugin setup a few times before posting on here.

**Comment by simplytoast1** [comment]
I did an unpair and repair on end and no luck.On Sep 8, 2024, at 12:21 PM, weissk93 ***@***.***> wrote:﻿

Try unpairing and do it again, it works perfectly for me after updating. Thanks grzegorz914 for all your hard work!

This worked for me. Did not think to do that even though I redid my entire plugin setup a few times before posting on here.

**Comment by grzegorz914** [comment]
@simplytoast1 get your debug log

**Comment by simplytoast1** [comment]
@grzegorz914 Attached.  Redacted seal numbers and IP addresses.
[homebridge-denon-tv.log-2.txt](https://github.com/user-attachments/files/16923840/homebridge-denon-tv.log-2.txt)

**Comment by simplytoast1** [comment]
5.1.13 restored the inputs!

<img width="498" alt="image" src="https://github.com/user-attachments/assets/2e72f85b-4167-4ab8-9215-6b919a8d7364">

But even after a repair I still an having [weissk93](https://github.com/weissk93) issue: https://github.com/grzegorz914/homebridge-denon-tv/issues/281#issuecomment-2336751382

**Comment by simplytoast1** [comment]
@grzegorz914 - After I deleted the cached accessory in Homebridge and re paired the amp the plugin is working as expected.

**Comment by goshawk2929** [comment]
Same issue and then some.  Now receiver is showing up as a speaker vice a device.  It used to be a device with switches to control inputs, zone speaker setting and even the volume control showed up as a slider all in one tile.  Latest upgrade and now its a speaker that have to use Apple RC app to control anything which is not what I want to do.
