### ISSUE TITLE
Error since the last update

### ISSUE THREAD

**Issue by Cesco117** [grzegorz914/homebridge-denon-tv#286]
Hi,
Everything was working great since many years.
Yesterday I updated to the last version of home bridge and it is now KO.

I have an error message without more explanations.
Am I the only one ? Do you have any solution please ?

thanks !

![IMG_3903](https://github.com/user-attachments/assets/96e7fd79-8ef5-4055-8a89-97b92fe0c6b1)

**Comment by grzegorz914** [comment]
Debug please, go to plugin settings Advanced Settings>>System>>Debug, enable it and get the log.

**Comment by grzegorz914** [comment]
Probably wrong config.json, read readme and adapt to last version.

**Comment by Cesco117** [comment]
> Probably wrong config.json, read readme and adapt to last version.

I didn't change anything, strange.

Debug mode, here is what it says : 
Thanks again for your help, and sorry for the late reply.

[9/15/2024, 7:20:29 PM] [homebridge-denon-tv] Restarting child bridge...
[9/15/2024, 7:20:29 PM] Got SIGTERM, shutting down child bridge process...
[9/15/2024, 7:20:34 PM] [homebridge-denon-tv] Child bridge process ended
[9/15/2024, 7:20:34 PM] [homebridge-denon-tv] Process Ended. Code: 143, Signal: null
[9/15/2024, 7:20:41 PM] [homebridge-denon-tv] Restarting Process...
[9/15/2024, 7:20:42 PM] [homebridge-denon-tv] Launched child bridge with PID 986654
[9/15/2024, 7:20:43 PM] Registering platform 'homebridge-denon-tv.DenonTv'
[9/15/2024, 7:20:43 PM] [homebridge-denon-tv] Loaded homebridge-denon-tv v5.1.15 child bridge successfully
[9/15/2024, 7:20:43 PM] Loaded 0 cached accessories from cachedAccessories.0EAA7DF1F941.
[9/15/2024, 7:20:43 PM] Homebridge v1.8.4 (HAP v0.12.2) (homebridge-denon-tv) is running on port 39565.
[9/15/2024, 7:20:43 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[9/15/2024, 7:20:43 PM] [homebridge-denon-tv] Device: 192.168.0.107 Marantz SR5011, did finish launching.
[9/15/2024, 7:20:43 PM] [homebridge-denon-tv] Device: 192.168.0.107 Marantz SR5011, Config: {
  "name": "Marantz SR5011",
  "host": "192.168.0.107",
  "port": 80,
  "generation": 0,
  "zoneControl": 0,
  "getInputsFromDevice": false,
  "getFavoritesFromDevice": false,
  "getQuickSmartSelectFromDevice": false,
  "inputsDisplayOrder": 1,
  "buttons": [
    {
      "name": "ATV",
      "reference": "0MSSMART1",
      "displayType": 2,
      "namePrefix": false
    },
    {
      "name": "PS4",
      "reference": "0MSSMART2",
      "displayType": 2
    }
  ],
  "sensorPower": false,
  "sensorVolume": false,
  "sensorMute": false,
  "sensorInput": false,
  "infoButtonCommand": "MNMEN ON",
  "masterPower": false,
  "masterMute": false,
  "masterVolume": false,
  "volumeControlNamePrefix": false,
  "volumeControl": 1,
  "volumeMax": 100,
  "refreshInterval": 5,
  "enableDebugMode": true,
  "disableLogInfo": false,
  "disableLogDeviceInfo": false,
  "disableLogConnectError": false,
  "restFul": {
    "enable": false,
    "debug": false
  },
  "mqtt": {
    "enable": false,
    "debug": false,
    "auth": false,
    "passwd": "removed"
  }
}
[9/15/2024, 7:20:43 PM] [homebridge-denon-tv] Device: 192.168.0.107 Marantz SR5011, debug: Connect data: {
  "FriendlyName": {
    "value": "Marantz SR5011"
  },
  "Power": {
    "value": "ON"
  },
  "ZonePower": {
    "value": "ON"
  },
  "RCSourceSelect": {
    "value": "POS"
  },
  "RenameZone": {
    "value": "Projo"
  },
  "TopMenuLink": {
    "value": "ON"
  },
  "VideoSelectDisp": {
    "value": "OFF"
  },
  "VideoSelect": {
    "value": ""
  },
  "VideoSelectOnOff": {
    "value": "OFF"
  },
  "VideoSelectLists": {
    "value": [
      {
        "#text": "Marche",
        "@_index": "ON"
      },
      {
        "#text": "Arrêt",
        "@_index": "OFF"
      }
    ]
  },
  "ECOModeDisp": {
    "value": "ON"
  },
  "ECOMode": {
    "value": "AUTO"
  },
  "ECOModeLists": {
    "value": [
      {
        "@_index": "ON",
        "@_table": "ECO : Marche",
        "@_param": ""
      },
      {
        "@_index": "OFF",
        "@_table": "ECO : Arrêt",
        "@_param": ""
      },
      {
        "@_index": "AUTO",
        "@_table": "ECO : AUTO",
        "@_param": ""
      }
    ]
  },
  "AddSourceDisplay": {
    "value": "FALSE"
  },
  "ModelId": {
    "value": 9
  },
  "BrandId": {
    "value": "MARANTZ_MODEL"
  },
  "SalesArea": {
    "value": 4
  },
  "InputFuncSelect": {
    "value": "AppleTV"
  },
  "NetFuncSelect": {
    "value": "FAVORITES"
  },
  "selectSurround": {
    "value": "Multi Ch Stereo"
  },
  "VolumeDisplay": {
    "value": "Absolute"
  },
  "MasterVolume": {
    "value": -32.5
  },
  "Mute": {
    "value": "off"
  },
  "RemoteMaintenance": {
    "value": ""
  },
  "SubwooferDisplay": {
    "value": "FALSE"
  },
  "Zone2VolDisp": {
    "value": "TRUE"
  },
  "SleepOff": {
    "value": "Arrêt"
  }
}
[9/15/2024, 7:20:43 PM] [homebridge-denon-tv] Device: 192.168.0.107 Marantz SR5011, debug: Saved data: {
  "FriendlyName": {
    "value": "Marantz SR5011"
  },
  "Power": {
    "value": "ON"
  },
  "ZonePower": {
    "value": "ON"
  },
  "RCSourceSelect": {
    "value": "POS"
  },
  "RenameZone": {
    "value": "Projo"
  },
  "TopMenuLink": {
    "value": "ON"
  },
  "VideoSelectDisp": {
    "value": "OFF"
  },
  "VideoSelect": {
    "value": ""
  },
  "VideoSelectOnOff": {
    "value": "OFF"
  },
  "VideoSelectLists": {
    "value": [
      {
        "#text": "Marche",
        "@_index": "ON"
      },
      {
        "#text": "Arrêt",
        "@_index": "OFF"
      }
    ]
  },
  "ECOModeDisp": {
    "value": "ON"
  },
  "ECOMode": {
    "value": "AUTO"
  },
  "ECOModeLists": {
    "value": [
      {
        "@_index": "ON",
        "@_table": "ECO : Marche",
        "@_param": ""
      },
      {
        "@_index": "OFF",
        "@_table": "ECO : Arrêt",
        "@_param": ""
      },
      {
        "@_index": "AUTO",
        "@_table": "ECO : AUTO",
        "@_param": ""
      }
    ]
  },
  "AddSourceDisplay": {
    "value": "FALSE"
  },
  "ModelId": {
    "value": 9
  },
  "BrandId": {
    "value": "MARANTZ_MODEL"
  },
  "SalesArea": {
    "value": 4
  },
  "InputFuncSelect": {
    "value": "AppleTV"
  },
  "NetFuncSelect": {
    "value": "FAVORITES"
  },
  "selectSurround": {
    "value": "Multi Ch Stereo"
  },
  "VolumeDisplay": {
    "value": "Absolute"
  },
  "MasterVolume": {
    "value": -32.5
  },
  "Mute": {
    "value": "off"
  },
  "RemoteMaintenance": {
    "value": ""
  },
  "SubwooferDisplay": {
    "value": "FALSE"
  },
  "Zone2VolDisp": {
    "value": "TRUE"
  },
  "SleepOff": {
    "value": "Arrêt"
  }
}
[9/15/2024, 7:20:43 PM] [homebridge-denon-tv] Device: 192.168.0.107 Marantz SR5011, did finish launching error: Error: Start error: Connect error: Cannot read properties of undefined (reading 'value')..

**Comment by grzegorz914** [comment]
I think you need to select generation 1 for your AVR

**Comment by Cesco117** [comment]
I tried to switch to beta and switch back to stock (now v5.1.19), checked the generation of NVR (took 2010-2012, I guess that the gen1 you were talking about) and it's now ok, thanks for your help !
