### ISSUE TITLE
Homebridge Version 2 works but ....

### ISSUE THREAD

**Issue by cracyfloyd** [grzegorz914/homebridge-denon-tv#289]
Follow Error occurs ...

Mode: OFF
HAP-NodeJS WARNING: The accessory 'Configured Name' has an invalid 'ConfiguredName' characteristic ('Blu-ray'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.

but it works ....

**Comment by grzegorz914** [comment]
It’s warning only, can be ignored.
