### ISSUE TITLE
Input change failed

### ISSUE THREAD

**Issue by sbernhardt81** [grzegorz914/homebridge-denon-tv#29]
Hi Grzegorz,
I upgraded today to the Version 2.4.0.
I very like the new possibility to change volume as well. great work!
while testing everything, I found out, that input change is not working anymore.
The log file shows my change requests, but the denon does not pick it up. Switch flips back to old Input.
vice versa looks ok, any change at the Denon (x2500h) is showing up in the homebridge and the homekit device.
I did not try removing and adding the Device at Homekit so far.

And switchInfoMenu= true crash the homebridge while pressing the "I" button in the iOS RC menu. I turned it off. I can open another issue if you want.

config is:

        {
            "platform": "DenonTv",
            "devices": [
                {
                    "name": "Verstärker",
                    "host": "192.168.7.133",
                    "port": 8080,
                    "zoneControl": 0,
                    "allZonesControl": false,
                    "volumeControl": true,
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "name": "Plex",
                            "reference": "BD"
                        },
                        {
                            "name": "TV Audio",
                            "reference": "TV"
                        },
                        {
                            "name": "PS3",
                            "reference": "GAME"
                        },
                        {
                            "name": "AppleTV",
                            "reference": "MPLAY"
                        },
                        {
                            "name": "Chromecast",
                            "reference": "DVD"
                        },
                        {
                            "name": "Spotify",
                            "reference": "SPOTIFY"
                        },
                        {
                            "name": "Internet",
                            "reference": "NET"
                        },
                        {
                            "name": "Aux",
                            "reference": "AUX1"
                        },
                        {
                            "name": "Bluetooth",
                            "reference": "BT"
                        }
                    ]
                }
            ]
        }

**Comment by grzegorz914** [comment]
Thanks
fixed in 2.4.1

**Comment by grzegorz914** [comment]
Regarding inputs changed Your config is wrong:

https://github.com/grzegorz914/homebridge-denon-tv#configuration

or best to use Config UI X setting to set this correct.

**Comment by sbernhardt81** [comment]
thanks. you were right, my fault, I missed to update the config.
I just updated to the 2.5.10.
input change is now working, even with a short flip back and forth of the setting.

biggest issue is now, homebridge crashes during volume control. will open a new issue.

**Comment by grzegorz914** [comment]
OK, open new issue with crash log
