### ISSUE TITLE
Address Collision

### ISSUE THREAD

**Issue by ValadAmoleo** [grzegorz914/homebridge-denon-tv#295]
I've just added another Denon to my setup but this one is causing a crash with the following error:

[10/24/2024, 10:47:55 AM] [homebridge-denon-tv] Device: 192.168.1.53 Lounge Rumble Denon, Volume Control Type: Relative
[10/24/2024, 10:47:55 AM] [homebridge-denon-tv] Device: 192.168.1.53 Lounge Rumble Denon, Picture Mode: OFF
[10/24/2024, 10:47:56 AM] [homebridge-denon-tv] Device: 192.168.1.210 Cinema Rumble Denon, Connect Success.
[10/24/2024, 10:47:56 AM] [homebridge-denon-tv] -------- Cinema Rumble Denon --------
[10/24/2024, 10:47:56 AM] [homebridge-denon-tv] Manufacturer: Denon/Marantz
[10/24/2024, 10:47:56 AM] [homebridge-denon-tv] Model: [object Object]
[10/24/2024, 10:47:56 AM] [homebridge-denon-tv] Zones: 1
[10/24/2024, 10:47:56 AM] [homebridge-denon-tv] Control: Main Zone
[10/24/2024, 10:47:56 AM] [homebridge-denon-tv] Firmware: 00
[10/24/2024, 10:47:56 AM] [homebridge-denon-tv] Api version: 000
[10/24/2024, 10:47:56 AM] [homebridge-denon-tv] Serialnr: 1234567654321
[10/24/2024, 10:47:56 AM] [homebridge-denon-tv] ----------------------------------
[Cinema Rumble Denon@@Model] characteristic value expected string and received object
[10/24/2024, 10:47:56 AM] [homebridge-denon-tv] Device: 192.168.1.210 Cinema Rumble Denon, published as external accessory.
Error: Accessory Cinema Rumble Denon experienced an address collision.
    at BridgeService.handlePublishExternalAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:418:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[10/24/2024, 10:47:56 AM] [homebridge-denon-tv] Child bridge process ended
[10/24/2024, 10:47:56 AM] [homebridge-denon-tv] Process Ended. Code: 1, Signal: null
[10/24/2024, 10:48:03 AM] [homebridge-denon-tv] Restarting Process...
[10/24/2024, 10:48:03 AM] [homebridge-denon-tv] Launched child bridge with PID 1778951

Here is my config:
{
    "devices": [
        {
            "name": "Cinema Denon",
            "host": "192.168.1.232",
            "port": 8080,
            "generation": 1,
            "zoneControl": 0,
            "getInputsFromDevice": false,
            "getFavoritesFromDevice": false,
            "getQuickSmartSelectFromDevice": false,
            "inputsDisplayOrder": 1,
            "inputs": [
                {
                    "name": "Cinema Apple TV",
                    "reference": "DVD"
                },
                {
                    "name": "8K Switch",
                    "reference": "8K"
                },
                {
                    "name": "CD",
                    "reference": "CD"
                },
                {
                    "name": "Front",
                    "reference": "AUX1"
                },
                {
                    "name": "PlayStation 4",
                    "reference": "CBL/SAT"
                },
                {
                    "name": "Xbox One X",
                    "reference": "BD"
                },
                {
                    "name": "PlayStation 3",
                    "reference": "GAME"
                },
                {
                    "name": "Nintendo Switch",
                    "reference": "MPLAY"
                },
                {
                    "name": "Xbox 360",
                    "reference": "CD"
                },
                {
                    "name": "TV",
                    "reference": "TV"
                },
                {
                    "name": "Record Player",
                    "reference": "PHONO"
                }
            ],
            "buttons": [
                {
                    "name": "AVR-Mon-1",
                    "reference": "0VSMONI1",
                    "displayType": 1,
                    "namePrefix": false
                },
                {
                    "name": "AVR-Mon-2",
                    "reference": "0VSMONI2",
                    "displayType": 1,
                    "namePrefix": false
                },
                {
                    "name": "AVR-HDMI-Amp",
                    "reference": "0VSAUDIO AMP",
                    "displayType": 2
                },
                {
                    "name": "AVR-HDMI-TV",
                    "reference": "0VSAUDIO TV",
                    "displayType": 2
                }
            ],
            "sensorPower": false,
            "sensorVolume": false,
            "sensorMute": false,
            "sensorInput": true,
            "sensorInputs": [
                {
                    "name": "AVR-Inp-Tele",
                    "reference": "TV",
                    "displayType": 3
                }
            ],
            "infoButtonCommand": "MNINF",
            "masterPower": false,
            "masterMute": false,
            "masterVolume": false,
            "volumeControlNamePrefix": false,
            "volumeControl": 2,
            "volumeMax": 100,
            "refreshInterval": 5,
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "restFul": {
                "enable": false,
                "debug": false
            },
            "mqtt": {
                "enable": false,
                "debug": false,
                "auth": false
            }
        },
        {
            "name": "Lounge Denon",
            "host": "192.168.1.22",
            "port": 80,
            "generation": 1,
            "zoneControl": 0,
            "getInputsFromDevice": false,
            "getFavoritesFromDevice": false,
            "getQuickSmartSelectFromDevice": false,
            "inputsDisplayOrder": 1,
            "inputs": [
                {
                    "name": "AppleTV",
                    "reference": "SAT/CBL"
                },
                {
                    "name": "Front",
                    "reference": "AUX1"
                },
                {
                    "name": "Record Player",
                    "reference": "PHONO"
                }
            ],
            "buttons": [
                {
                    "name": "AVR-Back",
                    "reference": "0MNRTN",
                    "displayType": 2,
                    "namePrefix": false
                },
                {
                    "name": "AVR-Aud-Tele",
                    "reference": "0VSAUDIO AMP",
                    "displayType": 2
                },
                {
                    "name": "AVR-Aud-AVR",
                    "reference": "0VSAUDIO AMP",
                    "displayType": 2
                },
                {
                    "name": "AVR-HDMI-Tele",
                    "reference": "0VSMONI1",
                    "displayType": 2
                },
                {
                    "name": "AVR-HDMI-None",
                    "reference": "0VSMONI2",
                    "displayType": 2
                }
            ],
            "sensorPower": true,
            "sensorVolume": true,
            "sensorMute": false,
            "sensorInput": false,
            "sensorInputs": [
                {
                    "name": "AplTele",
                    "reference": "SAT/CBL",
                    "displayType": 3,
                    "namePrefix": true
                }
            ],
            "infoButtonCommand": "MNINF",
            "masterPower": false,
            "masterMute": false,
            "masterVolume": false,
            "volumeControlNamePrefix": false,
            "volumeControl": 2,
            "volumeMax": 100,
            "refreshInterval": 1.5,
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "restFul": {
                "enable": false,
                "debug": false
            },
            "mqtt": {
                "enable": false,
                "debug": false,
                "auth": false
            }
        },
        {
            "name": "Cinema Denon Surround Mode",
            "host": "192.168.1.232",
            "port": 8080,
            "generation": 1,
            "zoneControl": 3,
            "getInputsFromDevice": false,
            "getFavoritesFromDevice": false,
            "getQuickSmartSelectFromDevice": false,
            "inputsDisplayOrder": 1,
            "surrounds": [
                {
                    "name": "Multi Channel Stereo",
                    "reference": "MCH STEREO"
                },
                {
                    "name": "Surround Mode",
                    "reference": "MOVIE"
                },
                {
                    "name": "Stereo",
                    "reference": "STEREO"
                },
                {
                    "name": "Pure Direct",
                    "reference": "PURE DIRECT"
                },
                {
                    "name": "Auto",
                    "reference": "AUTO"
                },
                {
                    "name": "Direct",
                    "reference": "DIRECT"
                }
            ],
            "buttons": [
                {
                    "namePrefix": false
                }
            ],
            "sensorPower": false,
            "sensorVolume": false,
            "sensorMute": false,
            "sensorInput": false,
            "sensorInputs": [
                {
                    "namePrefix": false
                }
            ],
            "infoButtonCommand": "MNINF",
            "masterPower": false,
            "masterMute": false,
            "masterVolume": false,
            "volumeControlNamePrefix": false,
            "volumeControl": 0,
            "volumeMax": 100,
            "refreshInterval": 5,
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "restFul": {
                "enable": false,
                "debug": false
            },
            "mqtt": {
                "enable": false,
                "debug": false,
                "auth": false
            }
        },
        {
            "name": "Lounge Denon Surround Mode",
            "host": "192.168.1.22",
            "port": 80,
            "generation": 1,
            "zoneControl": 3,
            "getInputsFromDevice": false,
            "getFavoritesFromDevice": false,
            "getQuickSmartSelectFromDevice": false,
            "inputsDisplayOrder": 1,
            "surrounds": [
                {
                    "name": "Multi Channel Stereo",
                    "reference": "MCH STEREO"
                },
                {
                    "name": "Surround Mode",
                    "reference": "MUSIC"
                },
                {
                    "name": "Stereo",
                    "reference": "STEREO"
                },
                {
                    "name": "Pure Direct",
                    "reference": "PURE DIRECT"
                },
                {
                    "name": "Auto",
                    "reference": "AUTO"
                },
                {
                    "name": "Direct",
                    "reference": "DIRECT"
                }
            ],
            "buttons": [
                {
                    "namePrefix": false
                }
            ],
            "sensorPower": false,
            "sensorVolume": false,
            "sensorMute": false,
            "sensorInput": false,
            "sensorInputs": [
                {
                    "namePrefix": false
                }
            ],
            "infoButtonCommand": "MNINF",
            "masterPower": false,
            "masterMute": false,
            "masterVolume": false,
            "volumeControlNamePrefix": false,
            "volumeControl": 0,
            "volumeMax": 100,
            "refreshInterval": 5,
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "restFul": {
                "enable": false,
                "debug": false
            },
            "mqtt": {
                "enable": false,
                "debug": false,
                "auth": false
            }
        },
        {
            "name": "Cinema Denon Zone 2",
            "host": "192.168.1.232",
            "port": 8080,
            "generation": 1,
            "zoneControl": 1,
            "getInputsFromDevice": true,
            "getFavoritesFromDevice": false,
            "getQuickSmartSelectFromDevice": false,
            "inputsDisplayOrder": 1,
            "sensorPower": false,
            "sensorVolume": false,
            "sensorMute": false,
            "sensorInput": false,
            "infoButtonCommand": "MNMEN ON",
            "masterPower": false,
            "masterMute": false,
            "masterVolume": false,
            "volumeControlNamePrefix": false,
            "volumeControl": 0,
            "volumeMax": 100,
            "refreshInterval": 5,
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "restFul": {
                "enable": false,
                "debug": false
            },
            "mqtt": {
                "enable": false,
                "debug": false,
                "auth": false
            }
        },
        {
            "name": "Lounge Rumble Denon",
            "host": "192.168.1.53",
            "port": 80,
            "generation": 0,
            "zoneControl": 0,
            "getInputsFromDevice": false,
            "getFavoritesFromDevice": false,
            "getQuickSmartSelectFromDevice": false,
            "inputsDisplayOrder": 0,
            "inputs": [
                {
                    "name": "Rumble",
                    "reference": "CD"
                }
            ],
            "sensorPower": false,
            "sensorVolume": false,
            "sensorMute": false,
            "sensorInput": false,
            "infoButtonCommand": "MNMEN ON",
            "masterPower": false,
            "masterMute": false,
            "masterVolume": false,
            "volumeControlNamePrefix": false,
            "volumeControl": 2,
            "volumeMax": 100,
            "refreshInterval": 5,
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "restFul": {
                "enable": false,
                "debug": false
            },
            "mqtt": {
                "enable": false,
                "debug": false,
                "auth": false
            }
        },
        {
            "name": "Cinema Rumble Denon",
            "host": "192.168.1.210",
            "port": 80,
            "generation": 0,
            "zoneControl": 0,
            "getInputsFromDevice": false,
            "getFavoritesFromDevice": false,
            "getQuickSmartSelectFromDevice": false,
            "inputsDisplayOrder": 0,
            "inputs": [
                {
                    "name": "Rumble",
                    "reference": "CD"
                }
            ],
            "sensorPower": false,
            "sensorVolume": false,
            "sensorMute": false,
            "sensorInput": false,
            "infoButtonCommand": "MNMEN ON",
            "masterPower": false,
            "masterMute": false,
            "masterVolume": false,
            "volumeControlNamePrefix": false,
            "volumeControl": 2,
            "volumeMax": 100,
            "refreshInterval": 5,
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "disableLogConnectError": false,
            "restFul": {
                "enable": false,
                "debug": false
            },
            "mqtt": {
                "enable": false,
                "debug": false,
                "auth": false
            }
        }
    ],
    "_bridge": {
        "username": "0E:A4:E5:96:0A:A5"
    },
    "platform": "DenonTv"
}

Probably unrelated but since adding this new one into Config-UI, I now can't edit via Config-UI.
![image](https://github.com/user-attachments/assets/44c0a8bb-bd14-428b-8e47-d5b6ab1e3e77)

**Comment by ValadAmoleo** [comment]
Formatting has gone a bit weird, let me see if I can sort it.

**Comment by grzegorz914** [comment]
Please post debug log.

**Comment by ValadAmoleo** [comment]
[10/24/2024, 11:16:45 AM] [homebridge-denon-tv] Device: 192.168.1.53 Lounge Rumble Denon, Connect Success.
[10/24/2024, 11:16:45 AM] [homebridge-denon-tv] -------- Lounge Rumble Denon --------
[10/24/2024, 11:16:45 AM] [homebridge-denon-tv] Manufacturer: Denon/Marantz
[10/24/2024, 11:16:45 AM] [homebridge-denon-tv] Model: [object Object]
[10/24/2024, 11:16:45 AM] [homebridge-denon-tv] Zones: 1
[10/24/2024, 11:16:45 AM] [homebridge-denon-tv] Control: Main Zone
[10/24/2024, 11:16:45 AM] [homebridge-denon-tv] Firmware: 00
[10/24/2024, 11:16:45 AM] [homebridge-denon-tv] Api version: 000
[10/24/2024, 11:16:45 AM] [homebridge-denon-tv] Serialnr: 1234567654321
[10/24/2024, 11:16:45 AM] [homebridge-denon-tv] ----------------------------------
[10/24/2024, 11:16:45 AM] [homebridge-denon-tv] Device: 192.168.1.53 Lounge Rumble Denon, published as external accessory.
[10/24/2024, 11:16:45 AM] [homebridge-denon-tv] Device: 192.168.1.53 Lounge Rumble Denon, Power: OFF
[10/24/2024, 11:16:45 AM] [homebridge-denon-tv] Device: 192.168.1.53 Lounge Rumble Denon, Input Name: Rumble
[10/24/2024, 11:16:45 AM] [homebridge-denon-tv] Device: 192.168.1.53 Lounge Rumble Denon, Reference: CD
[10/24/2024, 11:16:45 AM] [homebridge-denon-tv] Device: 192.168.1.53 Lounge Rumble Denon, Volume: 12dB
[10/24/2024, 11:16:45 AM] [homebridge-denon-tv] Device: 192.168.1.53 Lounge Rumble Denon, Mute: ON
[10/24/2024, 11:16:45 AM] [homebridge-denon-tv] Device: 192.168.1.53 Lounge Rumble Denon, Volume Control Type: Relative
[10/24/2024, 11:16:45 AM] [homebridge-denon-tv] Device: 192.168.1.53 Lounge Rumble Denon, Picture Mode: OFF
[10/24/2024, 11:16:45 AM] Lounge Rumble Denon BD84 is running on port 52116.
[10/24/2024, 11:16:45 AM] Please add [Lounge Rumble Denon BD84] manually in Home app. Setup Code: 344-45-234
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Device: 192.168.1.210 Cinema Rumble Denon, did finish launching.
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Device: 192.168.1.210 Cinema Rumble Denon, Config: {
  "name": "Cinema Rumble Denon",
  "host": "192.168.1.210",
  "port": 80,
  "generation": 0,
  "zoneControl": 0,
  "getInputsFromDevice": false,
  "getFavoritesFromDevice": false,
  "getQuickSmartSelectFromDevice": false,
  "inputsDisplayOrder": 0,
  "inputs": [
    {
      "name": "Rumble",
      "reference": "CD"
    }
  ],
  "sensorPower": false,
  "sensorVolume": false,
  "sensorMute": false,
  "sensorInput": false,
  "infoButtonCommand": "MNMEN ON",
  "masterPower": false,
  "masterMute": false,
  "masterVolume": false,
  "volumeControlNamePrefix": false,
  "volumeControl": 2,
  "volumeMax": 100,
  "refreshInterval": 5,
  "enableDebugMode": true,
  "disableLogInfo": false,
  "disableLogDeviceInfo": false,
  "disableLogConnectError": false,
  "restFul": {
    "enable": false,
    "debug": false
  },
  "mqtt": {
    "enable": false,
    "debug": false,
    "auth": false,
    "passwd": "removed"
  }
}
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Device: 192.168.1.210 Cinema Rumble Denon, debug: Connect data: {
  "FriendlyName": {
    "value": "Living Room"
  },
  "Power": {
    "value": "STANDBY"
  },
  "ZonePower": {
    "value": "OFF"
  },
  "RenameZone": {
    "value": "Living Rm"
  },
  "TopMenuLink": {
    "value": "OFF"
  },
  "ModelId": {
    "value": 4
  },
  "SalesArea": {
    "value": 1
  },
  "InputFuncSelect": {
    "value": "RUMBLE"
  },
  "NetFuncSelect": {
    "value": "RHAPSODY"
  },
  "selectSurround": {
    "value": "MULTI CH STEREO"
  },
  "VolumeDisplay": {
    "value": "Relative"
  },
  "MasterVolume": {
    "value": 8
  },
  "Mute": {
    "value": "off"
  },
  "RemoteMaintenance": {
    "value": "OFF"
  },
  "SubwooferDisplay": {
    "value": "FALSE"
  },
  "Zone2VolDisp": {
    "value": "TRUE"
  },
  "LastfmDisplay": {
    "value": "FALSE"
  },
  "SpotifyEnable": {
    "value": "TRUE"
  }
}
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Device: 192.168.1.210 Cinema Rumble Denon, debug: Saved data: {
  "FriendlyName": {
    "value": "Living Room"
  },
  "Power": {
    "value": "STANDBY"
  },
  "ZonePower": {
    "value": "OFF"
  },
  "RenameZone": {
    "value": "Living Rm"
  },
  "TopMenuLink": {
    "value": "OFF"
  },
  "ModelId": {
    "value": 4
  },
  "SalesArea": {
    "value": 1
  },
  "InputFuncSelect": {
    "value": "RUMBLE"
  },
  "NetFuncSelect": {
    "value": "RHAPSODY"
  },
  "selectSurround": {
    "value": "MULTI CH STEREO"
  },
  "VolumeDisplay": {
    "value": "Relative"
  },
  "MasterVolume": {
    "value": 8
  },
  "Mute": {
    "value": "off"
  },
  "RemoteMaintenance": {
    "value": "OFF"
  },
  "SubwooferDisplay": {
    "value": "FALSE"
  },
  "Zone2VolDisp": {
    "value": "TRUE"
  },
  "LastfmDisplay": {
    "value": "FALSE"
  },
  "SpotifyEnable": {
    "value": "TRUE"
  }
}
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Device: 192.168.1.210 Cinema Rumble Denon, All Inputs: [
  {
    "name": "Rumble",
    "reference": "CD",
    "mode": "SI"
  }
]
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Device: 192.168.1.210 Cinema Rumble Denon, debug: Saved data: [
  {
    "name": "Rumble",
    "reference": "CD",
    "mode": "SI"
  }
]
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Device: 192.168.1.210 Cinema Rumble Denon, Connect Success.
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] -------- Cinema Rumble Denon --------
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Manufacturer: Denon/Marantz
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Model: [object Object]
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Zones: 1
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Control: Main Zone
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Firmware: 00
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Api version: 000
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Serialnr: 1234567654321
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] ----------------------------------
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Device: 192.168.1.210 Cinema Rumble Denon, debug: Read saved Inputs Names: {}
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Device: 192.168.1.210 Cinema Rumble Denon, debug: Read saved Inputs Target Visibility: {}
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Device: 192.168.1.210 Cinema Rumble Denon, debug: Prepare accessory
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Device: 192.168.1.210 Cinema Rumble Denon, debug: Prepare information service
[Cinema Rumble Denon@@Model] characteristic value expected string and received object
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Device: 192.168.1.210 Cinema Rumble Denon, debug: Prepare television service
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Device: 192.168.1.210 Cinema Rumble Denon, debug: Prepare speaker service
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Device: 192.168.1.210 Cinema Rumble Denon, debug: Prepare inputs services
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Device: 192.168.1.210 Cinema Rumble Denon, debug: Prepare volume service
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Device: 192.168.1.210 Cinema Rumble Denon, published as external accessory.
[10/24/2024, 11:16:46 AM] [homebridge-denon-tv] Device: 192.168.1.210 Cinema Rumble Denon, debug: Inputs display order: [
  {
    "name": "Rumble",
    "reference": "CD",
    "mode": "SI",
    "visibility": 0,
    "identifier": 1
  }
]
Error: Accessory Cinema Rumble Denon experienced an address collision.
    at BridgeService.handlePublishExternalAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:418:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by grzegorz914** [comment]
You need go to plugin settings Advanced Settings >>.System>> Debug enable it and then get the log.

**Comment by grzegorz914** [comment]
Fixed

**Comment by ValadAmoleo** [comment]
Oh wow you managed to fix it faster than I could correctly enable the debug log.  Thank you!!
