### ISSUE TITLE
set Input error: TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by mishakim** [grzegorz914/homebridge-denon-tv#296]
Every time the AVR turns on, I get this error in the logs. Everything seems to be working fine other than the fact that the error is logged.

It's a Marantz NR1510, just one zone, four HDMI inputs

This is all that's in the log:
`[24/10/2024, 08:20:20] [homebridge-denon-tv] Error: 
    at Accessory.sendCharacteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:2044:14)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1745:14)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
[24/10/2024, 08:20:25] [homebridge-denon-tv] Device: 10.0.1.109 Home Theater, set Input error: TypeError: Cannot read properties of undefined (reading 'name')`

**Comment by grzegorz914** [comment]
Please enable debug in plugin config and get the log.

**Comment by mishakim** [comment]
Log attached (didn't realize the system-level logging didn't affect the plugin; I wondered why there wasn't much to the log).
I just realized this only happens when the AVR is turned on indirectly, by turning the TV on. The error does not occur if the AVR is turned on directly.
[homebridge-denon-tv.log.txt](https://github.com/user-attachments/files/17506921/homebridge-denon-tv.log.txt)

**Comment by grzegorz914** [comment]
try 5.1.22-beta.0 and let me know

**Comment by grzegorz914** [comment]
arę you have some automations running with this device? looks like some automations try to change input after POWER OFF/ON

**Comment by mishakim** [comment]
5.1.22-beta0 didn’t seem to change it

Yes, there was an old automation running, it was supposed to turn the AVR on and off to mirror the TV due to CEC not working reliably with that TV. That wasn’t supposed to change the input, but disabling it does appear to have gotten rid of this error. I’ll bet it had some stale value for the input name in the automation.

The TV also seems to be correctly controlling the AVR state without that automation for now, so I guess that resolves the problem.

Thanks!

On Oct 24, 2024, at 10:35 AM, Grzegorz ***@***.***> wrote:



arę you have some automations running with this device? looks like some automations try to change input after POWER OFF/ON
