### ISSUE TITLE
homebridge crash after volume change

### ISSUE THREAD

**Issue by sbernhardt81** [grzegorz914/homebridge-denon-tv#30]
Hi Grzegorz
with V2.5.10 I see homebridge crashing/restarting after volume change:

log:

May 20 19:54:17 homebridge homebridge[6367]: [5/20/2020, 7:54:17 PM] [DenonTv] Device: 192.168.7.133 Verstärker, devInfoFile saved successful in: /var/lib/homebridge/denonTv/
May 20 19:54:24 homebridge homebridge[6367]: [5/20/2020, 7:54:24 PM] [LgWebOsTv] Device: 192.168.7.171 LG TV, get current Power state successfull, state: OFF
May 20 19:54:24 homebridge homebridge[6367]: [5/20/2020, 7:54:24 PM] [DenonTv] Device: 192.168.7.133 Verstärker Main Zone, get current Power state successful: ON
May 20 19:54:24 homebridge homebridge[6367]: [5/20/2020, 7:54:24 PM] [DenonTv] Device: 192.168.7.133 Verstärker Main Zone, get current Input successful: TV
May 20 19:54:24 homebridge homebridge[6367]: [5/20/2020, 7:54:24 PM] [DenonTv] Device: 192.168.7.133 Verstärker Main Zone, get current Volume level successful: -45 dB
May 20 19:54:24 homebridge homebridge[6367]: [5/20/2020, 7:54:24 PM] [Verstärker Lautstärke] Receiver MainZone Volume power state is 1
May 20 19:54:33 homebridge homebridge[6367]: [5/20/2020, 7:54:33 PM] ReferenceError: stste is not defined
May 20 19:54:33 homebridge homebridge[6367]:     at denonTvDevice.setMute (/usr/local/lib/node_modules/homebridge-denon-tv/index.js:440:21)
May 20 19:54:33 homebridge homebridge[6367]:     at Mute.emit (events.js:310:20)
May 20 19:54:33 homebridge homebridge[6367]:     at Mute.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
May 20 19:54:33 homebridge homebridge[6367]:     at Mute.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:625:12)
May 20 19:54:33 homebridge homebridge[6367]:     at TelevisionSpeaker.Service._this.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:318:35)
May 20 19:54:33 homebridge homebridge[6367]:     at On.<anonymous> (/usr/local/lib/node_modules/homebridge-denon-tv/index.js:330:25)
May 20 19:54:33 homebridge homebridge[6367]:     at On.emit (events.js:310:20)
May 20 19:54:33 homebridge homebridge[6367]:     at On.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
May 20 19:54:33 homebridge homebridge[6367]:     at On.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:625:12)
May 20 19:54:33 homebridge homebridge[6367]:     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1437:24
May 20 19:54:33 homebridge homebridge[6367]:     at Array.forEach (<anonymous>)
May 20 19:54:33 homebridge homebridge[6367]:     at Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1279:10)
May 20 19:54:33 homebridge homebridge[6367]:     at HAPServer.emit (events.js:310:20)
May 20 19:54:33 homebridge homebridge[6367]:     at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
May 20 19:54:33 homebridge homebridge[6367]:     at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:812:12)
May 20 19:54:33 homebridge homebridge[6367]:     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:280:24)
May 20 19:54:33 homebridge homebridge[6367]: [5/20/2020, 7:54:33 PM] Got SIGTERM, shutting down Homebridge...

config:
{
            "devices": [
                {
                    "name": "Verstärker",
                    "host": "192.168.7.133",
                    "port": 8080,
                    "zoneControl": 0,
                    "volumeControl": true,
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "name": "Plex",
                            "reference": "BD",
                            "type": "HDMI",
                            "mode": "SI"
                        },
                        {
                            "name": "TV Audio",
                            "reference": "TV",
                            "type": "HDMI",
                            "mode": "SI"
                        },
                        {
                            "name": "PS3",
                            "reference": "GAME",
                            "type": "HDMI",
                            "mode": "SI"
                        },
                        {
                            "name": "AppleTV",
                            "reference": "MPLAY",
                            "type": "HDMI",
                            "mode": "SI"
                        },
                        {
                            "name": "Chromecast",
                            "reference": "DVD",
                            "type": "HDMI",
                            "mode": "SI"
                        },
                        {
                            "name": "Spotify",
                            "reference": "SPOTIFY",
                            "type": "HDMI",
                            "mode": "SI"
                        },
                        {
                            "name": "Internet",
                            "reference": "NET",
                            "type": "HDMI",
                            "mode": "SI"
                        },
                        {
                            "name": "Aux",
                            "reference": "AUX1",
                            "type": "HDMI",
                            "mode": "SI"
                        },
                        {
                            "name": "Bluetooth",
                            "reference": "BT",
                            "type": "HDMI",
                            "mode": "SI"
                        }
                    ]
                }
            ],
            "platform": "DenonTv"
        }

**Comment by grzegorz914** [comment]
fixed 2.5.11
