### ISSUE TITLE
All Zone Stereo: enhancement

### ISSUE THREAD

**Issue by abmotta** [grzegorz914/homebridge-denon-tv#33]
Congratulations for your work! Would it be possible to add a switch for the All Zone Stereo?
The commands in telnet are MNZST ON and MNZST OFF.
I've tried these commands on a telnet terminal in my X3500 and worked fine.

Thank you!!

**Comment by grzegorz914** [comment]
U can configure this in inputs and can be added to the every zone or to only one zone,

```
                         {
                            "name": "All zones stereo",
                            "reference": "ALL ZONE STEREO",
                            "type": "OTHER",
                            "mode": "MS"
                        },
```
