### ISSUE TITLE
Changelog Maintenance

### ISSUE THREAD

**Issue by intrepidsilence** [grzegorz914/homebridge-denon-tv#34]
Would it be ok to ask that you keep the changelog up with commits? It would be great to know what changed before applying an update.  Also, there is some difference in your package and others that use config-ui-x when doing updates. Other packages display the changelog before applying to update, your displays it after. Would you consider changing it to work the other way?

Thanks in advance!

**Comment by grzegorz914** [comment]
Only release update shows changes before update, all others U can read on git in descriptions of commit.
