### ISSUE TITLE
AVR not showing up as TV

### ISSUE THREAD

**Issue by Danton-** [grzegorz914/homebridge-denon-tv#39]
Good afternoon,

Sadly enough my X3400-H is not showing as a TV in Homebridge nor in Hoobs. Is this a known issue? Have the same problem with the homebridge-denon-heos plugin.

Hopefully there is an easy fix :).

Kind regards, Danton

**Comment by grzegorz914** [comment]
What iOS U have installed?

**Comment by miguelsasso** [comment]
Not sure if related, but I'm unable to get this to work with Hoobs / iOS14 also.  Homebridge finds the receiver but Homekit can't find the accessory. 

 [DenonTv] Device: 192.168.1.107 AV Receiver Main Zone, state: Online.
22/09/2020, 20:10:02 [DenonTv] -------- AV Receiver --------
22/09/2020, 20:10:02 [DenonTv] Manufacturer: Denon
22/09/2020, 20:10:02 [DenonTv] Model: AVR-X1400H
22/09/2020, 20:10:02 [DenonTv] Zones: 2
22/09/2020, 20:10:02 [DenonTv] Api version: 0301
22/09/2020, 20:10:02 [DenonTv] Serialnr: 0005CDAB0A78
22/09/2020, 20:10:02 [DenonTv] Firmware: 00
22/09/2020, 20:10:02 [DenonTv] ----------------------------------

**Comment by grzegorz914** [comment]
Alteady tester on mu siteband all working as excepted. Its not a plugin problem, check Your Local network.

**Comment by miguelsasso** [comment]
Ok.  Just to confirm, from the home app...  I click '+',  then 'add accessory', then 'I don't have a code or cannot scan'?

**Comment by grzegorz914** [comment]
Yes, exactly.

**Comment by miguelsasso** [comment]
Ok, tried everything I can think of at my end.  Local network is fine.  I've restarted the Homebridge service, Homekit Hub, iPhone and AVR.  Tried adding the accessory numerous times using the 'I don't have a code or cannot scan' option.  Out of ideas.  As per the above, Homebridge has found the AVR.

@Danton- Are you experiencing the same issue i've described above?

**Comment by grzegorz914** [comment]
What version of plugin U have installed?
Try to rename AVR “name” in config j.son save, restart homebridge and try to add it again. Also U can remove accessory cache from homebridge.

**Comment by miguelsasso** [comment]
Problem solved.  I renamed the AVR "name" and Homekit picked it up right away.  I'll know to clear the cache next time too.  Many thanks
