### ISSUE TITLE
Could we get a polling rate feature in this application? 

### ISSUE THREAD

**Issue by Luitwieler** [grzegorz914/homebridge-denon-tv#40]
I noticed that this package is generating quite a lot of load on the raspberry pi. 
Looking at the logs from the package it is polling every 3 seconds the state of the Denon AVR. 
This is fine however not necessary for my use case. Could we introduce a polling setting which allows us to change this 3 seconds?

**Comment by grzegorz914** [comment]
Yes, 
will be added in the next update.
