### ISSUE TITLE
X3300W - Homekit asking for 8-digit code

### ISSUE THREAD

**Issue by Robnbill** [grzegorz914/homebridge-denon-tv#41]
Hi - Will this plugin work with my Denon model - when I try to add it as an accessory under Homekit it keeps asking for a code which I don't have.

**Comment by grzegorz914** [comment]
Is Your Homebridge Pin

**Comment by drewcovi** [comment]
Also having this issue. Homebridge pin not working

**Comment by drewcovi** [comment]
Fixed by using another device. Clearly a HomeKit bug.
