### ISSUE TITLE
Only one Input available in Home App

### ISSUE THREAD

**Issue by spaggi2** [grzegorz914/homebridge-denon-tv#43]
I've copied the config from your example:

`
{
            "devices": [
                {
                    "name": "Testooo",
                    "host": "192.168.178.43",
                    "port": 80,
                    "refreshInterval": 5,
                    "zoneControl": 0,
                    "volumeControl": 1,
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "name": "Xbox One",
                            "reference": "GAME",
                            "type": "HDMI",
                            "mode": "SI"
                        },
                        {
                            "name": "Television",
                            "reference": "TV",
                            "type": "HDMI",
                            "mode": "SI"
                        },
                        {
                            "name": "Sat Receiver",
                            "reference": "SAT/CBL",
                            "type": "HDMI",
                            "mode": "SI"
                        }
                    ]
                }
            ],
            "platform": "DenonTv"
        }
`

I see the device as a receiver in my home app, however in the selection window I can only see XBOX One as single Input to choose from. In the Group there are additional tiles "Sat Receiver" and "Television" however I cannot interact with them. Did I do somthing wrong?

**Comment by grzegorz914** [comment]
What iOS U use on iPhone?

**Comment by spaggi** [comment]
Hi, I'm on iOS 14 and tvOS 14 as hub. What's odd is now a second input out of the 3 (Television) has appeared.

**Comment by grzegorz914** [comment]
Please post the Homebridge log after restart it

**Comment by djrams10** [comment]
> I've copied the config from your example:
> 
> `{ "devices": [ { "name": "Testooo", "host": "192.168.178.43", "port": 80, "refreshInterval": 5, "zoneControl": 0, "volumeControl": 1, "switchInfoMenu": false, "inputs": [ { "name": "Xbox One", "reference": "GAME", "type": "HDMI", "mode": "SI" }, { "name": "Television", "reference": "TV", "type": "HDMI", "mode": "SI" }, { "name": "Sat Receiver", "reference": "SAT/CBL", "type": "HDMI", "mode": "SI" } ] } ], "platform": "DenonTv" }`
> 
> I see the device as a receiver in my home app, however in the selection window I can only see XBOX One as single Input to choose from. In the Group there are additional tiles "Sat Receiver" and "Television" however I cannot interact with them. Did I do somthing wrong?

hello, I'm the same problem. Source changes are done in the logs, but not in the homekit application.

[10/11/2020, 9:52:06 PM] [DenonTv] Device: 192.168.86.229 Home Cinéma Main Zone, get current Power state successful: ON
[10/11/2020, 9:52:06 PM] [DenonTv] Device: 192.168.86.229 Home Cinéma Main Zone, get current Input successful: Apple Tv MPLAY
[10/11/2020, 9:52:27 PM] [DenonTv] Device: 192.168.86.229 Home Cinéma Main Zone, get current Power state successful: ON
[10/11/2020, 9:52:27 PM] [DenonTv] Device: 192.168.86.229 Home Cinéma Main Zone, get current Input successful: Apple Tv MPLAY
[10/11/2020, 9:52:32 PM] [DenonTv] Device: 192.168.86.229 Home Cinéma Main Zone, get current Power state successful: ON
[10/11/2020, 9:52:32 PM] [DenonTv] Device: 192.168.86.229 Home Cinéma Main Zone, get current Input successful: Apple Tv MPLAY
[10/11/2020, 9:52:38 PM] [DenonTv] Device: 192.168.86.229 Home Cinéma Main Zone, set new Input successful: Aiplay Net

**Comment by grzegorz914** [comment]
All ok in The log, The problem must be on The Homebridge or HomeKit app. Try to reset instancje and cache in homebridge, remove Accessory from HomeKit app and add it again. Please also post Your HB version, Log in debug Mode.

**Comment by spaggi2** [comment]
Sorry I've been so quiet on this. I did an update in Homebridge and now it works for me
