### ISSUE TITLE
Error Connecting

### ISSUE THREAD

**Issue by MarketSqHero** [grzegorz914/homebridge-denon-tv#47]
Device: 192.168.*.* Denon, getDeviceInfo eror: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read',
  config: [Object],
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function]
}, state: Offline

**Comment by grzegorz914** [comment]
What a AVR? Are U set correct port and IP address?

**Comment by MarketSqHero** [comment]
Hi;


Thanks for the quick reply. I'm thinking it's the HTTP / Telnet issue? I have a 2400H and if I use the http check at


/goform/Deviceinfo.xml


I get a 403: Forbidden error


Oddly I was sure this did work a few days ago. It may have been another plugin but I definitely had control of my AVR from Homekit.

Regards
Darren

On 19 October 2020 at 12:04, Grzegorz <notifications@github.com> wrote:






What a AVR? Are U set correct port and IP address?

**Comment by grzegorz914** [comment]
Try to set port 80 or 8080

**Comment by MarketSqHero** [comment]
Port 80 gives me


Denon TV HB, getDeviceInfo eror: Error: Request failed with status code 403
at createError (C:\Users\HTPC\AppData\Roaming\npm\node_modules\homebridge-denon-tv\node_modules\axios\lib\core\createError.js:16:15)
at settle (C:\Users\HTPC\AppData\Roaming\npm\node_modules\homebridge-denon-tv\node_modules\axios\lib\core\settle.js:17:12)
at IncomingMessage.handleStreamEnd (C:\Users\HTPC\AppData\Roaming\npm\node_modules\homebridge-denon-tv\node_modules\axios\lib\adapters\http.js:236:11)
at IncomingMessage.emit (events.js:327:22)
at endReadableNT (_stream_readable.js:1221:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21) {
config: [Object],
request: [ClientRequest],
response: [Object],
isAxiosError: true,
toJSON: [Function]
}, state: Offline


Port 8080 gives me


Denon TV HB, getDeviceInfo eror: Error: read ECONNRESET
at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
errno: 'ECONNRESET',
code: 'ECONNRESET',
syscall: 'read',
config: [Object],
request: [Writable],
response: undefined,
isAxiosError: true,
toJSON: [Function]
}, state: Offline


Does the 2400H support HTTP? Or does your plugin support Telnet?


Thanks

On 19 October 2020 at 12:22, Grzegorz <notifications@github.com> wrote:






Try to set port 80 or 8080

**Comment by grzegorz914** [comment]
try this:
http://ip:8080/goform/formMainZone_MainZoneXmlStatusLite.xml  and get the output

**Comment by MarketSqHero** [comment]
On 8080 I get


This site can’t be reachedThe connection was reset.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_RESET




on 80  get


Error 403: Forbidden
Access Forbidden


I don't have any ports blocked and the AV is connected to the router via Cat5, not WiFi

On 19 October 2020 at 12:59, Grzegorz <notifications@github.com> wrote:






try this:
http://ip:8080/goform/formMainZone_MainZoneXmlStatusLite.xml and get the output

**Comment by grzegorz914** [comment]
Hmm... looks like the model support only telnet command.

**Comment by MarketSqHero** [comment]
Yes, I think that's the answer. Is your plugin only working over HTTP commands?

On 19 October 2020 at 13:21, Grzegorz <notifications@github.com> wrote:






Hmm... looks like the model support only telnet command.

**Comment by grzegorz914** [comment]
Yes, right now support only HTTP
