### ISSUE TITLE
Missing name

### ISSUE THREAD

**Issue by Dhorst** [grzegorz914/homebridge-denon-tv#48]
Hello,

After reading all issues I still am looking for an solution to my problem.

I tried different names from Denon to Marantz to reciever etc...

Starting ' Hoobs'  / homebridge I see this in mij log file:
Log:
31/10/2020, 12:34:02 [DenonTv] Initializing DenonTv platform...
31/10/2020, 12:34:02 [DenonTv] **Device Name Missing**
31/10/2020, 12:34:02 External port pool ran out of ports. Fallback to random assign.

My confiq:

[
    {
        "platform": "DenonTv",
        "devices": [
            {
                "name": "Denon",
                _"host": "0.0.0.0",_
                "port": 80,
                "refreshInterval": 5,
                "zoneControl": 0,
                "volumeControl": 0,
                "switchInfoMenu": true,
                "inputs": [
                    {
                        "name": "Television",
                        "reference": "TV",
                        "type": "HDMI",
                        "mode": "SI"
                    },
                    {
                        "name": "Stereo",
                        "reference": "STEREO",
                        "type": "OTHER",
                        "mode": "MS"
                    },
                    {
                        "name": "Multi Channel Stereo",
                        "reference": "MCH STEREO",
                        "type": "OTHER",
                        "mode": "MS"
                    },
                    {
                        "name": "Digital Input AUTO",
                        "reference": "AUTO",
                        "type": "OTHER",
                        "mode": "DC"
                    }
                ],
                "manufacturer": "Manufacturer",
                "modelName": "Model",
                "serialNumber": "Serial Number",
                "firmwareRevision": "Firmware Revision"
            }
        ]
    }
]

**Comment by grzegorz914** [comment]
This is typical HOOBS problem, move your installation to Homebridge and Config UI X:
https://github.com/homebridge/homebridge-raspbian-image/wiki/How-to-migrate-from-HOOBS-to-Homebridge

**Comment by Dhorst** [comment]
I really like Hoobs because its more my difficult level:P

I tried homebridge but I don't have any experience with Json or coding....

Isn't there any solution?

**Comment by grzegorz914** [comment]
Post this problem on the HOOBS support

**Comment by Dhorst** [comment]
Thanks! will do
