### ISSUE TITLE
Tiles Only showing up in Homebridge

### ISSUE THREAD

**Issue by WinterBoss** [grzegorz914/homebridge-denon-tv#49]
Hello, I have a AVR-X3500H I see all the settings in the homebridge web UI but they don't appear in homekit. I uninstalled and reinstalled and it's the same issue. The log shows it connects properly and the controls work via homebridge but nothing shows up in Homekit

**Comment by chetstone** [comment]
Did you follow the instructions in the plugin's Settings to pair the device?

> "This plugin works with Denon/Marantz AV Receivers series X and are exposed to HomeKit as separate accessories and each needs to be manually paired.
>1. Open the Home <img src='https://user-images.githubusercontent.com/3979615/78010622-4ea1d380-738e-11ea-8a17-e6a465eeec35.png' height='16.42px'> app on your device.
>2. Tap the Home tab, then tap <img src='https://user-images.githubusercontent.com/3979615/78010869-9aed1380-738e-11ea-9644-9f46b3633026.png' height='16.42px'>.
>3. Tap *Add Accessory*, and select *I Don't Have a Code or Cannot Scan*.
>4. Enter the Homebridge PIN, this can be found under the QR code in Homebridge UI or your Homebridge logs, alternatively you can select *Use Camera* and scan the QR code again.",

Also, if you define more than one zone, you have to pair each zone separately as above.
@grzegorz914 these instructions should probably be included in the README as well as in the settings page that comes up when you install the plugin.

**Comment by grzegorz914** [comment]
Readme updated.
