### ISSUE TITLE
Default Homekit Config Code? 

### ISSUE THREAD

**Issue by phenomeus** [grzegorz914/homebridge-denon-tv#5]
I somehow see a "Volume-1480" Device that I can add to HomeKit (Volume is the name I configured, the -1480 is added automatically) but HomeKit app is asking a 8 digit code

i don't get it where I can define a code. please advice, thank you very much

**Comment by grzegorz914** [comment]
The Code is The same as for Homebridge.

**Comment by phenomeus** [comment]
alright, I try

**Comment by grzegorz914** [comment]
The receivers need to be available on Network during connection

**Comment by phenomeus** [comment]
"Volume is running on port 38873."

i had to open the port with `sudo uff allow 38873` now its working.

**Comment by grzegorz914** [comment]
U can define the port in Homebridge config

**Comment by phenomeus** [comment]
it its defined, but still, the log says its taking another port like 38873 on every restart 

` {
            "devices": [
                {
                    "name": "Volume",
                    "host": "192.168.1.27",
                    "port": 8080,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "name": "TVN 24",
                            "reference": "DVD"
                        }
                    ]
                }
            ],
            "platform": "DenonTv"
        },`

**Comment by grzegorz914** [comment]
Change the port to Your 38873

**Comment by phenomeus** [comment]
on every reboot its a new port

`Volume is running on port 39387.
[3/1/2020, 10:56:05] Please add [Volume] manually in Home app. Setup Code:`

**Comment by grzegorz914** [comment]
Where is the problem?

**Comment by phenomeus** [comment]
If I use ufw the port is changing constantly. How can I get them open when it’s random on every reboot?

**Comment by grzegorz914** [comment]
The port is getting from Homebridge and always get the same port for the same device.

**Comment by phenomeus** [comment]
The log says something different. On every reboot the port behind volume is different

**Comment by grzegorz914** [comment]
Port 8080 is the port For communication between Homebridge and Your AV Receiver, the other port is from Homebridge comunication with HomeKit app.

**Comment by grzegorz914** [comment]
Sorry but I don’t quit understood where the problem is?
The problem is not on plugin site. I don’t know what configuration U use.

**Comment by phenomeus** [comment]
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "0E:BD:B2:XX:XX:XX",
        "port": 51416,
        "pin": "XXX-01-XXX"
    },
…
            "devices": [
                {
                    "name": "Volume",
                    "host": "192.168.1.27",
                    "port": 8080,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "name": "TVN 24",
                            "reference": "DVD"
                        }
                    ]
                }
            ],
            "platform": "DenonTv"
        },


```

**Comment by grzegorz914** [comment]
I can define port for external accessory like this:

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "0E:A1:E1:99:18:C5",
        "port": 9100,
        "pin": "xxx-11-xxx"
    },
    "description": "Mostek HomeKit",
    "ports": {
        "start": 9101,
        "end": 9150,
        "comment": "W tej sekcji ustawia się zakres portów dla urządzeń rejestrujących się jako zewnętrzne akcesoria."
    },
  "platforms": [
        {
            "name": "Web UI",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "debug": false,
            "accessoryControl": {
                "debug": false
            },
            "platform": "config"
        },

```

**Comment by phenomeus** [comment]
understood! will give It a try. thnx

**Comment by danTHAman152000** [comment]
I see my Marantz SR7012 in Homebridge accessories, but cannot figure out how to get the receiver to show up in Home app. Any tips?

**Comment by grzegorz914** [comment]
Are you try this https://github.com/grzegorz914/homebridge-denon-tv/wiki#adding-to-homekit

**Comment by danTHAman152000** [comment]
Thanks for the quick reply. Yeah, it doesn't show up in my devices. Ironically, the Marantz has some type of built in HomeKit use, but it is terrible and not functional for me.

**Comment by grzegorz914** [comment]
No need to open any port. Can you disable built in HomeKit support?,
Are You before try to add AVR to HomeKit app, if yes try this:
https://github.com/grzegorz914/homebridge-denon-tv/wiki#troubleshooting

**Comment by danTHAman152000** [comment]
Thank you again. I am trying those steps now and trying to access those files. My Homebridge is on a raspberry pi. Do you recommend a mac program that I can visually delete those files? Is that via SSH? I am not too good with Terminal.

**Comment by grzegorz914** [comment]
I use FE File Explorer Pro

**Comment by danTHAman152000** [comment]
Thanks, I ended up using Terminus, found the files and deleted them. I was then able to find the receiver in Home app and added it successfully. But for some reason when the Marantz SR7012 turns off, it becomes unresponsive. This is the same problem I had on the Home Assistant's two (Denon and a Marantz plugin) so I know it's not yours. The receiver doesn't go offline with my UniFi router, but does on Home app.

**Comment by grzegorz914** [comment]
Is your receiver available on network in standby mode?, can you ping it in standby mode?, are you enable emote control in Marantz settings?

**Comment by grzegorz914** [comment]
look here: 
https://manuals.marantz.com/SR7012/EU/EN/HJWMSYmehwmguq.php

**Comment by danTHAman152000** [comment]
Aw, yes, I just saw the setting in my Marantz that standby cuts off internet connection! Thank you for your fast support, sorry my newb issues took your time! Hopefully some other dork like me will learn. BTW Terminus has that free GUI that I was easily able to delete the files. Before, I used OpenSSH or Putty but now don't have a PC and use an older Mac. 
Thanks!
