### ISSUE TITLE
Cannot find Mute button

### ISSUE THREAD

**Issue by chetstone** [grzegorz914/homebridge-denon-tv#51]
@grzegorz914 Congratulations and thanks for creating such a well-designed plugin! I am surprised at how well it works on my aging AVR-3312I. 

I cannot find a mute button on the Home app tile. Is this an issue with the Home app or is it there somewhere and I'm just not seeing it? 

Along the same lines, I am able to see a "legacy" or "additional" volume control by setting `volumeControl` to 1, but if I set it to 0 should there be a "modern" or "non-legacy" volume control somewhere I'm not seeing?

Thanks

**Comment by grzegorz914** [comment]
The mute button will only show if U enable volumeConteol as FAN 1 or Slider 2. Press the tile toggle the mute state.

If U set volumeConteol to 0(none) The volume can be control using hardware button on iPhone after u go to Remote app. In this case is not possible display mute button.

**Comment by chetstone** [comment]
Thanks for the reply. I still can't find the mute function when volumeControl is 1 or 2. When I press on the tile in the main home display all it does is open an expanded view of the tile:

![UNADJUSTEDNONRAW_thumb_2425](https://user-images.githubusercontent.com/976343/99311804-6002f780-281a-11eb-8144-86e08703615f.jpg)

There is nothing that looks like a mute button in the expanded tile, and no matter where I touch on that screen I don't see any mute event being sent to the receiver in the homebridge log.


And thanks for explaining how to use the iphone volume switches in volumeControl 0. It does work but on my receiver it only changes the volume by 0.5 dB each press and you have to wait a few seconds between presses, so not very convenient.

**Comment by grzegorz914** [comment]
Please display the volume slider as separates Tile, I this case after press it will toggle the mute state.

![46C44FEB-32A8-42DB-8FBC-96A68FEB18C6](https://user-images.githubusercontent.com/28867813/99313358-b3e3ff80-285f-11eb-9e50-f60005d36b4a.jpeg)

**Comment by chetstone** [comment]
Ah, OK thanks!

Now when I touch the volume tile it mutes but doesn't unmute when I touch it again. It just keeps sending a mute command each time I touch it. The only way to get it to unmute is to open the tile and touch the volume slider. Is this expected?
```
[11/16/2020, 3:25:10 PM] [DenonTv] Device: 192.168.1.143 Receiver Main Main Zone, set new Mute state successful: ON
[11/16/2020, 3:25:16 PM] [DenonTv] Device: 192.168.1.143 Receiver Main Main Zone, set new Mute state successful: ON
[11/16/2020, 3:25:22 PM] [DenonTv] Device: 192.168.1.143 Receiver Main Main Zone, set new Mute state successful: ON
[11/16/2020, 3:25:27 PM] [DenonTv] Device: 192.168.1.143 Receiver Main Main Zone, set new Mute state successful: ON
[11/16/2020, 3:25:35 PM] [DenonTv] Device: 192.168.1.143 Receiver Main Main Zone, set new Volume level successful: 46
```

**Comment by grzegorz914** [comment]
OK, I will look on this tomorrow.
