### ISSUE TITLE
Compatibility with Https and AVR-X5500H

### ISSUE THREAD

**Issue by coalfield** [grzegorz914/homebridge-denon-tv#54]
When accessing my AVR-X5500H on port 80 it automatically forwards to https on 10443.  This plugin is no longer working (I am guessing this happened via a firmware update).  I have tried changing the port but guessing https is the issue? 

Can you confirm is this plugin compatible with the 5500H / is there a way to configure for https?

Thanks

**Comment by sbernhardt81** [comment]
8080 ist the right port for the API.
Try this, works for me with the x2500h

**Comment by coalfield** [comment]
> 8080 ist the right port for the API.
> Try this, works for me with the x2500h

Thank you me being a dum dum.
