### ISSUE TITLE
Input switcher only support 4 devices and "show as separate fields" doesn't work correctly

### ISSUE THREAD

**Issue by melgu** [grzegorz914/homebridge-denon-tv#55]
As soon as I configure a fifth device, it shows up as a button instead of inside the input-list.
<img src="https://user-images.githubusercontent.com/9601403/102652967-8c3dcb00-416e-11eb-84eb-e45db1ce1638.PNG" alt="Screenshot" width="256">

That button is not visible in the general overview, but only inside the device itself.
<img src="https://user-images.githubusercontent.com/9601403/102653231-fce4e780-416e-11eb-8305-52ad44e33786.PNG" alt="Screenshot" width="256">
<img src="https://user-images.githubusercontent.com/9601403/102652977-9069e880-416e-11eb-95e2-49027d22af3c.PNG" alt="Screenshot" width="256">

Only when I enable "show as separate fields", does it show up in the overview. But as you can see, in that case the four other inputs are missing.
<img src="https://user-images.githubusercontent.com/9601403/102653306-1b4ae300-416f-11eb-8d23-caf283c4695d.PNG" alt="Screenshot" width="256">

This issue is specific to the this Denon plugin. The [LG TV plug-in](https://github.com/merdok/homebridge-webos-tv) for example does behave correctly.

**Comment by grzegorz914** [comment]
Config please.....

**Comment by melgu** [comment]
Quick update about the situation: After restarting both Homebridge and all devices, the fifth input device shows up in the correct place.

But, toggling "show as separate fields" still only affects the volume slider. It doesn't show the inputs as buttons like it does with the LG WebOs plug-in. I'm not sure if that's intended.

Here's my config:

```json
{
    "devices": [
        {
            "name": "Denon",
            "host": "192.168.1.30",
            "port": 80,
            "refreshInterval": 10,
            "zoneControl": 0,
            "volumeControl": 2,
            "switchInfoMenu": false,
            "inputs": [
                {
                    "name": "TV",
                    "reference": "TV",
                    "type": "HDMI",
                    "mode": "SI"
                },
                {
                    "name": "Mac",
                    "reference": "SAT/CBL",
                    "type": "HDMI",
                    "mode": "SI"
                },
                {
                    "name": "PC",
                    "reference": "GAME",
                    "type": "HDMI",
                    "mode": "SI"
                },
                {
                    "name": "Xbox 360",
                    "reference": "DVD",
                    "type": "HDMI",
                    "mode": "SI"
                },
                {
                    "name": "Fire TV",
                    "reference": "BD",
                    "type": "HDMI",
                    "mode": "SI"
                }
            ],
            "manufacturer": "Denon",
            "modelName": "AVR-X5200W"
        }
    ],
    "platform": "DenonTv"
}
```

Anyways, thanks for you great work. Really like this plug-in so far 👍

**Comment by grzegorz914** [comment]
The inputs can’t be show as separate tile. I close this as solved.

**Comment by melgu** [comment]
Ok, do you know a way to switch to a specific input using a scene or automation?

**Comment by gr8gtp** [comment]
Same question the specific input selection. Also my denon tile shows “ALL ON” instead of input selected or volume level is there a way to make it display source selected for the AVR tile?
