### ISSUE TITLE
[DenonTv] No configuration found for homebridge-denon-tv

### ISSUE THREAD

**Issue by Seexelas** [grzegorz914/homebridge-denon-tv#58]
Hi,

I have a little issue running this plugin on Hoobs on my Raspberry 3. 

Here is my configuration config.json : 

-------------------------------------------------------------------
{
    "platform": "DenonTv",
    "devices": [
        {
            "name": "AV Receiver",
            "host": "192.168.1.11",
            "port": 10443,
            "refreshInterval": 5,
            "zoneControl": 0,
            "volumeControl": 0,
            "masterPower": false,
            "switchInfoMenu": false,
            "inputs": [
                {
                    "name": "Xbox One",
                    "reference": "GAME",
                    "type": "HDMI",
                    "mode": "SI"
                },
                {
                    "name": "Television",
                    "reference": "TV",
                    "type": "HDMI",
                    "mode": "SI"
                },
                {
                    "name": "Sat Receiver",
                    "reference": "SAT/CBL",
                    "type": "HDMI",
                    "mode": "SI"
                },
                {
                    "name": "Stereo",
                    "reference": "STEREO",
                    "type": "OTHER",
                    "mode": "MS"
                },
                {
                    "name": "Multi Channel Stereo",
                    "reference": "MCH STEREO",
                    "type": "OTHER",
                    "mode": "MS"
                },
                {
                    "name": "Digital Input AUTO",
                    "reference": "AUTO",
                    "type": "OTHER",
                    "mode": "DC"
                }
            ],
            "manufacturer": "Manufacturer",
            "modelName": "Model",
            "serialNumber": "Serial Number",
            "firmwareRevision": "Firmware Revision"
        }
    ]
}
------------------------------------------------------------------

Here is what the log is telling me : 

[DenonTv] No configuration found for homebridge-denon-tv

Can you help me please ?

Thanks a lot,

**Comment by sbernhardt81** [comment]
First thing which I notice here is the port, typical port is 8080 here. Give that a try.

**Comment by grzegorz914** [comment]
Hoobs?

**Comment by Seexelas** [comment]
Hello,

Thx for your answers, yes Hoobs and my Denon is responding via HTTPS on 10443, is this important ?

**Comment by grzegorz914** [comment]
This is know issue with Hoobs, If U can move to Homebridge and Config UI X for full compatibility.

**Comment by Seexelas** [comment]
That's what i thought :/ I'm installing this on my rasp3 and let you know ! Thanks for the support

**Comment by grzegorz914** [comment]
Here all what U need to migrate to HB from Hoobs 
https://github.com/homebridge/homebridge-raspbian-image/wiki/How-to-migrate-from-HOOBS-to-Homebridge
