### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by mishakim** [grzegorz914/homebridge-denon-tv#59]
I have a Marantz receiver which has been working fine for months, but as of the last week or so is not working more often than it is. The error is below. It is reachable on the indicated IP address via web. Uplugging worked once to bring it back on line, but has not worked again.

`[1/10/2021, 1:20:52 PM] [DenonTv] Device: 10.0.1.115 Home Theater Main Zone, get current Input error: Error: connect ECONNREFUSED 10.0.1.115:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '10.0.1.115',
  port: 8080,
  config: [Object],
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}`

**Comment by grzegorz914** [comment]
Can U control the receiver using dedicated app? Please check Your network and firewall.

**Comment by grzegorz914** [comment]
May be same as #61

**Comment by mishakim** [comment]
Sounds like the same. It resolved on its own, again, but seems to recur at random times. Yes, can control with app and directly through web.

**Comment by grzegorz914** [comment]
May be try to install other version of Homebridege, I use actually HB 1.3 beta 44 and all working as excepted.
