### ISSUE TITLE
HOOBS not finding config file

### ISSUE THREAD

**Issue by miguelsasso** [grzegorz914/homebridge-denon-tv#6]
Hello

Your plugin doesn't appear to be working with HOOBS v3.1.20.

After installing the plugin, the config window displays the following:

`[]`

I would usually expect to see something along the lines of:

`{
   "platform": "DenonTv",
    "devices": [
 }`

I tried copying and pasting the sample config file.  However when I try and start the homebridge service, I get the following error message and my other plugins don't work:

`[Homebridge] [4/6/2020, 5:35:21 PM] [DenonTv] Initializing DenonTv platform...`
`[Homebridge] [4/6/2020, 5:35:21 PM] [DenonTv] No configuration found for homebridge-denontv-tv`

Thanks, Miguel

**Comment by grzegorz914** [comment]
Please post Your complete config.json file

**Comment by miguelsasso** [comment]
Hi

Thanks for getting back to me.  

My hunch is the issue is something to do with HOOBS not correctly installing your plugin.  As noted above, the config window doesn't contain the usual default text.  Then I get the error message when trying to start up the service saying 'no configuration found'.  

Re the config file, I just copied and pasted your sample config into the HOOBS UI and updated the IP.  Config.json attached... [config file.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/4438356/config.file.txt)


```
{
    "platform": "DenonTv",
    "devices": [
        {
            "name": "AV Receiver",
            "host": "192.168.1.107",
            "port": 8080,
            "switchInfoMenu": true,
            "inputs": [
                {
                    "name": "Xbox One",
                    "reference": "GAME"
                },
                {
                    "name": "Telewizor",
                    "reference": "TV"
                },
                {
                    "name": "Tuner Sat",
                    "reference": "SAT/CBL"
                },
                {
                    "name": "CD",
                    "reference": "CD"
                }
            ]
        }
    ]
}
```

Thanks, Miguel

**Comment by grzegorz914** [comment]
I see in Your config.json additional lines, U use 2times platform DenonTv, and also other config position which have nothing to do with DenonTv platform. Please see sample-config.json for correct settings.

**Comment by miguelsasso** [comment]
Hello

I agree that the config.json I posted previously wasn't correct.

I don't know if you have used HOOBS before, but we are not supposed to directly edit the config.json.  Instead we enter the config details into the HOOBS user interface.  There is something in your code which I believe is not compatible with HOOBS.

I'll try and explain.  Please see:

Attachment 1.  Config file with Denon tv uninstalled
Attachment 2.  Config file immediately after installing Denon Tv
Attachment 3.  An example config window for different plugin
Attachment 4.  The config window for your Denon tv plugin

The config window for your plugin (item 4) doesn't contain the usual code which I would expect to see (for example, item 3).  This leads me to believe HOOBS does not work with your code.

Thanks, Miguel

Attachment [1 - config (Denon Tv uninstalled).txt](https://github.com/grzegorz914/homebridge-denon-tv/files/4438775/1.-.config.Denon.Tv.uninstalled.txt)
Attachment [2 - config (after Denon Tv installed).txt](https://github.com/grzegorz914/homebridge-denon-tv/files/4438776/2.-.config.after.Denon.Tv.installed.txt)

**Attachment 3 (an example of what I expect to see)**
![3 - example  HOOBS config window for different plugin](https://user-images.githubusercontent.com/59859023/78566616-139e1500-7852-11ea-9812-092c27100f7e.PNG)


**Attachment 4 (what I see with the Denon tv plugin)**
![4 - HOOBS config window for Denon Tv plugin](https://user-images.githubusercontent.com/59859023/78566220-7f33b280-7851-11ea-9b20-ac0a16298e72.PNG)

Thanks, Miguel

**Comment by grzegorz914** [comment]
Please replace your config with this one and check of this work:

```
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023IT868M791",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-57-152",
        "username": "86:BF:61:FA:5C:67"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-tplink-smarthome",
        "homebridge-samsung-tizen",
        "homebridge-panasonic-air-conditioner",
        "homebridge-denon-tv"
    ],
    "accessories": [
        {
            "accessory": "PanasonicAirConditioner",
            "plugin_map": {
                "plugin_name": "homebridge-panasonic-air-conditioner",
                "index": 0
            },
            "password": "XXX",
            "email": "XXX",
            "name": "Air Con 1",
            "debug": false
        },
        {
            "accessory": "PanasonicAirConditioner",
            "plugin_map": {
                "plugin_name": "homebridge-panasonic-air-conditioner",
                "index": 0
            },
            "name": "Air Con 2",
            "email": "XXX",
            "password": "XXX",
            "debug": false
        }
    ],
    "platforms": [
        {
            "platform": "SamsungTizen",
            "devices": [
                {
                    "name": "Bedroom TV",
                    "ip": "192.168.1.108",
                    "mac": "f8:3f:51:e8:b5:23"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-samsung-tizen"
            }
        },
        {
            "platform": "DenonTv",
              "devices": [
        {
            "name": "AV Receiver",
            "host": "192.168.1.107",
            "port": 8080,
            "switchInfoMenu": true,
            "inputs": [
                {
                    "name": "Xbox One",
                    "reference": "GAME"
                },
                {
                    "name": "Telewizor",
                    "reference": "TV"
                },
                {
                    "name": "Tuner Sat",
                    "reference": "SAT/CBL"
                },
                {
                    "name": "CD",
                    "reference": "CD"
                }
            ]
        }
    ],
            "plugin_map": {
                "plugin_name": "homebridge-denon-tv"
            }
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}
```

**Comment by miguelsasso** [comment]
Hi

I had to start again with a fresh install of HOOBS for an unrelated reason.  Config file is slightly different now.  I did try and modify it as per your code above but it didn't work.

Would you mind editing the new config file attached?  Sorry, i'm useless with JSON code :)

Thanks

[new_config.txt](https://github.com/grzegorz914/homebridge-denon-tv/files/4443441/new_config.txt)

**Comment by grzegorz914** [comment]
Yes,

```
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY0OKE",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "C8:10:CD:A9:7A:7E"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "PanasonicAirConditioner",
            "plugin_map": {
                "plugin_name": "homebridge-panasonic-air-conditioner",
                "index": 0
            },
            "name": "Air Con 2",
            "email": "miguel_sasso@hotmail.com",
            "password": "NewAircon1357",
            "debug": false
        },
        {
            "accessory": "PanasonicAirConditioner",
            "plugin_map": {
                "plugin_name": "homebridge-panasonic-air-conditioner",
                "index": 0
            },
            "name": "Airc Con 1",
            "email": "miguelsasso@gmail.com",
            "password": "NewAircon1357",
            "debug": false
        }
    ],
    "platforms": [
        {
            "platform": "TplinkSmarthome",
            "plugin_map": {
                "plugin_name": "homebridge-tplink-smarthome"
            }
        },
        {
            "platform": "SamsungTizen",
            "devices": [
                {
                    "name": "TV",
                    "ip": "192.168.1.108",
                    "mac": "f8:3f:51:e8:b5:23"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-samsung-tizen"
            }
        },
        {
            "platform": "DenonTv",
              "devices": [
        {
            "name": "AV Receiver",
            "host": "192.168.1.107",
            "port": 8080,
            "switchInfoMenu": true,
            "inputs": [
                {
                    "name": "Xbox One",
                    "reference": "GAME"
                },
                {
                    "name": "Telewizor",
                    "reference": "TV"
                },
                {
                    "name": "Tuner Sat",
                    "reference": "SAT/CBL"
                },
                {
                    "name": "CD",
                    "reference": "CD"
                }
            ]
        }
    ],
            "plugin_map": {
                "plugin_name": "homebridge-denon-tv"
            },
            "devices": []
        }
    ]
}
```

**Comment by grzegorz914** [comment]
I don’t use HOOBS but make unnecessary modifications, just use this instruction for clean install Homebridge and Config UI X:

https://github.com/oznu/homebridge-config-ui-x/wiki

**Comment by miguelsasso** [comment]
HOOBS has worked well for me so far and I like the ability to do a backup/restore.  I might give config-ui-x a try if I have more problems going forward.

That new config worked. 

I guess I better change those passwords I posted :)

Thanks for your help, much appreciated!
