### ISSUE TITLE
Error 'ECONNRESET'

### ISSUE THREAD

**Issue by RDLF11** [grzegorz914/homebridge-denon-tv#61]
Hi there, I've been having a connection issue since the last update: 

```
[1/12/2021, 12:12:03 PM] [DenonTv] Device: 10.0.0.xx Home Theater, getDeviceInfo eror: Error: read ECONNRESET
at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  config: [Object],
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}, state: Offline
```

I haven't changed the configuration at all, and can no longer control the receiver (AVR-650H) neither from homebridge.local or from iOS (Updating/No Response).

It had been working amazing up until now. Great work on the plugin @grzegorz914

**Comment by grzegorz914** [comment]
Can U control The receiver using dedicated Denon app?  Can U Ping The receiver?

**Comment by RDLF11** [comment]
Yes, both things work just fine. I can ping it, and control it with the app or from a browser.
![image](https://user-images.githubusercontent.com/42297804/104365498-59da8000-5518-11eb-85c7-86467a717df3.png)

**Comment by RDLF11** [comment]
Okay, so after a couple restarts to the Raspberry Pi (homebridge), un-plugging and re-plugging both the power cord for the AVR and the ethernet cable, everything seems to be working fine again.

Sorry for any inconvenience I may have caused.

![IMG_0457](https://user-images.githubusercontent.com/42297804/104366957-695ac880-551a-11eb-8cdc-127ce22dfa7a.PNG)
