### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by JimmyEyeball** [grzegorz914/homebridge-denon-tv#62]
I have had the plugin running now for a few weeks with no issue on my Marantz NR1609 until today I am getting no response from the device in Homebridge. On checking the logs (below) I can see a "MaxListenersExceededWarning" So I assume this is the issue.

Is there anything I can do to resolve this? I only have x2 Plugins with 1 device each running on this bridge and as you can see the Xbox has loaded fine...

Jan 13 18:16:21 raspberrypi homebridge[6151]: [13/01/2021, 18:16:21] [XboxTv] Device: 192.168.0.39 Kids Xbox One, get current Power state successful, state: ON
Jan 13 18:16:28 raspberrypi homebridge[6151]: (node:6151) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_console_status listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
Jan 13 18:16:28 raspberrypi homebridge[6151]: (Use `node --trace-warnings ...` to show where the warning was created)

**Comment by grzegorz914** [comment]
Look Here #61,
MaxListenersExceededWarning is from Xbox plugin.

**Comment by JimmyEyeball** [comment]
No problem thanks for the quick response I will give that a go and come back...
