### ISSUE TITLE
Play Apple Music or Spotify on particular Zone

### ISSUE THREAD

**Issue by muflon-cmd** [grzegorz914/homebridge-denon-tv#63]
Hi All,
maybe I'm doing something wrong but please could you navigate me how can I play music from Apple Music App or Spotify (I have both) to created Zones? My idea (or better expectations :)) was that after creating zones in rooms I can select them from music app.

Many thanks for your work

**Comment by grzegorz914** [comment]
U need to use airplay or Spotify connect, this have nothing to do with this plugin.
