### ISSUE TITLE
Error # -104: device is unresponsive in HomeKit

### ISSUE THREAD

**Issue by RuntyCascade** [grzegorz914/homebridge-denon-tv#65]
I have a Denon S640. It was working fine for the first week I installed the plugin. When the plugin got updated a couple times, the device became unresponsive in HomeKit.

Receiver can be pinged and controlled in browser.

Logs:
```
[02/02/2021, 15:40:33] [DenonTv] Device: 192.168.1.21 Receiver, getDeviceInfo eror: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  config: [Object],
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}, state: Offline
```
Config:
```
        {
            "devices": [
                {
                    "name": "Receiver",
                    "host": "192.168.1.21",
                    "port": 8080,
                    "refreshInterval": 5,
                    "zoneControl": 0,
                    "volumeControl": 0,
                    "masterPower": false,
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "name": "Fire TV",
                            "reference": "SAT/CBL",
                            "type": "HDMI",
                            "mode": "SI"
                        },
                        {
                            "name": "Google TV",
                            "reference": "DVD",
                            "type": "HDMI",
                            "mode": "SI"
                        },
                        {
                            "name": "Switch",
                            "reference": "GAME",
                            "type": "HDMI",
                            "mode": "SI"
                        },
                        {
                            "name": "Sonos",
                            "reference": "MPLAY",
                            "type": "HDMI",
                            "mode": "SI"
                        },
                        {
                            "name": "Airplay",
                            "reference": "NET",
                            "type": "HDMI",
                            "mode": "SI"
                        }
                    ],
                    "manufacturer": "Denon",
                    "modelName": "S640",
                    "firmwareRevision": "4100-8114-8061-3085"
                }
            ],
            "platform": "DenonTv"
        }

```
![image](https://user-images.githubusercontent.com/3450439/106677995-a7be3300-656e-11eb-92c7-9cded4f8af16.png)

**Comment by grzegorz914** [comment]
Looks like problem in Your network.

**Comment by RuntyCascade** [comment]
> Looks like problem in Your network.

Is it normal for the "denon TV" accessory on homebridge to have a completely different Mac address than the receiver?

**Comment by grzegorz914** [comment]
Tamat is adres of The Accessory not The Denon itself, restar Your ruter, Denon , Homebridge. Just Switch The Power OFF nad ON.

**Comment by RuntyCascade** [comment]
> This is address  of The Accessory not The Denon itself, restar Your ruter, Denon , Homebridge. Just Switch The Power OFF nad ON.

Ok, do the logs I provided indicate what type of network issue is not allowing the plug-in to work or see my receiver?

**Comment by kwhittenberger** [comment]
Just thought I would lend a thought to this issue for you folks.  I have been getting the same error message but I have also lost my ability to connect to the receiver with the official app.  I verified all the settings and pulled the plug on the receiver but still no luck.  I went to a web browser and put the ip in the address bar to load as an HTTP endpoint (not HTTPS).  I got a certificate warning as it had re-directed to an HTTPS endpoint and when I accepted that I was able to load the browser controller and then both the app and HomeKit began working.

**Comment by RuntyCascade** [comment]
> Just thought I would lend a thought to this issue for you folks.  I have been getting the same error message but I have also lost my ability to connect to the receiver with the official app.  I verified all the settings and pulled the plug on the receiver but still no luck.  I went to a web browser and put the ip in the address bar to load as an HTTP endpoint (not HTTPS).  I got a certificate warning as it had re-directed to an HTTPS endpoint and when I accepted that I was able to load the browser controller and then both the app and HomeKit began working.
> 
> 
> 
> Tweak: I can't seem to power the receiver off but I don't see any log errors.
> 
> 
> 
> Tweak 2: And now I can power the receiver off but not sure what happened.

Ok so I also have the http to https certificate error. How did you fix that? Everytime I input the IP for the receiver on web browser it keeps giving me a certificate error.![image](https://user-images.githubusercontent.com/3450439/106822309-c33f4180-6633-11eb-9da5-51ad7eb813da.jpeg)

**Comment by kwhittenberger** [comment]
I didn't do anything specific.  I was able to look at the certificate and determined that it was issued by the parent company so went ahead and allowed the website to load in my browser on my Windows 10 desktop.  Once I did that, it was almost like it triggered something in the receiver and immediately both the app and HomeKit started working.  

I don't know when this switch to SSL happened as I can't seem to track it down but it seems weird that it isn't more clearly documented.  My pure supposition is that it was some firmware update related to HomeKit control.

**Comment by RuntyCascade** [comment]
> I didn't do anything specific.  I was able to look at the certificate and determined that it was issued by the parent company so went ahead and allowed the website to load in my browser on my Windows 10 desktop.  Once I did that, it was almost like it triggered something in the receiver and immediately both the app and HomeKit started working.  
> 
> 
> 
> I don't know when this switch to SSL happened as I can't seem to track it down but it seems weird that it isn't more clearly documented.  My pure supposition is that it was some firmware update related to HomeKit control.
> 
> 

That unfortunately did not work for me. Homebridge still may not be able to access the receiver because of the HTTP TO HTTPS certificate. Not sure how I could fix this. Can any router settings help this?

**Comment by kwhittenberger** [comment]
I wouldn’t expect the router to be able to help here.  I think the repo owner here is going to have to chine in.  Seems like the client is able to handle the non trusted certificate in my case, or it’s not getting re-directed.  Also, did you pull the power cord and plug it back in?  Don’t know if that made a difference but if the internal web server is having some kind or port exhaustion possibly it cleared that up for me.  Given the lack of logging from the receiver it’s hard to say.

**Comment by RuntyCascade** [comment]
> I wouldn’t expect the router to be able to help here.  I think the repo owner here is going to have to chine in.  Seems like the client is able to handle the non trusted certificate in my case, or it’s not getting re-directed.  Also, did you pull the power cord and plug it back in?  Don’t know if that made a difference but if the internal web server is having some kind or port exhaustion possibly it cleared that up for me.  Given the lack of logging from the receiver it’s hard to say.

Pull the plug on what? Homebridge server or receiver? Only way to connect to receiver on browser is to connect as http initially.![image](https://user-images.githubusercontent.com/3450439/106828518-3ac69e00-663f-11eb-97c1-21123d3b9d12.jpeg)

**Comment by kwhittenberger** [comment]
Receiver.  Interesting on not being able to access https directly.  I will try that when I can and see what happens.

**Comment by RuntyCascade** [comment]
> Receiver.  Interesting on not being able to access https directly.  I will try that when I can and see what happens.

Funnily enough, if I type
 ```
https://192.168.1.55:10443
```
It shows the "untrusted" certificate like as if you accessed as http.
![image](https://user-images.githubusercontent.com/3450439/106835859-eaeed380-664c-11eb-9fc0-5adf74452f2f.jpeg)
