### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by tobihoby** [grzegorz914/homebridge-denon-tv#70]
Hi,

where is the Problem:
[DenonTv] Device: 192.168.0.7 Denon Zone 2, update Device state error: TypeError: this.televisionService.getCharacteristic(...).on(...).onSet is not a function

Greets
Tobi

**Comment by tobihoby** [comment]
18.2.2021, 20:13:54 [DenonTv] Device: 192.168.0.7 Denon Zone 2, state: Online.
18.2.2021, 20:13:54 [DenonTv] -------- Denon --------
18.2.2021, 20:13:54 [DenonTv] Manufacturer: Denon
18.2.2021, 20:13:54 [DenonTv] Model: *AVR-X3200W
18.2.2021, 20:13:54 [DenonTv] Zone: 2
18.2.2021, 20:13:54 [DenonTv] ----------------------------------
18.2.2021, 20:13:54 [DenonTv] Device: 192.168.0.7 Denon Zone 2, update Device state error: TypeError: this.televisionService.getCharacteristic(...).on(...).onSet is not a function
    at denonTvDevice.prepareAccessory (/home/hoobs/.hoobs/node_modules/homebridge-denon-tv/index.js:337:5)
    at denonTvDevice.updateDeviceState (/home/hoobs/.hoobs/node_modules/homebridge-denon-tv/index.js:288:8)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by grzegorz914** [comment]
Update hb to 1.3.x beta

**Comment by kwhittenberger** [comment]
Unfortunately, until the HOOBs team upgrades, this won’t be an option.

**Comment by grzegorz914** [comment]
Then install previous version

**Comment by tobihoby** [comment]
can you please provide the last working version as a package for hoobs

**Comment by grzegorz914** [comment]
just Install from console

npm Install -g homebridge-denon-tv@pluginversion

**Comment by tobihoby** [comment]
whats the latest version for Hoobs? 3.0.0?

**Comment by grzegorz914** [comment]
I cont know, latest stałe is 3.5.9

**Comment by grzegorz914** [comment]
Latest release fixed this issue and HB 1.3.0 is already released.
