### ISSUE TITLE
Favorites [1-3] as inputs

### ISSUE THREAD

**Issue by MBarti** [grzegorz914/homebridge-denon-tv#71]
Great work!

Small thing - in the UI for config, please allow to set FAVORITES.
So I figured that to start the AVR and set it to my "Favorite 1" station (so the one remembered on one of the 3 "favorite" buttons on the remote), the config file needs to look like this - with "mode" set up as "ZM" (which cannot be set in the UI), so I had to edit it manually, and it worked.

                {
                    "name": "FAVORITE 1",
                    "reference": "FAVORITE1",
                    "type": "OTHER",
                    "mode": "ZM"
                }

Now it works flawlessly.

**Comment by grzegorz914** [comment]
Will be added in the next update.

**Comment by MBarti** [comment]
Great, thanks.
It works now - can select the favorites. 

Just a small annoyance in the Home app's UI, the "Input" doesn't stay on the item I chose. 
Example: I have as inputs "Favorite 1", "Favorite 3", "Favorite 3", "TV"... And whatever input I choose, the AVR correctly changes to it, but in the UI, the list rolls back to the first position.
