### ISSUE TITLE
Trying to pull the Volume slider below 10% results in in bouncing back.

### ISSUE THREAD

**Issue by MBarti** [grzegorz914/homebridge-denon-tv#72]
Trying to pull the Volume slider below 10% results in in bouncing back.
My set-up: Volume slider in Home app set as Fan service. AVR X-1000.

Pulling the volume slider up and down works fine. But pulling it below 10% seems to work, but the volume actually doesn't change and the slider bounces back to above 10% after a few seconds. But the log says the 5% command was sent... weird. If I pull to 0% it says the MUTE command was sent - also not doing anything (sound still plays at above 10% volume!)

In other homebridge-marantz-volume plugin everything works fine and I can set the volume to 5% without problems.

Feb 20 22:19:04 raspberrypi homebridge[13042]: [2/20/2021, 10:19:04 PM] [DenonTv] Device: 192.168.1.7 Denon All Zones, set new Volume level successful: 7
Feb 20 22:19:04 raspberrypi homebridge[13042]: [2/20/2021, 10:19:04 PM] [DenonTv] Device: 192.168.1.7 Denon All Zones, set new Volume level successful: 5
Feb 20 22:19:09 raspberrypi homebridge[13042]: [2/20/2021, 10:19:09 PM] [DenonTv] Device: 192.168.1.7 Denon All Zones, set new Volume level successful: 2
Feb 20 22:19:11 raspberrypi homebridge[13042]: [2/20/2021, 10:19:11 PM] [DenonTv] Device: 192.168.1.7 Denon All Zones, set new Mute state successful: ON

**Comment by grzegorz914** [comment]
Mamy be U have set in AVR settings min. Volume to 10%?

**Comment by MBarti** [comment]
Nope. If I did, the other plugin wouldn't work.

Just looking at the other plugin's code, there's some additional math being done to the volume, maybe that's the reason why it works fine?
https://github.com/robertvorthman/homebridge-marantz-volume/blob/master/index.js

---
ReceiverVolume.prototype.setBrightness = function(newLevel, callback) {

    if(this.mapMaxVolumeTo100){
        var volumeMultiplier = this.maxVolume/100;
        var newVolume = volumeMultiplier * newLevel;
    }else{
        //cap to max volume set in homebridge config.json
        var newVolume = Math.min(newLevel, this.maxVolume);
    }
    
    //cap newVolume.  //Denon/Marantz percentage maxes at 98 in receiver settings
    if(newVolume > 98){
        newVolume = 98;
    }

    **//convert volume percentage to relative volume
    var relativeVolume = (2 * (newVolume - 80)).toFixed(0) / 2.0;

    //cap between -80 and 0
    relativeVolume = Math.max(-80.0, Math.min(0.0, relativeVolume));**
    
    this.setControl('Volume', relativeVolume, callback);
}

**Comment by MBarti** [comment]
ok, now it's a bit better, thanks! Possible to set it to whatever % I want.

Pulling down all the way now sometimes turns on the mute, sometimes it doesn't and bounces back to 1-3%. But it's better than nothing:)
