### ISSUE TITLE
Volume not refreshed often

### ISSUE THREAD

**Issue by MBarti** [grzegorz914/homebridge-denon-tv#82]
Volume levels are ot refreshed periodically. When entering the Home app, I need to wait 3-5 seconds to see the volume update - e.g. I see it's turned off, then after a few seconds it shows the actual state of eg. 20%. 

I see that other volume plugs do polling every 5 seconds or so, to always have up to date information.

**Comment by MBarti** [comment]
Also in the control center - even many hours after I've turned off the AVR, the icon still shows that the volume is at e.g. 20%. It only updates a few seconds after I enter the home app.

**Comment by grzegorz914** [comment]
Still this exist with latest release?

**Comment by MBarti** [comment]
Now it's different - mostly "updating" to show 0% volume.
So for example I change the volume in the home app to 50%, I exit the app, then reopen it and the volume updates to 0%.
The same in the Control Center.

Log:
`
Mar 20 14:35:17 raspberrypi homebridge[18937]: [20/03/2021, 14:35:17] [DenonTv] Device: 192.168.1.7 Denon undefined, state: Online.
Mar 20 14:35:17 raspberrypi homebridge[18937]: [20/03/2021, 14:35:17] [DenonTv] -------- Denon --------
Mar 20 14:35:17 raspberrypi homebridge[18937]: [20/03/2021, 14:35:17] [DenonTv] Manufacturer: Denon
Mar 20 14:35:17 raspberrypi homebridge[18937]: [20/03/2021, 14:35:17] [DenonTv] Model: *AVR-X1000
Mar 20 14:35:17 raspberrypi homebridge[18937]: [20/03/2021, 14:35:17] [DenonTv] Zones: 1
Mar 20 14:35:17 raspberrypi homebridge[18937]: [20/03/2021, 14:35:17] [DenonTv] Firmware: 00
Mar 20 14:35:17 raspberrypi homebridge[18937]: [20/03/2021, 14:35:17] [DenonTv] Api version: 0210
Mar 20 14:35:17 raspberrypi homebridge[18937]: [20/03/2021, 14:35:17] [DenonTv] Serialnr:[censored:) ]
Mar 20 14:35:17 raspberrypi homebridge[18937]: [20/03/2021, 14:35:17] [DenonTv] ----------------------------------
Mar 20 14:35:17 raspberrypi homebridge[18937]: [20/03/2021, 14:35:17] [DenonTv] Device: 192.168.1.7 Denon undefined, update Device state error: TypeError: Cannot read property 'Power' of undefined
Mar 20 14:35:17 raspberrypi homebridge[18937]:     at denonTvDevice.updateDeviceState (/usr/lib/node_modules/homebridge-denon-tv/index.js:222:36)
Mar 20 14:35:17 raspberrypi homebridge[18937]:     at runMicrotasks (<anonymous>)
Mar 20 14:35:17 raspberrypi homebridge[18937]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Mar 20 14:35:18 raspberrypi homebridge[18937]: [20/03/2021, 14:35:18] [DenonTv] Device: 192.168.1.7 Denon undefined, set new Volume level successful: -15 dB`

**Comment by grzegorz914** [comment]
Can U post Your config

**Comment by MBarti** [comment]
{
    "devices": [
        {
            "name": "Denon",
            "host": "192.168.1.7",
            "port": 80,
            "refreshInterval": 4,
            "zoneControl": 3,
            "volumeControl": 2,
            "masterPower": true,
            "switchInfoMenu": false,
            "disableLogInfo": false,
            "inputs": [
                {
                    "name": "FAVORITE 1",
                    "reference": "FAVORITE1",
                    "type": "OTHER",
                    "mode": "ZM"
                },
                {
                    "name": "FAVORITE 2",
                    "reference": "FAVORITE2",
                    "type": "OTHER",
                    "mode": "ZM"
                },
                {
                    "name": "FAVORITE 3",
                    "reference": "FAVORITE3",
                    "type": "OTHER",
                    "mode": "ZM"
                },
                {
                    "name": "ATV",
                    "reference": "TV",
                    "type": "HDMI",
                    "mode": "SI"
                }
            ]
        }
    ],
    "platform": "DenonTv"
}

**Comment by grzegorz914** [comment]
Set zoneControl to 1 MainZone

**Comment by MBarti** [comment]
Wow, you nailed it. I redid the config and now it works fine!
Thank you very much for your amazing work!
