### ISSUE TITLE
Please explain Siri Volume service usage 

### ISSUE THREAD

**Issue by intrepidsilence** [grzegorz914/homebridge-denon-tv#84]
In the documentation you mentioned that this plug-in supports Siri volume service, but you do not explain how to use it. Asking Siri to change the volume using the name of the receiver in the home app does not work.

**Comment by grzegorz914** [comment]
https://github.com/grzegorz914/homebridge-denon-tv/commit/a5c32837386d3226cf96b479c073c960c302727d

**Comment by intrepidsilence** [comment]
I see that this turned out to be a bug and not documentation. Thanks for fixing it. I have tested and it works as expected.
