### ISSUE TITLE
[homebridge-denon-tv] This plugin generated a warning from the characteristic

### ISSUE THREAD

**Issue by hotdotdev** [grzegorz914/homebridge-denon-tv#87]
With homebridge-denon-tv v3.9.0-beta.20  receive following message:

`[homebridge-denon-tv] This plugin generated a warning from the characteristic 'Brightness': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.`

It is the same for „Volume"

**Comment by tjm7844** [comment]
This actually did come back for me on the volume setting (per #75 ), after a little bit of time.
