### ISSUE TITLE
Wiki Improvement

### ISSUE THREAD

**Issue by sbernhardt81** [grzegorz914/homebridge-denon-tv#9]
Hi Grzegorz,
thanks for the latest released Plugins (homebridge-denon-tv, homebridge-lgwebos-tv) - thats really great - I really appreciate your work!
One thing I always miss in plugin descriptions, are the description of full possibilities, like Input definitions.
Can you extend the Wiki with those Inputs?
Also helpful is a description what is possible, e.g. I can control volume via voice command because it is now a TV Service with its features.

I took definitions from https://www.openhab.org/addons/bindings/denon1/ and tried some.

       {
            "platform": "DenonTv",
            "devices": [
                {
                    "name": "AV Receiver",
                    "host": "1.2.3.4",
                    "port": 8080,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "name": "Plex",
                            "reference": "BD"
                        },
                        {
                            "name": "TV Audio",
                            "reference": "TV"
                        },
                        {
                            "name": "PS3",
                            "reference": "GAME"
                        },
                        {
                            "name": "AppleTV",
                            "reference": "MPLAY"
                        },
                        {
                            "name": "Chromecast",
                            "reference": "DVD"
                        },
                        {
                            "name": "Tuner Sat",
                            "reference": "SAT/CBL"
                        },
                        {
                            "name": "Spotify",
                            "reference": "SPOTIFY"
                        },
                        {
                            "name": "Internet",
                            "reference": "NET"
                        }
                    ]
                }
            ]
        }
> 

Best regards
Stefan

**Comment by grzegorz914** [comment]
Here U can find all possible command for x200 series:
https://usa.denon.com/us/downloads/ProductDownloads?FileName=Denon%20S%20Series%20-%20X%20Series%20RS232%20IP%20Protocol%202014.xlsx

**Comment by sbernhardt81** [comment]
Thanks, can you add it to the Wiki?

**Comment by grzegorz914** [comment]
I add this to the README.
