### ISSUE TITLE
firmwareRevision does not seem to work correctly

### ISSUE THREAD

**Issue by intrepidsilence** [grzegorz914/homebridge-denon-tv#90]
I have the following in my config.json:

"firmwareRevision": "3600-8135-1261-3085"

But what shows up in the Accessory in Homebridge UI X is:

Firmware Revision	00

**Comment by intrepidsilence** [comment]
This seems to be fixed with beta.18

**Comment by intrepidsilence** [comment]
Accidentally commented on wrong issue.

**Comment by grzegorz914** [comment]
Its not a bug.

**Comment by intrepidsilence** [comment]
So do you think this is a Homebridge bug or limitation? It does not show up correctly in Config-UI-X nor in Home.app.

**Comment by grzegorz914** [comment]
The plugin have priority to read firmware revision from Receiver, if this response is not undefined then is return the received data..
Probably Your receiver return 00.
You can ignore it, this is just info and nothing more.

**Comment by intrepidsilence** [comment]
Oh, I see. That makes much more sense. Perhaps it could be set that if the receiver returns 00 AND it is being set in the config.json then send the config.json value instead. At least then those of us who want it set can do so. Otherwise it would make sense to remove the config value from config.json and the instructions since it will not be used if the receiver can override it with an invalid value.
