### ISSUE TITLE
Config-UI-X only shows one input and button

### ISSUE THREAD

**Issue by intrepidsilence** [grzegorz914/homebridge-denon-tv#92]
Since the latest major rewrite of inputs and buttons, the UI when in Settings for this plugin only shows the first Inut and the first Button that is configured, rather than everything in the config.json.

**Comment by grzegorz914** [comment]
Probabbly bug in Config UI X

**Comment by grzegorz914** [comment]
Checked this behaviour and all displays correct on my site, all inputs are displayed in Config UI X

**Comment by grzegorz914** [comment]
This is Bug in Config-UI-X, I have reported this but not fixed yet.

**Comment by intrepidsilence** [comment]
Could you link to the config-ui-x bug here, please? Thanks!

**Comment by grzegorz914** [comment]
This is fixed in latest beta Config-UI-X v40.5.5-test.5
https://github.com/homebridge/homebridge-config-ui-x/pull/1504

**Comment by intrepidsilence** [comment]
Great news!
