### ISSUE TITLE
Remote Control App - Cannot select AppleTV

### ISSUE THREAD

**Issue by hansw1204** [grzegorz914/homebridge-denon-tv#93]
I now cannot select Apple TV as the controlled device in the Remote Control App. Only my AVR can be selected

**Comment by grzegorz914** [comment]
This have nothing to do with this plugin.

**Comment by hansw1204** [comment]
Sorry, I am new to this. I noticed this after I installed the plugin and made a button for the AppleTV input which generates the option in the Remote App to select the AVR as an alternative source. Then the AppleTV cannot be selected anymore. When I remove that button in the plugin the option disappears and everything is fine again. I have added the Apple TV as an Input source and that works just fine.
