### ISSUE TITLE
what is this for an misstake?

### ISSUE THREAD

**Issue by kusselin** [grzegorz914/homebridge-denon-tv#99]
Hi, i installed the plugin and restart the homebridge..then this is comming out in the console:
`4/6/2021, 8:51:56 PM] [DenonTv] Device: 192.168.200.24 AV Receiver, prepareInformationService error: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at denonTvDevice.prepareAccessory (/usr/lib/node_modules/homebridge-denon-tv/index.js:291:55)`

what must i do.

best regards and thanks

**Comment by grzegorz914** [comment]
Restart again and all will be OK.

**Comment by kusselin** [comment]
O.K. thanks and with my denon x1500h, the network is always on .... when I switch off the receiver at the main switch, no red text or errors may appear in the Homebridge log ... right?

**Comment by grzegorz914** [comment]
right, only if the receiver will offline the red warning will appear in the log

**Comment by kusselin** [comment]
But when I´m finish with tv and i go to bed a will turn off the receiver and then the LOG will full all over..you know what i mean?

**Comment by grzegorz914** [comment]
It is correct, because Your receiver is offline. 

In normal case the Receiver need to be in Standby mode.

**Comment by kusselin** [comment]
But then you have much elecricity price :-)

**Comment by grzegorz914** [comment]
In Standby The Power is < 1W 😂

**Comment by grzegorz914** [comment]
For power save also switch power OFF for homebridge then You have no red log and saved much price.
